### ISSUE TITLE
Выбрать инструмент для ведения дискуссий и управления задачами

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#1]
К сожалению, эта дискуссия была начата в чате и ее начало может быть непонятно стороннему наблюдателю. Мы не будем решать эту проблему.

Результатом решения этой issue должны стать выбранные  и внедренные инструменты для ведения дискуссий и задач. Возможно, как одно решение, так два отдельных --это тоже предмет дискуссии.

До принятия решения дискуссии ведем в issues этого репозитория.

**Comment by glitchcore** [comment]
Еще раз скажу свою позицию: принципиальные вопросы, решение которых = новое правило или инструкция, предлагаю вести здесь, с дальнейшим внесением в вики. Или в формате PR.

Я считаю, что нужно выбрать именно трекер для повседневных задач

**Comment by kaero** [comment]
> Я считаю, что нужно выбрать именно трекер для повседневных задач

Я не понимаю, как различать "повседневные" и требующие обсуждения задачи. Любая "повседневная" задача может потребовать обсуждения до начала ее выполнения или в процессе. Само по себе обсуждение -- это тоже задача, по хорошему нужно чтобы за него был ответственный заинтересованный в результативности этого обсуждения.

Поэтому, я считаю, что трекер задач подходит в качестве инструмента для управления задачами, и дискуссий в частности.

**Comment by sntxerror** [comment]
Считаю важным в первую очередь разработать систему оценки и сравнения инструментов. Нам нужно собрать требования к ним и характеристики которые важны именно нам. А потом уже примерять решения.

**Comment by kaero** [comment]
> систему оценки и сравнения инструментов. 

В первую очередь, мне кажется, нужно решить каких инструментов. Мы еще не решили, что мы тут выбираем: только трекер или отдельно трекер и средство для ведения дискуссий. 

Если решим, что нам нужны два разных инструмента, то разнести выборы в отдельные issue.

**Comment by glitchcore** [comment]
> Я не понимаю, как различать "повседневные" и требующие обсуждения задачи. Любая "повседневная" задача может потребовать обсуждения до начала ее выполнения или в процессе. Само по себе обсуждение -- это тоже задача, по хорошему нужно чтобы за него был ответственный заинтересованный в результативности этого обсуждения.

результаты выполнения «повседневных» задач не отражаются в wiki

**Comment by sntxerror** [comment]
> > Я не понимаю, как различать "повседневные" и требующие обсуждения задачи. Любая "повседневная" задача может потребовать обсуждения до начала ее выполнения или в процессе. Само по себе обсуждение -- это тоже задача, по хорошему нужно чтобы за него был ответственный заинтересованный в результативности этого обсуждения.
> 
> результаты выполнения «повседневных» задач не отражаются в wiki

Не согласен. Судя по опыту любая задача может стать поводом для внесения правок в доку.

**Comment by kaero** [comment]
> результаты выполнения «повседневных» задач не отражаются в wiki

Сомнительное утверждение.

> новое правило или инструкция, предлагаю вести здесь, с дальнейшим внесением в вики. Или в формате PR.
> Я считаю, что нужно выбрать именно трекер для повседневных задач

Чем эта дискуссия отличается от задачи?

**Comment by glitchcore** [comment]
> Чем эта дискуссия отличается от задачи?

в результате этой дискуссии у нас появится правило о том, где обсуждать задачи.

Например, после выполнения задачи «купить туалетной бумаги» в вики ничего не изменится

**Comment by sntxerror** [comment]
> Чем эта дискуссия отличается от задачи?

Нет ответственного, нет сроков, нет DoD, нет категории, нет статуса кроме открыто/закрыто.

**Comment by kaero** [comment]
> Нет ответственного, нет сроков, нет DoD, нет категории, нет статуса кроме открыто/закрыто

partially fixed

**Comment by glitchcore** [comment]
Принципиально — эти обсуждения буквально означают «обсуждения», в них не нужно ничего делать кроме принятия какого-то решения, и назначать на них ответственного тоже выглядит странно

**Comment by glitchcore** [comment]
Если в процессе выполнения задачи возникает какая-то всенепонимающая жопа, нужно пойти сюда и создать дискуссию, хорошо, если по окончании сформируется правило или будет изменено текущее

**Comment by kaero** [comment]
Принятие решения -- есть действие, нет? В результате дискуссии появляется какой-то артефакт, не обязательно материальный, как в результате решения задачи. 

На мой взгляд ничем не отличающиеся задачи:
- купить туалетную бумагу
- договориться с арендодателем о вывозе старых ламп
- договориться, где вести дискуссии и задачи

**Comment by glitchcore** [comment]
> * купить туалетную бумагу
> * договориться с арендодателем о вывозе старых ламп

мое предложение: в трелло появляется колонка todo, когда кто-нибудь берет задачу, переносит ее в doing и назначает себе, если в процессе выполнения у него возникает необходимость обсудить и он не может найти ответ в правилах, идет в github и создает issue, потому что это буквально баг в нашей системе правил.

**Comment by glitchcore** [comment]
> в трелло

но может и не в трелло, но мы уже им пользуемся

**Comment by kaero** [comment]
>  это буквально баг в нашей системе правил.

В таком случае у нас будет свод правил на все случаи жизни, всегда неполный -- с одной стороны, но с кучей одноразовых правил -- с другой, которые были выведены в ходе дискуссии к конкрентной задаче и ни разу более не использовались и не будут.

Руководствоваться таким сводом правил будет настолько сложно, что практически невозможно.

**Comment by glitchcore** [comment]
> В таком случае у нас будет свод правил на все случаи жизни, всегда неполный -- с одной стороны, но с кучей одноразовых правил -- с другой, которые были выведены в ходе дискуссии к конкрентной задаче и ни разу более не использовались и не будут.
> 
> Руководствоваться таким сводом правил будет настолько сложно, что практически невозможно.

я предлагаю попробовать. До сих пор у нас не было прям кучи острых обсуждаемых вопросов

**Comment by kaero** [comment]
На мой взгляд процесс такой:
- если в ходе задачи возникает обсуждения, то оно и должно происходить в контексте задачи, а инструмент должен помогать собирать контекст
- если обсуждение повторяется в другой задаче, то на основе этих случаев можно решить стоит ли завести правило, или это все еще частные случаи

**Comment by glitchcore** [comment]
> * если обсуждение повторяется в другой задаче

только ты не узнаешь об этом, если не участвовал в предыдущем обсуждении

**Comment by glitchcore** [comment]
в общем, я предлагаю конкретно в этих issues дискутировать именно о правилах и других вещах, которые будут добавлены в wiki

**Comment by kaero** [comment]
> только ты не узнаешь об этом, если не участвовал в предыдущем обсуждении

Да, все так. Также как при решении следующей задачи будет сложно найти все правила, под которые она подходит.

**Comment by kaero** [comment]
> в общем, я предлагаю конкретно в этих issues дискутировать именно о правилах и других вещах, которые будут добавлены в wiki

https://github.com/b4ck5p4c3/wiki/issues/1#issuecomment-547073101

**Comment by glitchcore** [comment]
окей. Может быть, начнем обсуждать здесь вообще все, а когда упремся в ограничения, будем думать о миграции?
У меня есть ощущение, что не попробовав, мы не поймем чего хотим

**Comment by kaero** [comment]
Ну, так одна из опций, которые мы рассматривали в чате до дискуссии здесь и звучала, как "использовать GitHub Issues для всего".

Напомню, что среди минусов:
- Отсутствие ACL: все задачи публичны, можно только запретить комментарии для всех, кроме участников
- Плохой полнотекстовый поиск

Ставьте ваши :+1: если вам норм github issues для ведения задач (доску можно завести тоже в github) и :-1:  если вы против.

**Comment by glitchcore** [comment]
> вам норм github issues для ведения задач

мы используем issues к репозиторию wiki?

**Comment by kaero** [comment]
> мы используем issues к репозиторию wiki?

можно завести отдельный, но я бы пока наваливал все в кучу, применяя решения по мере возникновения проблем с этой кучей

**Comment by z4fd** [comment]
В общем я тут немного поковырял Gitlab и вот что мне понравилось и почему к нему стоит присмотреться:
- Нет ограничений ни в приватных репах, ни в кол-ве участников, ни в кол-ве групп и подгрупп
- Более фичастый issue tracker 
  - Создание issues через мыло https://gitlab.com/help/administration/incoming_email.md
  - Тайм трекинг https://gitlab.com/help/workflow/time_tracking.md
  - Deadline у issue
- Наличие ACL во всем https://gitlab.com/help/user/permissions
- Встроенная Wiki является полноценной репой со всеми вытекающими https://gitlab.com/help/user/project/wiki/index.md
- Наличие TODO дашборда https://gitlab.com/help/workflow/todos.md
- Он опенсорсный и если им приспичит закрыть сервис или нам переехать, это можно будет сделать

Все что я написал относиться к бесплатному тарифу

**Comment by glitchcore** [comment]
> В общем я тут немного поковырял Gitlab и вот что мне понравилось и почему к нему стоит присмотреться:

выглядит круто, можем попробовать переехать

**Comment by glitchcore** [comment]
А у них есть CI на кастомный домен?

**Comment by z4fd** [comment]
> А у них есть CI на кастомный домен?

Ты про Continuous integration  или про хостить статичный сайт с кастомным доменом? Eсли про второе то да, он как и гитхаб может в это https://docs.gitlab.com/ee/user/project/pages/custom_domains_ssl_tls_certification/

**Comment by glitchcore** [comment]
Я за переезд в гитлаб

**Comment by glitchcore** [comment]
С другой стороны, гитхаб, кажется, более популярен. В общем, интересно мнение других

**Comment by z4fd** [comment]
> С другой стороны, гитхаб, кажется, более популярен. В общем, интересно мнение других

Если ты про то что там надо будет заново регаться то у них куча провайдеров через которые можно войти, github в том числе :))


  

-  GitHub
-  Bitbucket
-  GitLab.com
-  Google
-  Facebook
-  Twitter
-  Shibboleth
-  SAML
-  Crowd
-  Azure
-  Auth0
-  Authentiq
-  OAuth2Generic
-  JWT
-  OpenID Connect
-  UltraAuth
-  Salesforce

https://docs.gitlab.com/ee/integration/omniauth.html

**Comment by glitchcore** [comment]
> Если ты про то что там надо будет заново регаться

скорее про то, что надо будет заново учиться пользоваться, ну и в целом инструмент непривычный для многих

**Comment by kaero** [comment]
> Встроенная Wiki является полноценной репой со всеми вытекающими 
> https://gitlab.com/help/user/project/wiki/index.md

это есть и в github

> Наличие TODO дашборда https://gitlab.com/help/workflow/todos.md

в github есть проекты с досками

**Comment by kaero** [comment]
> Он опенсорсный и если им приспичит закрыть сервис или нам переехать, это можно будет сделать

Он _частично_ опенсорсный :)

Инструментов миграции из hosted в self-hosted ничего, кроме git-репозиториев нет. Придется писать скрипты, использующие API, что возможно и с github, и с другими решениями.

**Comment by kaero** [comment]
> Наличие ACL во всем https://gitlab.com/help/user/permissions

@z4fd я не увидел там никаких принципиальных отличий от github:

> https://gitlab.com/help/user/permissions#permissions
>
> On public and internal projects the Guest role is not enforced. All users will
be able to create issues, leave comments, and clone or download the project code.

**Comment by kaero** [comment]
https://github.com/b4ck5p4c3/wiki/issues/1#issuecomment-547138408

Из реальных плюсов, относительно GH я вижу только:
- отсутствие ограничения на количество приватных репозиториев (мы пока не придумали зачем бы они могли быть нам нужны)
- срок у тикетов
- таймтрекинг (тоже не вижу зачем он нам может быть нужен)

Меня волнует только то, как мы перенесем уже появившуюся историю issues из одного сервиса в другой.

**Comment by glitchcore** [comment]
У меня на одной чаше весов:
1. Потенциальные квази-политические проблемы с гитхабом
2. Теоретическая возможность сделать self-hosted (хотя хз нужно ли)

На другой чаше:
1. github привычный инструмент для организации различных открытых штук, к нему привыкли
2. Нужно теперь будет как-то переносить все из гитхаба в гитлаб

**Comment by kaero** [comment]
> 1. Потенциальные квази-политические проблемы с гитхабом

Они возможны и с gitlab

> 2. Теоретическая возможность сделать self-hosted (хотя хз нужно ли)

 Имейте в виду, что открыто и бесплатно там доступны далеко не все фичи ;)

**Comment by glitchcore** [comment]
В общем у меня пока формируется уверенность в том, что нужно все задачи вести на данном этапе просто в issues репозитория wiki в гитхабе.

**Comment by z4fd** [comment]
> Меня волнует только то, как мы перенесем уже появившуюся историю issues из одного сервиса в другой.

Бегло просмотрел и их можно экспортнуть через API, вопрос в том насколько "больно" :D 
https://developer.github.com/v3/issues/



> это есть и в github

Как инструмента нет, но да, можно вполне просто отдельную репу юзать под это :) 




> в github есть проекты с досками

Трелло борды тоже есть, но на мой вкус это штука удобней. Зашел и сразу видишь все что на тебе висит, но это и правда пустяк



> On public and internal projects the Guest role is not enforced. All users will
> be able to create issues, leave comments, and clone or download the project code.

Я про вот это
>Guest users can only view the confidential issues they created themselves
>Guests are not active contributors in private projects. They can only see, and leave comments and issues.

Но гитовую подобную страничку сходу я не смог нагуглить, так что спорить не буду


>отсутствие ограничения на количество приватных репозиториев (мы пока не придумали зачем бы они могли быть нам нужны)

Я не вижу причин для того чтобы все было исключительно публичным

з.ы. 42 get

**Comment by kaero** [comment]
> Бегло просмотрел и их можно экспортнуть через API, вопрос в том насколько "больно" :D
> https://developer.github.com/v3/issues/

Да API GH я знаю наизусть в силу жизненных обстоятельств. Вопрос в том, как импортировать эти данные в GitLab? Как вот эту issue с сохранением авторства, порядка и ссылок перенести в GitLab? На первый взгляд никак.

> Как инструмента нет, но да, можно вполне просто отдельную репу юзать под это :)

Есть, [вот же](https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally)

> Трелло борды тоже есть, но на мой вкус это штука удобней. Зашел и сразу видишь все что на тебе висит, но это и правда пустяк

Это не какая-то отдельная функциональность. Это возможность собирать доски из issues, дискуссий и pr без приявзки к конкретному проекту. https://help.github.com/en/github/managing-your-work-on-github/managing-project-boards

Увидеть что висит на тебе можно и без этого при помощи фильтра в рамках отдельного репозитория, или на своем дашборде в рамках всего github.

> Но гитовую подобную страничку сходу я не смог нагуглить, так что спорить не буду

Это совсем другая функциональность. Возможность приватного репортинга security issues есть и на GitHub, и даже возможность создавать приватные форки независимо от тарифного плана для этого. Это для репортинга уязвимостей. Использовать это для любых тредов несколько больно.

> Я не вижу причин для того чтобы все было исключительно публичным

Я вижу причины для закрытых issues на некоторые темы, например, некоторых юиридических вопросов, которые могут включать конфиденциальную, и чувствительную персональную информацию.

А вот репозитории с кодом какого рода у нас могут быть приватные, я хз. Сейчас в приватном репо лежит только связка ключей, но она зашифрована.

**Comment by glitchcore** [comment]
Предлагаю перенести обсуждение в #16 и #17 и закрыть issue.

**Comment by kaero** [comment]
Поддерживаю

**Comment by sntxerror** [comment]
Не согласен с закрытием. Комент https://github.com/b4ck5p4c3/wiki/issues/1#issuecomment-547069205 проигнорирован, требования не выработаны, текущий инструмент выбран просто так.

**Comment by glitchcore** [comment]
Именно. Моя позиция — начать пользоваться любым инструментом, приобрести опыт, понять, чего мы хотим. Сейчас как-то формализовать более чем «нам нужно место где можно создавать сущности-задачи и отдельно их обсуждать» у меня не получается.

**Comment by sntxerror** [comment]
Как верно подметил @kaero нужно для начала понять что вообще мы выбираем. Это понимание уже потерялось судя по обсуждению.

Затем исходя из задач мы определим список конкретных must-have фич. После, выберем потенциально подходящие тулы и составим сравнительную таблицу тулов по фичам. Дальше взвешивание, вывод и выбор.

**Comment by sntxerror** [comment]
Итак. Что мы вибираем?

- систему ведения проектов и задач?
- систему публичного обсуждения тем?
- систему документации?
- ваш вариант?
- все сразу?

p.s. здесь нет опросов. это жаль.

**Comment by glitchcore** [comment]
Выбираем систему, которая позволит раздавать и обсуждать задачи, обсуждать и править документацию.
Для меня «обсуждение тем» очень сливается с пунктами выше.

**Comment by a-andreyev** [comment]
> gitlab

@z4fd, поделюсь опытом "gitlab vs github", который я видел в проекте [matrix](https://github.com/matrix-org/):

Им не подошёл гитхаб для [одной репы](https://github.com/matrix-org/olm) -- где лежит реализация алгоритма криптографии. Как объясняется, для работы с ней на github требовалась лишняя бюрократия через океан.

Но при этом проект не уехал полностью на self-hosted решение. Насколько я понимаю, для узнаваемости. Благодаря популярности github большее число людей сможет узнать о проекте. Мне кажется, на текущий момент это ключевое отличие. В целом и gitlab, и github вполне себе известны и популярны среди разработчиков, а их функционал очень похож.

В случае с проектом matrix все проекты, которые можно, ведутся на github, а исключения на self-hosted gitlab.

> инструмент для дискуссий и управления

Предлагаю начать с инструмента для работы с перепиской. Мне кажется, узким местом сейчас может быть разрозненность обсуждений по площадкам.

Предлагаю для работы с перепиской Matrix IM. Благодаря заявляемой интероперабельности, сможем [подключить](https://matrix.org/bridges/) остальные инструменты (tg,github/gitlab,trello,jira,snipe-it,etc) в общую инфраструктуру.

Согласен с тем, что нужно определиться с критериями, по которым стоит делать выбор того или иного инструмента.

Мне кажется, чтобы этого достичь, нужно с помощью временных инструментов, что уже есть сейчас, определиться со сверх-задачами: чем должен быть и не быть хакспейс.

**Comment by glitchcore** [comment]
В общем еще раз скажу свою точку зрения: сейчас решение этого вопроса блокирует многие другие и от этого возникает много давления. Одновременно с этим, мне кажется, что сейчас найти идеальное решение у нас не получится, как и какие-то гарантирующие правильный выбор метрики.
Мне кажется, что нужно взять гитхаб как первый шаг, начать в нем работать, попутно не останавливать поиски более удобного инструмента. Тот же матрикс (и любой другой инструмент) можно будет попробовать более спокойно, сравнить его с гитхабом, и если там будет удобнее — частично или полностью переехать.

**Comment by kaero** [comment]
Давайте так.

@z4fd @kaero @aanper @sntxerror @dm-shi 

Кому-нибудь из нас неудобно сейчас пользоваться GitHub Issues для 
- заведения, обсуждения, назначения и закрытия задач?
- ведения обсуждений?

Никакие другие проблемы тут не обсуждались и не подоразумевались, откуда @sntxerror в  https://github.com/b4ck5p4c3/wiki/issues/1#issuecomment-547434233 увидел тут выбор системы документации я не понял. 

Документация у нас в репозитории.

Ответ на вопрос 

> Итак. Что мы вибираем?

находился и находится до сих пор в описании этого  issue https://github.com/b4ck5p4c3/wiki/issues/1#issue-513458747

----

Если кому-то действтельно неудобно решать указанные в топике проблемы тут, то давайте выбирать другое средство по критерию "всем текущим участникам удобно". В таком случае, каждый напишите свои критерии удобства.

----

Меня GitHUb Issues устраивают для решения обоих озвученных проблем в настоящий момент.

Для решения проблемы _заведения, обсуждения, назначения и закрытия задач_ для меня действительно важно (необходимо):
- возможность развернутого обсуждения
- статус открыт/решен
- возможность назначить исполнителя

Для решения проблемы _ведения обсуждений_ для меня важно
- возможность развернутого обсуждения
- явного включения необходимых участников (призыв к комментарию)
- не необходима, но желательна, возможность как-то пометить дискуссию завершенной

Все отальное может быть приятными плюшками, удобствами, но не является лично для меня необходимым, потому GitHub Issues полностью устраивают меня в обоих ролях

----

**Снова! Внимание! Внимание! Если вам неудобно испоьзование GitHub Issues в одной из ролей, то напишите об этом и укажите, каких качеств вам нехватате для возможности использования их в такой роли.** При этом прошу руководствоваться не соображениями "в сервисе Х есть фича У, а тут нет", а каких именно инструментов вам прямо сейчас в текущих задачах и дискуссиях не хвататет.

**Comment by sntxerror** [comment]
GitHub Issues для ведения задач неудобны мне как минимум тем, что:
- нет разделения постановка задачи/обсуждение (все содержимое issue - одноуровневые комментарии)
- нет статусов кроме открыт/закрыт (in progress, on hold, etc..)
- нет зависимостей и связей с другими issue (завит от, начнется после и тд)
- нет разграничения доступа
- не видны на борде и кажется тут нет борды задач в целом, поскольку и задач как сущности тоже нет
- нет сроков и DoD
- github не является системой управления проектами и задачами и то что мы делаем – мимикрия

**Comment by a-andreyev** [comment]
> нет борды

@sntxerror, насколько я понимаю, есть. И есть возможность автоматизировать нахождение каких-либо карточек-issue в тех или иных отделах доски:

[Вот](https://github.com/quotient-im/libQuotient/projects/2?fullscreen=true) пример проекта, где есть группировка "automated as ..." (в столбце in work, например).

Но замечание насчет рассмотрения отдельной системы, заточенной на управление проектами и задачами -- понятно.

**Comment by sntxerror** [comment]
То что есть борда это хорошо! Спасибо за инфу. В целом я готов принять github как первоначальный инструмент постановки и учета задач. Потребность связей задач и постановки их во времени конечно не отпадает, но ею можно пренебречь. Одноуровневые комментарии я попробую пережить.

Всяко это лучше чем ничего.

Тем не менее предлагаю в следующем подходе все же формализовать наши общие требования, а не просто кидаться аргументами.

**Comment by glitchcore** [comment]
> То что есть борда это хорошо! Спасибо за инфу.

да, я заценил тоже, круто. Создал канбан-проект для примера: https://github.com/b4ck5p4c3/wiki/projects/2

> В целом я готов принять github как первоначальный инструмент постановки и учета задач

Я предлагаю принять GH вместе с правилом смены инструмента. Предлагаю такой механизм: если кто-то находит более удобную и подходящую систему, то поднимает её где-то, заинтересованные пробуют делать в ней типичные для нас кейсы, предметно сравнивают с текущим инструментом и тогда принимаем решение о переезде.

> Одноуровневые комментарии я попробую пережить.

мне тоже не нравятся :( но, наверное, это не так критично, если не раздувать дискуссию (эта ветка — скорее пример того, как не должно быть)

**Comment by glitchcore** [comment]
Если такой подход не вызывает вопросов, предлагаю зафиксировать систему через рассмотрение PR #16, текущий issue закрыть

**Comment by kaero** [comment]
> нет зависимостей и связей с другими issue (завит от, начнется после и тд)

Скоро подъедет, уже в бете

> нет разделения постановка задачи/обсуждение 

Или я не понимаю о чем речь, или есть. Наверху постановка, это не комментарий. Все могут ее редактировать. В API это тоже отдельное поле, а не коммент.

> github не является системой управления проектами и задачами и то что мы делаем – мимикрия

Сам GH декларирует Issues & Projects именно так.

> нет разграничения доступа

Гибкого ACL для Issues нет, есть Security issues pioeline (такой тикет видит только автор и выделенная команда, можно использовать для abuse) и обсуждения внутри команд. Это все не ACL уровня Я.Трекера или JIRA, но мы пока не приняли решение, что нам нужно вести приватно, потому и реальной проблемы тут пока никакой нет.

**Comment by kaero** [comment]
Ещё раз, я напомню, что я просил писать не в терминах абстрактных фич, которых нет, иначе выигрывают большие платные трекеры: JIRA, Tracker, MS Project, .. , но у нас нет необходимости в их фичах.
