### ISSUE TITLE
Порядок финансовых расчетов

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#100]
Решить как мы сводим баланс за месяц:
- взносы участников
- безвозмесдные взносы
- покрытие разницы расходов и взносов организаторами

Решением будет описанный и зафиксированный в вики порядок расчетов

**Comment by kaero** [comment]
Ничерта не решили, оставили на совести организаторов

**Comment by glitchcore** [comment]
Предлагаю закрыть и продолжить обсуждение в почте
/d
