### ISSUE TITLE
Мануал по организации мероприятий

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#101]
Записать все то, что у нас сейчас в чатах и гловах касательно организации мероприятий в виде хотя бы чеклиста в вики.

Сходу из моей головы:
- анонс хотя бы за неделю
- дату, время, место, описание
- обсудить с докладчиком формат: мастер-класс, где людям требуются рабочие места (лимит людей ~16 человек); или лекционный (лимит людей ~35 человек)
- обсудить с докладчиком возможность и желание видеозаписи и трансляции
- подготовка места к мероприятию: убрать/собрать столы, навести порядок, поставить стулья
- пиццуня
- отметить все это в календаре как можно раньше

**Comment by heeeyflo** [comment]
Я бы добавил ещё:

 — техрайдер (например, на мероприятии используется 802.11b-only железка, а у нас дефолтная сеть ac/n-only, или для мастер-класса требуется десять программаторов, которые срочно нужно отыскать)

 — мы на встрече 11/26/2019 обсуждали создание документа, описывающего потенциальные риски докладывающей стороны. Нужно сформулировать основные принципы этого документа и добавить их в условную форму "запроса на проведение мероприятия", чтобы убедиться что раскрывающая сторона осознает все риски

**Comment by kaero** [comment]
аддон на встрече 2019-12-10
- назначать ответственного со стороны спейса
- доступы к анонсу события где бы он ни был для отвественного со стороны спейса

**Comment by glitchcore** [comment]
Предлагаю кому-нибудь заняться PR, в т.ч. добавить #18

**Comment by glitchcore** [comment]
> Предлагаю кому-нибудь заняться PR, в т.ч. добавить #18

я и займусь, позже
