### ISSUE TITLE
Порядок приема участников

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#102]
Людям сейчас никак не очевидны следующие вещи:
- как стать участником (чего куда писать, платить, идти...)
- как стать резидентом
- как занести денег явно разметив "это безвозмездный донат, делайте что хотите" или "это взнос за участие, хочу быть участником, когда как куда продлевать"

Нужно все это обсудить, зафиксировать в вики, написать псто в канал

**Comment by kaero** [comment]
На сайте сейчас есть проблемы:
- есть ссылка на карты, но она мало помогает ориентироваться на местности и найти вход
- непонятно когда открыто, нужно написать инструкцию: посмотрите в календарь, напишите в чат

@valdikss готов сделать изменения на сайте, @sntxerror посодействовать

**Comment by kaero** [comment]
Написать огромными буквами:
- если вы хотите стать участником, то ...
- явно написать про "уровни" участников и гостей, есть референс имени @aanper в ветке https://github.com/b4ck5p4c3/0x08.in/commits/authorization_rules

@ValdikSS

**Comment by kaero** [comment]
Завести отдельную страничку по контенту аналогичную рассказу про наш хакспейс на 0day

@kaero

**Comment by kaero** [comment]
Онлайн-формы по умолчанию донат, участники сами знают как хэндлить платежи. Нужно чуть более явно написать об этом на форме.

@sntxerror

**Comment by kaero** [comment]
обработать сисок уже заплатившим за мембершип и больше

@sntxerror

**Comment by lomalkin** [comment]
Предлагаю на главной добавить ссылку  "Как нас найти" на страницу с подробным описанием этого. А то получается как с BeerAndCakes в первый раз, типа "спасибо, что нашли нас".

**Comment by kaero** [comment]
И вывеску сделать. 

Но в целом у нас кажется и так на каждом углу написано, что точка на карте установлена точно (в каждом ивенте), но никто не читает, потому не думаю, что сайт поможет. Что, конечно, не значит, что сделать не нужно -- спасет пару душ :)

**Comment by ValdikSS** [comment]
Я в пятницу начал делать это:
https://github.com/ValdikSS/0x08.in/commit/2b0afdd532da143c4447ae78bfb09512f8178613
Прямо на главной странице картинка с картой.

 ![Как пройти](https://i.imgur.com/7OmCMgN.jpg) 

Сегодня (в воскресенье) доделаю и отправлю реквест. И для порядка приёма напишу черновик, прокомментируете.

**Comment by kaero** [comment]
Попросил пару знакомых гостей рассказать в лс, что вызвало трудности, и что по их мнению помогло бы с локальной навигацией (когда до адреса уже добрался).

**Comment by ValdikSS** [comment]
Какой-нибудь вывески не хватает. Хотя бы внутри, через стекло.

**Comment by lomalkin** [comment]
> Какой-нибудь вывески не хватает. Хотя бы внутри, через стекло.

Она как раз была в плане, какое-нибудь светящееся табло в аквариуме, заметное с улицы, видимо таки будет.

**Comment by lomalkin** [comment]
#113
