### ISSUE TITLE
Формализовать оплату мембершипа

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#106]
Пока у нас нет возможности создавать полноценные подписки с рекуррентными платежами, предлагаю чётче сформулировать принципы оплаты, в частности — дату. Например, обусловиться что оплата вносится не позже шестого числа каждого месяца (удобно привязано к авансовой части зарплаты).

Ещё с имейлами в платежах такая тема, что при увеличении количества людей (следовательно, появления уже менее знакомых персон) будет сложновато как-то сопоставить реального человека и почту. У меня пока нет идей как это пофиксить не запрашивая номер паспорта, структурный снимок лица, CVV карточки и девичью фамилию матери, так что тут нужен **#дискасс**

Мы так же рассуждали на собрании о том, что было бы неплохо чтобы перед тем как стать участником сообщества, люди приходили на денёк и знакомились с нами, следует, наверное, четко зафиксировать что этот "ознакомительный" день не требует оплаты (если оно так).

Related to #102

**Comment by NetBUG** [comment]
1) согласен
2) мне кажется, в хакспейсе человек волен выбирать способ самоидентификации фрагментом текста. Т.е. достаточно, чтобы платёж пришёл с комментарием «от @fuckyeahbaby за небритябрь 2024 года» и человек корректно идентифицировал себя при (первом) визите в хайспейс, дальше можно установить корреляцию между биометрическими/антропометрическими свойствами биообъекта и его текстовой идентификацией. На мой взгляд, решение понадобится, но проблема пока явным образом не вылезла и вряд ли вылезет, пока существуют ~6 мемберов, из которых 100% появляются достаточно часто.
Скорее может появиться задача «быстро отличить мемберов от гостей».

3) да, вроде все согласились на встрече

**Comment by kaero** [comment]
+1 к мнению @NetBUG по второму пункту. Человек передает один идентификатор (выглядящий как почта или произвольную строку) в платеже и его же сообщает имеющим доступ к платежной информации (потенциально даже без эквайринга какой-то автоматике: боту, форме, вотэва).

**Comment by lomalkin** [comment]
1 число месяца это просто, зачем усложнять? Аванс не у всех 5го.
У нас не та аудитория, которая живет от з/п до з/п, даже если я не прав, то такие скорее не будут ходить или будут делать это бесплатно, если на членство денег нет, а не тратить последнее на нас.

В остальном согласен с Олегом, но какую-то базу этих самых идентификаторов я бы все-таки предложил завести, чтобы можно было проставлять флаг оплаты. Плюс, что делать с платящими наличкой, если такие найдутся?

Если цель членства это получение денег на поддержку места, но по факту никак не проверять оплату (как сейчас), то нет никакого смысла в оплате членства, т.к. можно и так приходить.

Если его смысл только в регулярном донате от небезразличных - возможно они наоборот, хотят видеть себя на сайте в списке, типа "Люди, поддерживающие нас: @nickname, ..." - тогда надо базу вести.

Поставлю следующий вопрос: какова цель сбора средств в пользу опдаты членства? Какая мотивация у участников?

**Comment by heeeyflo** [comment]
@lomalkin я соглашусь насчёт того, что нет смысла отслеживать реккурентность платежей, но два момента таки бы обсудил:

> 1 число месяца это просто, зачем усложнять? Аванс не у всех 5го.
У нас не та аудитория, которая живет от з/п до з/п, даже если я не прав, то такие скорее не будут ходить или будут делать это бесплатно, если на членство денег нет, а не тратить последнее на нас.

Если мы рассматриваем членский взнос больше как именно донейшн, а не как подписку, то человеку гораздо проще будет сделать это именно после аванса. Насчёт того, что аванс не у всех пятого — окей, но я полагаю что это один из самых популярных вариантов. Мне кажется что никаких усложнений между первым и "условно шестым" числом нет, но это поможет нам увеличить шанс того, что этот донейшн вообще случится.

> Плюс, что делать с платящими наличкой, если такие найдутся?

Вроде бы, на встрече 12/3/19 кто-то высказал предложение о том, что наличка проходит через других участников, то есть просто так в коробке неучтенными остаются только донаты.

> Если цель членства это получение денег на поддержку места, но по факту никак не проверять оплату (как сейчас), то нет никакого смысла в оплате членства, т.к. можно и так приходить.

Насколько я понимаю, никто не ставит целью сверять людей по списку на входе, но, опять же, существование какого-то формализованного механизма скорее всего увеличит эту вероятность.

**Comment by theg4sh** [comment]
Пардон, что вмешиваюсь в дискуссию, не рассматривали что-нибудь типа https://ru.wikipedia.org/wiki/Patreon в качестве сервиса сборов за членство?

**Comment by sntxerror** [comment]
> Пардон, что вмешиваюсь в дискуссию, не рассматривали что-нибудь типа https://ru.wikipedia.org/wiki/Patreon в качестве сервиса сборов за членство?

Рассматривали, к сожалению там не все так просто с выводом плюс Patreon не резидент РФ, есть риски остаться через N времени без средств .

Самый прямой в итоге сценарий на наш взгляд это подключиться к Яндекс.Кассе. Более того, личный кабинет Кассы у меня уже есть, необходима только реализация сценариев платежа по API

**Comment by heeeyflo** [comment]
В конечном счёте определились что будет использоваться Яндекс.Касса и самозанятость. Эта issue более не актуальна, дальнейшее обсуждение автоматизации донатов, мембершипа и бухгалтерии в целом будет производится в рамках отдельного проекта.
