### ISSUE TITLE
посудомоечная машина

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#11]
Паттерны говорят нам: Invest in the single most important piece of hardware: a dishwasher!

**Comment by kaero** [comment]
Это для зажиточных крестьян. Нам бы за аренду заплатить и станок купить. Разве что пожертвует кто.

**Comment by kaero** [comment]
Еще можно устроить хакатон по построению посудомоечной машины.

**Comment by glitchcore** [comment]
Хакатон по мойке посуды

**Comment by kaero** [comment]
Issue не обозначает проблему и не содержит предложения решения. Не понятно, что тут обсуждать, в таком виде закрываю, можно вернуться и переоткрыть измениф формулировку, чтобы была возможна дискуссия или выполнение действия.
