### ISSUE TITLE
Завести страницу Контакты с картой, адресом, фотками и гайдом как найти

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#115]

**Comment by glitchcore** [comment]
В итоге кто PR делает? @z4fd вроде собирался?

**Comment by ValdikSS** [comment]
https://github.com/b4ck5p4c3/0x08.in/pull/116

**Comment by kaero** [comment]
Было закрыто указанным PR без отдельной страницы, но в остальном ешение удовлетворяет условию.

**Comment by glitchcore** [comment]
Я считаю, что нужна отдельная страница — мне не нравится картинка на глагне и хочется скидывать инфу отдельной ссылкой нуждающимся.
Вроде @z4fd хотел заняться этим

**Comment by kaero** [comment]
> Я считаю, что нужна отдельная страница — мне не нравится картинка на глагне и хочется скидывать инфу отдельной ссылкой нуждающимся.
> Вроде @z4fd хотел заняться этим

Чем для этого плохи карточки организации в Картах и 2ГИС?

- https://yandex.ru/profile/29206101690
- https://yandex.ru/maps/org/bekspeys/29206101690
- https://2gis.ru/spb/firm/70000001039989605

Вместо картинки я бы вставил фрейм Карт: он интерактивный, Карты приняли указание входа, можно включить Навик, фото входа там тоже есть в карточке. Вот код фрейма:

```
<iframe src="https://yandex.ru/map-widget/v1/?z=12&ol=biz&oid=29206101690" width="560" height="400" frameborder="0"></iframe>
```

**Comment by glitchcore** [comment]
> Чем для этого плохи карточки организации в Картах и 2ГИС?

Ничем, не считаю, что их наличие должно отменять страницу «контакты» на сайте, это довольно общепринятая практика.

**Comment by glitchcore** [comment]
> Вместо картинки я бы вставил фрейм Карт

предлагаю вставить и картинку с отмеченной точкой, и фрейм и ссылку на карту (например, для навигатора)
