### ISSUE TITLE
Душевая кабина

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#12]
Еще один хороший паттерн, стоит подумать об этом.

**Comment by kaero** [comment]
Начать стоит с солгасования возможности установки с арендодателем.

**Comment by kaero** [comment]
Issue не обозначает проблему и не содержит предложения решения. Не понятно, что тут обсуждать, в таком виде закрываю, можно вернуться и переоткрыть измениф формулировку, чтобы была возможна дискуссия или выполнение действия.
