### ISSUE TITLE
Ежемесечная встреча фаундеров

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#123]
Предлагаю проводить ежемесячную встречу фаундеров для обсуждения вопросов организации хакспейса.

На такой встрече можно будет обсудить финансы, роадмап, следование ему и в целом провести ретроспективный healthcheck.

Проводить предлагаю в конце каждого месяца после 25 числа.

**Comment by glitchcore** [comment]
Готов согласиться. Жду PR.

**Comment by sntxerror** [comment]
Зачем PR? Может просто добавим встречу в календарь?

**Comment by glitchcore** [comment]
Думал, как зафиксировать.
Наверное, можно и так.
Какой день?

>

**Comment by sntxerror** [comment]
Предлагаю каждый последний понедельник месяца, чтобы было до оплаты всех счетов и не пересекалось с другими встречами.

**Comment by kitnerboy** [comment]
По опыту бывают горячие встречи, а бывают вполне без задач.
Сейчас мы сделаем более редкие встречи, в итоге будет накапливаться гора вопросов, которые сведут с ума участников.
Может проводить встречи "еженедельно". То есть в те недели, когда в стеке задач для встречи (который надо наполнять не в понедельник по-хорошему) есть достаточное количество этих самых задач?
С другой стороны планировать такое нереально.

**Comment by sntxerror** [comment]
Ты вероятно не совсем понял мысль, идея встречаться раз в месяц не всем, а фаундерам или организаторам, как назшовешь.

Еженедельные встречи никуда не денутся.

**Comment by glitchcore** [comment]
Добавил встречу в 20:00 каждый последний понедельник месяца
