### ISSUE TITLE
Собрать и установить стеллажи в зале

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#125]
Необходимо собрать стеллажи и установить их зеркально в конфигурации 1000мм-700мм-экран-700мм-1000мм, если считать от входа. 

При установке необходимо предусмотреть крепление к стене (короткий дюбель в гипрок/длинный дюбель в кирпичную стену под гипроком).

**Comment by glitchcore** [comment]
Установили
