### ISSUE TITLE
Установить трекеры Google Analytics и Яндекс.Метрики на сайт

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#128]
Нужно трекать посещаемость, проблемы сайта и другие полезные штуки. В качестве opt-out не включаем трекеры при включенном в браузере DNT. В случае отключенного JS безусловно отключаем трекеры.

todo @kaero: приложить коды трекеров

**Comment by kaero** [comment]
Вопрос установки трекеров сам по себе довольно спорный и холиварный. Предлагаю поставить задачу на паузу на день-другой, чтобы желающие могли высказать мнение.

Мое мнение такое: если нас волнует "находимость" сайта из поисковых систем, и проблемы пользователей на сайте, и какая-то аналитика, то стоит использовать трекеры.

Опции:
1. самописная аналитика по логам
2. self-hosted аналитика
3. аналитика поисковых систем

Пункты 1 и 2 потребуют хосттить сайт самим, чтобы иметь возможность парсить логи.

Пункт 1 я бы вообще выкинул сразу из рассмотрения, если только у нас нет квалифицированного энтузиаста, желающего потренироваться в этой задаче.

Пункт 2 против 3 ограничен в возможностях аналитики относительно поисковой системы, трекинга и таргетинга нашей же рекламы.

**Comment by NetBUG** [comment]
Я хочу, чтобы сайт находился, и чтобы трекеров не было.
А ещё чтобы на сайте не было видимой пользователям рекламы, но он приносить $1000 в месяц хакспейсу!

**Comment by kaero** [comment]
Я про рекламу сайта спейса, а не рекламу на сайте.

**Comment by heeeyflo** [comment]
> Я хочу, чтобы сайт находился, и чтобы трекеров не было.

@NetBUG так поэтому мы и форсированно респектим Do Not Track:
1. Если JS выключен, то скрипт проверки и подгрузки аналитики просто не выполнится.
2. Если JS включён, и DNT активен, то скрипт чекнет это и не будет ничего подгружать
3. Если JS включён, DNT выключен, но стоит Privacy Badger и ему подобные штуки — они вырежут аналитику.
4. И только если включён JS, отключён DNT и не стоит никаких privacy экстеншенов — мы подгружаем аналитику.

То есть, нужно прям очень постараться быть затреканным, чтобы это случилось. Мне кажется что вообще идея on premise аналитики здесь ничего не меняет — мы так же трекаем пользователей, собирая больше данных, чем они, вероятно, хотели бы раскрывать.

Если всё же нам нужны трекеры, то альтернатива DNT только одна — спрашивать согласие напрямую, модалкой или каким-нибудь bottom pinned элементом, подобно тому как сейчас спрашивают согласие на использование cookies.

**Comment by z4fd** [comment]
> спрашивать согласие напрямую, модалкой или каким-нибудь bottom pinned элементом, подобно тому как сейчас спрашивают согласие на использование cookies.

Oh, shi~ Давайте только вот только без этого, самая бесполезная и дико раздражающая вещь в современно вебе.

И да, я честно говоря не вижу дикой потребности в аналитики, трекерах и п.р. Но мне вобщем-то фиолетово если кто-то хочет этим заниматься :)

**Comment by heeeyflo** [comment]
> Oh, shi~ Давайте только вот только без этого, самая бесполезная и дико раздражающая вещь в современно вебе.

Да, я того же мнения, поэтому предалагаю вариант в котором вообще не требуется участия пользователя. В качестве альтернативы, можно при эмбеде трекеров в футере показывать текст вроде "Мы подключили аналитику, так как вы не активировали функцию Do Not Track. Нажмите **сюда** если хотите чтобы мы перестали так делать." и по клику на "сюда" проставлять флаг в локалсторадже/куках, то есть такой дублирующий opt-out.

**Comment by kaero** [comment]
> И да, я честно говоря не вижу дикой потребности в аналитики, трекерах и п.р. Но мне вобщем-то фиолетово если кто-то хочет этим заниматься :)

Просто не ты заплатил за рекламу :)

Если серьезно, то трекеры и аналитика нужны, чтобы можно было понять что не так с нашим сайтом, почему его нифига не найти или почему люди не идут дальше одной страницы, чтобы аккуратнее настраивать рекламку и меньше тратить на нее денег, чтобы понимать почему наш сайт не найти, иметь какие-то данные для оценки его качества (если никто не ходит на страницу со списком мероприятий, то может она и не нужна?)

**Comment by glitchcore** [comment]
Пинг, ребята, к чему пришли, кто делает?

**Comment by kaero** [comment]
Ни к чему не пришли, на встрече было 3 участника, представляющие только позиций "за" и "похуй". Решили, что кворума нет.
