### ISSUE TITLE
Получение разрешения людей на публикацию фото и видео, включающих их различимые лица

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#13]
Законодательно в России предусмотрен только opt-out: если к нам обратились или постановил суд, то мы должны прекратить публикацию материала.

При этом в чате прозвучало мнение, что неплохо бы брать разрешение у людей до публикации. 

Я сам тоже склоняюсь к этой позиции.

**Comment by glitchcore** [comment]
Можно выкладывать временно доступно только для участников события в течение 1-2 дней, если за это время никто не предъявит, то публиковать.
Как это сделать технически — вопрос

**Comment by z4fd** [comment]
На Chaos Communication Camp это решается просто

**Ask everybody in the picture if they agree to be photographed or filmed.**

It follows that shots from the stage into the audience and long shots in the hackcenters, villages and the other public areas are not possible! Please note that we might ask photographers and film teams to leave, if they don't behave accordingly.

Других вариантов, кроме явного согласия я не вижу

**Comment by glitchcore** [comment]
> **Ask everybody in the picture if they agree to be photographed or filmed.**

> Других вариантов, кроме явного согласия я не вижу

Надо это автоматизировать — распознавать лица на фотке и рассылать всем автоматом запросы)

**Comment by glitchcore** [comment]
Пришли к тому, что
1. По-умолчанию все выкладывается, об этом есть уведомление;
2. Для трансляции можно сделать на стене выключатель трансляции, если кому-то не ок публиковать то, что происходит — может выключить
3. Для мероприятий та же фигня, если кому-то не ок, он может предупредить и мы его не будем фотать/замажем

**Comment by kaero** [comment]
/a

но закрыть только при помощи PR с добавлением соответствующих правил в вики

**Comment by glitchcore** [comment]
Создам PR позже.

**Comment by heeeyflo** [comment]
Протокол встречи от 11/26/2019.

1. Все мерояприятия публичны by default, пока не указано обратное.

2. При подготовке к мероприятию, необходимо определить разрешена ли съемка, это аннонсируется перед началом события.

3. Необходимо ввести общее правило — при желании сфотографировать кого-то, необходимо получить явное разрешение всех людей на этой фотографии.
