### ISSUE TITLE
Покупка 3D-принтера

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#131]
Предлагаю обсудить приобретение принтера [TL-D3 Pro](https://wholesaler.alibaba.com/product-detail/DHL-Free-Shipping-TL-D3-Pro_62199060254.html?tracelog=null)

Стоимость порядка 30-35к.

**Comment by sntxerror** [comment]
Я уже высказывал своё одобрение голосом) все также!

/a

**Comment by kaero** [comment]
Я за 3D принтер, но хочу развернутого обоснования выбора

**Comment by sntxerror** [comment]
У меня есть вопрос, мы уверены что при доставке его не остановят на таможне суетом новых таможенных лимитов в 200€ на посылку? Потребуется оплатить пошлину судя по всему. Это по последним данным 15% с посылки

**Comment by kaero** [comment]
> У меня есть вопрос, мы уверены что при доставке его не остановят на таможне суетом новых таможенных лимитов в 200€ на посылку? 

Остановят, если на посылке будет указано, что это продажа из магазина, и указана стоимость превышающая лимит. В уплате пошлины нет ничего сложного.

btw, китайцы часто не указывают, что это продажа, или указывают заниженную стоимость. Можно об этом явно договориться с продавцом и указать на отправлении заниженную, но похожую на реальную стоимость, например, $150.

> Потребуется оплатить пошлину судя по всему. Это по последним данным 15% с посылки

Пошлина уплачивается с превышения лимита, а не всей стоимости.

**Comment by Nemessor** [comment]
> Я за 3D принтер, но хочу развернутого обоснования выбора

Хм, у этого принтера есть, как минусы, так и плюсы. 
С одной стороны в Хакспейс хватило бы и одноэкструдерного принтера, но люди тут разные и запросы также всяческие и разносторонние. Т.к. место общественное, то делать вытяжку и создавать место для печати едкими пластиками, типа ABS , попросту неактуально. 
Поэтому выбор пластиков не велик -то пластики с небольшой усадкой и с неприхотливыми свойствами : PLA, PETG , TPU, PVA и композитные смеси . Но этого должно хватить под многие задачи. Корпуса и тем более. 

Поэтому нужда в принтере с закрытой камерой отпадает. И выбору представляются всевозможные дрыгостолы всяческой конфигурации. 

Для выбора всегда есть всевозможные одноэкструдерные варианты , такие как CR-10S , Tevo Tornado, Tevo Flash и прочие роликовые дрыги. 

Но что если посмотреть в сторону двухэкструдерный принтеров ? То тут все не очень вкусно, недорогие двухэкструдерные принтеры это концентрация боли и страданий. 
Wanhao 4s и все двухэкструдерные копии 2ого Мецкербот Репликатор ,это боль и стралания, как и другие компоновки принтеров с соплами на одном уровне и на одной печатной голове. Какова причина лютой боли при использовании данных аппаратов ? Выровнять сопла в уровень никогда не выйдет, и чем меньше слой, тем сильнее эта разница заметна, к тому же принтер при печати будет всегда норовиьтся сбить то, что напечатано другим соплом. 
Это повышает шанс фейла печати и значительно повышает окружающую температуру вокруг пятой точки печатающих. Поэтому, мое мнение - двухсопельные печатные головы (без качелтки) эт не бро. 

Второй вариант - это экструдер смешивания, где есть одно сопло и один термоблок. По факту тут вообще всё классно : никакого офсета с другим соплом, все четко и одинаково, ибо все пластики идут через одно сопло. Но есть косяк - печатать нужно одинаковыми по роду пластиками (PLA, но просто разные цвета) , а это не особо востребовано и интересно. А если печатать разными, то мы будем терять на каждом слое печати очень большое количество времени на смену пластика(пока охладится под один, пока нагреется под другой), а ещё не всё пластики любят смешиваться, в итоге порой там образуется лютый композит, который забивает все к чертям . 
Поэтому экструдер смешивания , хоть он и меньше мороки даёт, но явно не наш вариант . 


И вот, приближаемся к сути - полунезависимые экструдеры, такой довольно активно развивающийся тренд в области 3д печати. Как раз тот компромис , который даёт нам не только решение ряда проблем, но и даже очень прикольные преимущества. 

Плюсы: 
1) Возможно задать Z офсет для каждого экструдера независимо , что позволяет нам программно выровнять сопла в уровень, если будем печатать двумя материалами. 
2) Независимый контроль температур для каждого материала.
3) Более лёгкая печатная голова , чем в случае с двумя хотендами на одной ПГ. 
4) В данном принтере ПГ с директ подачей - а это значит стабильность подачи на любых скоростях . 
5) Директ подача это также всеядность и минимальные проблемы при печати гибкими пластиками
6) В принципе довольно удачная механика для Dual semi-independent extruder'ов . Лучше только за очень дорого (если интересно, в феврале можем презентовать наш проект с такой компоновкой)

7) Все аккуратно скомпановано и выглядит , как законченный продукт.  За демократичную цену

_____________
Ну теперь немного о минусах:
1) Да, это большая дрыга, поэтому скорости печати хорошего качества эт до 80-90мм/с . 150-200мм/с эт не этот бюджет даже, да и там нужен более менее профессионал печати, чтобы хорошо подбирать параметры. 

2) Рельса только на одной оси. Заменить ролики на рельсы потом можно, Но ролики по V рельсам у меня работают также без проблем, на CR-10 оно живут у меня 2 года, более 2500 машинных часов, и все с ними в порядке. 

3) Цена, наверное. Все же не самая дешёвая дрыга, но скорее одна из самых дешёвых двухэкструдерных. 

4) Несинхррнизированные оси Z, могут добавить проблем, но если они возникнут, то это решаемо, но в принципе проблемы не так часто. Да и со временем учишься их решать на автомате.

**Comment by Nemessor** [comment]
> Пошлина уплачивается с превышения лимита, а не всей стоимости

К тому же это будет ввозиться, как SAMPLE ,скорее всего , т.е. как тестовый образец   и китайцы Уде сразу предложили указать 50-100$, как объявленную ценность . Это я решу

**Comment by kitnerboy** [comment]
Двухголовые принтеры - это ИМБА, которая не даёт ничего кроме плюсов относительно одноголового варианта?
К чему я: по идее инструмент надо бы брать под задачи, но в случае со спейсом мы не можем знать задач. Получается, инструмент должен быть в определённых рамках универсальный. Двухголовый принтер даёт такое преимущество?
Просто безапеляционно обсуждается необходимость именно двухголового без обоснования. Не то чтобы я знал, как правильно, я как раз хотел бы выяснить, раз есть знающий человек.

**Comment by NetBUG** [comment]
Скажем так
Двухэкструдерные без защёлки дают больше минусов, чем плюсов в итоге.
Двухголовый вроде минусов давать не должен, если вторую не использовать. Заодно можно поставить два разных сопла и не крутить их ключом каждый раз.
По факту вангую, что две головы будут использоваться ~5% от общего времени работы, но по очереди - если в них разные сопла стоят — могут сэкономить кучу времени (~10 минут на запуск).

**Comment by kitnerboy** [comment]
Можно ли при количестве одинаковых деталей больше одной параллелить их печать в ущерб максимальному рабочему полю само собой?
Для меня это было бы плюсом, а разноцветная печать - это уже лакшери какой-то.

**Comment by NetBUG** [comment]
Да, это один из вариантов использования двух голов — печатать две одинаковые небольшие детали

Разноцветная по факту фигня и нужна всяким дизайнерам, а вот два разных сопла — весьма заметный плюс

**Comment by Nemessor** [comment]
> Двухголовые принтеры - это ИМБА, которая не даёт ничего кроме плюсов относительно одноголового варианта?
> К чему я: по идее инструмент надо бы брать под задачи, но в случае со спейсом мы не можем знать задач. Получается, инструмент должен быть в определённых рамках универсальный. Двухголовый принтер даёт такое преимущество?
> Просто безапеляционно обсуждается необходимость именно двухголового без обоснования. Не то чтобы я знал, как правильно, я как раз хотел бы выяснить, раз есть знающий человек.

Раз мы как раз заговориои про универсальность, то это как раз тот вариант, который универсален настолько,насколько позволяет бюджет. 
Остальное уже решает ваше воображение. 

Двухголовость позволяет печатать детали сложной геометрии с растворяемой поддержкой (PVA, HIPS).
Также можно печатать зеркальные и одинаковые детали одновременно, особенно полезно, когда этих деталей много или допустим зеркальные комплекты запчастей . 

Можно взять и одноголовый и печатать поддержки из того же материала и механически их удалять . Это также возможно. 

Но задачи именно неизвестны, и поэтому даётся возможность максимальной гибкости и универсальности , которую даёт как раз использование разных материалов.

**Comment by Nemessor** [comment]
К тому же можно использовать комбинирование разных сопел в одном изделии, для уменьшения времени печати: 
Печатать внутренние структуры одним диаметром большего размера, а внешнюю оболочку меньшим слоем и меньшим диаметром сопла.

**Comment by NetBUG** [comment]
А вот про последнее расскажи плиз, как это слайсером делается

**Comment by Nemessor** [comment]
> А вот про последнее расскажи плиз, как это слайсером делается

В той же Cura, можно выбрать экструдер для определенных структур, в том числе например печатать оболочку одним материалом, а внутреннюю структуру другим. 
Также можно использовать слайсер Aura для этого , а после будет возможность в Triangulatica

**Comment by glitchcore** [comment]
Насколько я понимаю, ни у кого нет возражений, принимаем положительное решение о покупке принтера
