### ISSUE TITLE
Новогодний пост

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#133]
Предлагаю отредактировать текст поста и опубликовать:

===

**ВСЕХСН4СТУП4ЮЩИМ!**
Наверняка все уже погружены в новогоднее безумие и мы не исключение. Пишем рассказать о наших планах на праздники:

* **31 декабря**, Вторник — регулярная встреча участников, сегодня не совсем обычная ;) Собираемся в 20:00, по традиции обсуждаем важные issues и готовимся к празднованию Нового года. Приглашаем всех участников встретить его вместе с нами!
* **1 января**, Среда, 00:00 — ночь открытых дверей. Приглашаем всех желающих с первых минут провести её вместе! В программе — любимые игры в локальной сети, веселье в VR, музыка, напитки и закуски. Safety first: пришедшим в защитных очках, каске и других средствах индивидуальной защиты дарим стикер! :) Наличие бодрствующих к утру не гарантировано, поэтму лучше приходите пораньше.
* **1 января** — как и всегда по средам, день открытых дверей с 19:00, приходите, будем рады!
* **3 января** в стенах нашего хакерспейса пройдет [встреча 2600](http://2600.spb.ru), приглашаем всех, кому интересны электронные устройства, компьютерная безопасность, влияние технологий на общество или просто изучение технологий. Начало в 19:00.

Призываем всех, кто придет на встречу участников и ночь открытых дверей, приносить с собой еду, некрепкий алкоголь. Желающим поиграть по сети пригодится компьютер и компьютерная мышь, берите с собой) Также не стоит забывать, что хакспейс живет и развивается силами его участников, так что ночью действует простое правило: поел-попил — убери за собой.

Наше большое желание уже сбылось, а главным итогом года стало открытие хакспейса. Мы желаем вам в эту новогоднюю ночь и в течение всего года не забывать, что вы excellent, заниматься тем, что вы любите, не мешая другим, улучшать мир вокруг себя, быть финансово независимыми и, конечно же, не умирать!

===

/post
/deadline 2019-12-31T16:20:00+3

**Comment by sntxerror** [comment]
**ВСЕХСН4СТУП4ЮЩИМ!**

Наверняка все уже погружены в новогоднее безумие и мы не исключение. Пишем рассказать о наших планах на праздники:

- **31 декабря** Вторник - день регулярнонй встречи участников. Собираемся в 20:00, по традиции обсуждаем важные issues и готовимся к празднованию новому года. Приглашаем всех участников встретить его вместе с нами!
- **1 января, 00:00** Среда, еженедельно — день открытых дверей. Приглашаем всех желающих с первых минут провести её вместе! В программе - любимые игры в локальной сети, веселье в VR, музыка, напитки и закуски. Safety first! Пришедшим в защитных очках, каске и других средствах защиты дарим стикер! :) Наличие бодрствующих к утру не гарантировано, поэтму лучше приходите пораньше.
- **3 января** Вечером в стенах нашего хакерспейса пройдет встреча 2600, приглашаем всех, кому интересна электронника, компьютеры, программирование, информационная безопасность и влияние технологий на общество. Начало в 19:00, подробности на 2600.spb.ru

Призываем всех, кто придет на встречу участников и на день открытых дверей, приносить с собой закуски, еду и некрепкий алкоголь. Желающим поиграть по сети пригодится компьютер и компьютерная мышь, берите с собой)

Наше большое желание уже сбылось, а главным итогом года стало открытие хакспейса. Мы желаем вам в эту новогоднюю ночь и в течение всего года не забывать что вы excellent, заниматься тем что вы любите, не мешая другим, улучшать мир вокруг себя, быть финансово независимыми и, конечно же, не умирать!
