### ISSUE TITLE
Купить оснастку для токарника

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#138]
## ~Резцы~

Во всехинструментах довольно большой выбор (https://spb.vseinstrumenti.ru/rashodnie_materialy/k_stankam/tokarnym/stameski_i_reztsy/nabory_rez/show_cat.php?formType=param&cat_id=5261&orderby=sales_rating&asc=DESC&bdc%5B226088%5D%5Bids%5D%5B29784%5D=on&bdc%5B226088%5D%5Bids%5D%5B29777%5D=on&bdc%5B226088%5D%5Btype%5D=check&bdc%5B226089%5D%5Bids%5D%5B29795%5D=on&bdc%5B226089%5D%5Bids%5D%5B29785%5D=on&bdc%5B226089%5D%5Btype%5D=check), но судя по отзывам можно попробовать взять эти https://spb.vseinstrumenti.ru/rashodnie-materialy/k-stankam/tokarnym/stameski-i-reztsy/nabory-rez/jet/11-sht-8x8-mm-59500022/ или эти https://spb.vseinstrumenti.ru/rashodnie_materialy/k_stankam/tokarnym/stameski_i_reztsy/nabory_rez/enkor/nabor_tokarnih_reztsov_po_metallu_iz_enkor_23362/#tab-Responses

Алсо можно прогуляться на уделку :)

У станка макс. ширина державки — 10×10 мм, высота режущей кромки (расстояние от базирующей плоскости резцедержателя до центра) — 10.65 мм.
При покупке проверить высоту режущей кромки (приложить резец на ровную поверхность и штангеном измерить от поверхности до самой дальней точки), в некоторых наборах в отзывах жаловались что кромка выше центра

## ~Патрон в заднюю бабку~

В бабке конус MT2 (он же КМ2)

## Всякое

* Центровочное сверло (2.5 мм, 2 шт)
* Индикатор?

**Comment by kaero** [comment]
Пак резцов и патрон будут 8го числа

**Comment by kaero** [comment]
Резцы и патрон подъехали
