### ISSUE TITLE
Анонимность обращения людей

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#14]
Периодически в кому-то в личку пишут всякие предложения, например, про фотик недавнее.
Хочется их как-то публично обсуждать эти предложения, но меня волнует вопрос конфиденциальности.

Возможно, стоит у предлагающего человека просто спрашивать согласие на публикацию его предложения.

**Comment by kaero** [comment]
Думаю, что стоит опубликовать правило и пайплайн для обращений. Все обращения, как и другую коммуникацию вести публично.

Я вижу всего два кейса для закрытой коммуникации:
1. необходимость передачи и фигурирование в коммуникации персональных, финансовых и других чувствительных данных
2. "abuse" -- возможность сообщить о неприемлемом поведении участника как другому участнику, так и внешнему человеку.

Делать коммуникацию закрытой, при том, что она все равно так или иначе отразится на том, что происходит в открытом в остальном спейсе на мой взгляд будет только вызывать вопросы у других участников.

**Comment by glitchcore** [comment]
> Думаю, что стоит опубликовать правило и пайплайн для обращений. Все обращения, как и другую коммуникацию вести публично.

Согласен. Сможешь добавить в вики?

> Я вижу всего два кейса для закрытой коммуникации:
> 
> 1. необходимость передачи и фигурирование в коммуникации персональных, финансовых и других чувствительных данных
> 2. "abuse" -- возможность сообщить о неприемлемом поведении участника как другому участнику, так и внешнему человеку.

Кажется, для такого в GH есть security issues, если нужно прям обсудить какой-то инцидент.

**Comment by sntxerror** [comment]
> пайплайн для обращений

https://github.com/b4ck5p4c3/wiki/issues/35

**Comment by glitchcore** [comment]
Переношу обсуждение в #35 (хотя мне не очень понятно, зачем еще одну ветку заводить)
