### ISSUE TITLE
Лицензии для проектов спейса

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#140]
Я даже не знаю с чего начать :) Предлагаю выбрать лицензию для коллективных проектов участников спейса в этой организации (проектов спейса), то есть не личных проектов.

Кажется, что нам могут потребоваться лицензии для:
- программного обеспечения
- проектов аппаратного обеспечения
- иных произведений в цифровой форме (фото, чертежи, текстовый контент, ...)

**Comment by kaero** [comment]
Лично я за максимально разрешающие лицензии, как вариант -- с четко прописанным отказом от гарантий и указанием авторства исходной работы.

**Comment by glitchcore** [comment]
Я считаю, что под каждый конкретный проект можно выбирать лицензию персонально, тем более что в ряде проектов могут возникнуть ограничения в связи с лицензиями используемых компонентов.
Мы можем сейчас выбрать лицензии на уже существующие проекты, в т.ч. этот сайт

**Comment by glitchcore** [comment]
Хочется прояснить/обсудить вопрос авторства: проекты хакспейса имеют личное авторство (группы участников) или это проекты авторства хакспейса как организации?

**Comment by kaero** [comment]
Авторство неотъемлемо у автора :) Внося изменения автор соглашается публиковать их под лицензией проекта. Проекты поевшие говна на спорах в суде имеют CLA обычно, где это прописано явно. В этом заключаются некоторые сложности с лицензиями: например, чтобы изменить лицензию всего проекта нужен апрув от всех авторов живого кода в нем, даже если от кого-то только скобка на одной строке осталась.

**Comment by kaero** [comment]
Я предлагаю по умолчанию для продуктов коллективного творчества участников во славу спейса (СКУД, сайт, ...) использовать пермисивные лицензии:

- Для ПО, где нет GPL-like включений: [MIT/X11](https://en.wikipedia.org/wiki/MIT_License)
- Для ПО, где есть GPL-like включения, для которых невозможна динамическая линковка, и не применимы иные исключения GPL, допускающие отличную от GPL лицензию производной или включающей работы: соответствующая GPL-like лицензия. Но по возможности избегать в пользу MIT/X11.
- Для чертежей, рисунков и прочих произведений, не являющихся исходным кодом программ, предлагаю [CC BY](https://creativecommons.org/licenses/by/4.0/).

/a

**Comment by glitchcore** [comment]
Полностью поддерживаю про MIT/CC BY

**Comment by glitchcore** [comment]
@kaero ты сделаешь PR?
