### ISSUE TITLE
Автоматизировать постинг информации о событиях 

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#142]
Чтобы писать о событии только в github, а автоматика уже делала посты в Телеграмм, Вконтакте и Твиттер.

Можно запилить GH Actions или вебхук с обработчиком в Облаке (в виде функции или в виртуалке) или на сервере спейса.

**Comment by kaero** [comment]
todo: поштырить готовые штуки

**Comment by heeeyflo** [comment]
В качестве source of truth для списка событий, предлагаю использовать страницы событий на сайте. Данная задача требует более тщательной проработки и завязана на завершение работ над новой версией сайта, которыми занимается @sntxerror 

По завершению работ над новой версией сайта, нужно сфорумлировать требования и дополнить текущую задачу (если публикация будет частью кодовой базы сайта), либо перенести эту задачу в репозиторий соответствующего сервиса и дополнить её уже там.
