### ISSUE TITLE
Регулярная встреча участников 2020-01-21

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#146]
[О встрече](https://0x08.in/participants#%D1%80%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%B0%D1%8F-%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B0)

## Объёмные вопросы
**Уровни участия:** на прошлой встрече подняли очень сложную тему с уровнями мембершипа, мы вроде как устаканились в тот раз на трёх уровнях (гостевой, первый и второй), но встряли на вопросе с переходом участников с первого на второй и теме голосования в частности. @kaero хотел призвать @mcheshkov на помощь с методологией голосования.

**Использование хакспейса для своих целей:** очень сложно сформулировать заголовок, но это то что мы тоже обсуждали в прошлый раз — насколько допустимо использовать хакспейс для того, чтобы, условно, придти и починить розетку / помыть платы / починить утюг. Кажется, на прошлой встрече мы так ни к чему и не пришли.

**Аполитичность хакспейса:** на прошлую встречу к нам приходила Маша из [Студии 4.413](https://www.instagram.com/studio_4413) с различными идеями для коллаборации (о которых лучше всего знает @z4fd), но суть не совсем в этом. Этот разговор поднял тему того, что понятие «политика» гораздо шире того смысла, в котором мы его применяем говоря о том, что _Бэкспейс вне политики_, и даже запланированный цикл митапов / лекций о раздельном сборе, это тоже своего рода политика. Эта тема немного обсуждалась в кулуарах, но её однозначно стоит вынести на полноценное обсуждение.

### Менее объёмные вопросы
На прошлой встрече мы совсем не коснулись вопросов из этого комментария https://github.com/b4ck5p4c3/0x08.in/issues/145#issuecomment-573782875, а ещё @z4fd хотел вынести на обсуждение какую-то тему, связанную с днём открытых дверей.

**Comment by NetBUG** [comment]
Также хотел обсудить фразу «если хочешь задонатить — донать окончательно», мне кажется, под проекты/задачи можно принимать оборудование на время от конкретных людей, на имя хакспейса или конкретных людей.

**Comment by kaero** [comment]
> на имя хакспейса 

Я не верю в коллективную ответственность, потому мне кажется, что такая форма займа вещей может создать проблемы.

> или конкретных людей

В этом случае это ничем не отличается от случая когда ты лично даешь человеку взаймы что-то, и хакспейс тут, кмк, вообще ни причем, кроме того, что человек может быть его участником.

> Использование хакспейса для своих целей ...  Кажется, на прошлой встрече мы так ни к чему и не пришли.

А мне казалось, что пришли к принципу _Вкладывай больше, чем потребляешь_, но у Леши были вопросы касательно соизмеримости вклада и потребления.

**Comment by kaero** [comment]
Предлагаю **обсудить СКУД, а точнее часть про привод замка**, и мое предложение из чата "купить готовую личинку с приводом". 

**И снова критически взглянуть на вопрос с доступом**: не знаю как у других участников и посетителей, но у меня от нашего режима работы немного пригорает. После отъезда @aanper открываю спейс, судя по календарю, только я. Я очень хочу решить вопрос с доступом для участников и не методом обязательства текущих 4х владельцев физических ключей к обеспечению какого-либо расписания. Возможно, например, выдать больше ключей текущим участникам. Больше участников с доступом -- чаще открыто.

Эта тема мне кажется наиболее важной, если ни у кого нет аргументов в пользу других тем, я предлагаю начать встречу с этой.

**Comment by kaero** [comment]
**Сокращение частоты регулярных встреч участников и дня открытых дверей в два раза.** Сейчас на оба мероприятия приходит мало участников и гостей, кажется лучше чуть более рационально тратить время и собираться реже, но более полным составом и выбирать темы, которые правда не удается обсудить онлайн, а не те, что даже не пробовали.

**Comment by sntxerror** [comment]
**Прием стаффа от @Brakhma**

**Comment by kaero** [comment]
Про СКУД, замок и частоту встреч решили следующее:
1. Димон посмотрит в магазе электромеханический замок по дешману -- это ускоряет внедрение механики в 1000%
2. Электроника выглядит минимально сходимой в неделю-две
3. Дни открытых дверей пока не сокращаем,смотрим стату: кто когда как проводит и сколько новых людей приходит
4. Проводим или нет встречу участников решаем сформировав повестку за день до и посчитавшись соберется ли кворум

**Comment by NetBUG** [comment]
По правилам приёма участников принято следующее решение.
На настоящий момент сложились два неформальных уровня участия, условно, «участник» и «ответственный участник». На статус влияет только взятая человеком и данная сообществом ответственность, резидентство и количество донатов не влияют.
Обсуждением в кругу 8 человек оффлайн придуманы «level 10» и «level 20». 

На данный момент это сообщество примерно соответствует членам «жёлтого» чата B34CKSP4CE.

Для изменения этого списка предлагается следующая процедура:
 - для добавления человека есть два пути:
 -- человек предлагает свою кандидатуру
 -- после согласования с кандидатом её предлагает любой текущий участник
При наличии явного либо неявного согласия **всех** участников группы level20 кандидатура принимается (что является упрощением формальной проверки ниже). При наличии разногласий предлагается голосование с принятием в расчёт достоинств человека по следующему списку:
* активность человека в течение хотя бы трёх недель перед выдвижением кандидатуры
* волонтёрская работа любого формата (от помощи при уборки до участия в разработке чего-то общественного)
* наличие публичного проекта, реализуемого с помощью спейса
* здесь были ещё три пункта

Число ответственных участников следует держать примерно на одном уровне, это не способ дать человеку привилегию, это способ решения задач спейса как дома для сообщества: наличие N ответственных людей, которые могут обслуживать пространство (открывать, проводить мероприятия единолично, назначать помощников). Они имеют доступ в спейс через СКУД и имеют права и обязанности по поддержанию пространства в живом состоянии.

**Comment by kaero** [comment]
https://github.com/b4ck5p4c3/0x08.in/pull/155
