### ISSUE TITLE
Индикатор открытости спейса для гостей

### ISSUE THREAD

**Issue by van2048** [b4ck5p4c3/0x08.in#149]
Предлагаю каким-ли образом автоматизировать получение информации о том, открыт ли в данный момент спейс. В идеале еще получать бы информацию о том до скольки спейс планируется быть открытым.

**Comment by van2048** [comment]
Мое предложение - написать бота для телеграмм, у которого есть 2 категории пользователей
- админы
- все остальные

Бот будет жить в чате с обсуждениями. 
Для всех доступна кнопка:
- спейс открыт?
Для админов дополнительно доступны кнопки:
- cпейс сейчас открыт
- cпейс сейчас закрыт
- cпейс откроется в `часы:минуты`
- cпейс закроется в `часы:минуты`

**Comment by a-andreyev** [comment]
на всякий случай продублирую здесь, что [есть календарь](https://calendar.google.com/calendar/embed?src=n0oev7vtqntpok3phdbb48cvu0%40group.calendar.google.com&ctz=Europe%2FMoscow&mode=WEEK)

**Comment by kaero** [comment]
Сейчас есть [календарь](https://calendar.google.com/calendar/embed?src=n0oev7vtqntpok3phdbb48cvu0%40group.calendar.google.com&ctz=Europe%2FMoscow).  Ссылка на него есть в описании чата, описании канала, он вставлен на станицу [События](https://0x08.in/events) сайта и [на главной есть ссылка на него](https://0x08.in/#хакспейс-открыт-но-не-каждый-день).

По крайней мере в окрестности часа он до сих пор был актуален. У всех участников имеющих ключи есть доступ на его редактирование, и им известно, что когда они в спейсе и готовы к посетителям, то нужно завести событие "Открыто". Чтобы немного упростить это действо мы в рамках автоматизации спейса заводим presense switch: он уже установлен рядом с автоматом включения контура розеток в электрическом щитке и подключен:

![image](https://user-images.githubusercontent.com/352609/72891184-bdc2d200-3d24-11ea-8bf4-2e909a5091fe.png)

В ближайшее время, я думаю, заведем софт. В дальнейшем планируем сделать его чуть более автоматическим.

/d

**Comment by glitchcore** [comment]
У меня была следующая идея:
1. Хакспейс переводится в состояние «открыто/включено» когда авторизованный участник прикладывает карту и после этого открывает дверь.
Открывается замок, включаются розетки, включается вывеска.

2. Хакспейс переводится в состояние «закрыто/выключено» когда авторизованный участник выходит, прикладывает карту и зажимает кнопку вызова.
Закрывается замок, выключаются розетки, выключается вывеска.

Это является заменой presence switch?

**Comment by kaero** [comment]
> Это является заменой presence switch?

Не совсем. Участник может прийти в спейс. Спейс фактически будет открыт, но это не отвечает на вопросы:
1. сколько он еще будет открыт
2. готов ли участник принимать посторонних людей или участников без возможности открыть/закрыть спейс

Presense switch как выделенная сущность решает как минимум вторую проблему. Для решения первой пока нет идей, которые бы выглядели лучше календаря. Например, есть мысль сделать кнопку, требующую нажатия раз в N минут, если следующие N минут спейс будет открыт.

**Comment by glitchcore** [comment]
Педаль внимания!

**Comment by heeeyflo** [comment]
@kaero за последние три недели что-то поменялось в отношении пресенс-свитча? Если что, то я могу перехватить у тебя эту задачу обратно, чтобы высвободить время на донейшн-бокс и систему учёта из #176.

**Comment by kaero** [comment]
@imcatwhocode не поменялось, подхватывай.

Дима установил пульт с переключателем и индикатором в портале, предполагалось, что переключателем можно преключать презенс, а индикатор горит в состоянии "спейс открыт", чтобы уходя напоминать о необходимости выключить его.

С тех пор @aanper предложил сделать переключение презенса авторизуемым и доступным только суперучастником. Можно использовать для этого либо бота и список телеграмм-акков, либо считыватель внутри спейса (который все равно нужен, чтобы удобно, не морозя жопу на улице, добавлять метки). Я поддерживаю его, но реализация как всегда на усмотрение делающего, любая реализация лучше отсутствующей :)

**Comment by glitchcore** [comment]
Да, у меня есть мнение что надо переключать состояния по авторизации.
Можно сделать кнопочный пост с кнопками с подсветкой и ридером:
* спейс выключен
* спейс включен
* спейс открыт
* режим мероприятия.

Можно взять RS2ALL и на его основе забахать контроллер.
