### ISSUE TITLE
Размещение постов в канале

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#15]
Рубрика «нам пишут»: 

> Здравствуйте, Андрей! Меня зовут ███████, я — комьюнити-менеджер компании ██████. ██ ноября мы проводим митап [ДАННЫЕ УДАЛЕНЫ] и хотим вас пригласить! Я подумала, что аудитории вашего чата тоже будет интересна эта информация, участие бесплатное, нужно только зарегистироваться. Скажите, пожалуйста, какие условия размещения информации у вас о нашем мероприятии? Спасибо!

**Comment by sntxerror** [comment]
Без удаленных данных решить невозможно.

**Comment by sntxerror** [comment]
В целом я против размытия контекстов постами не про место. Можно конечно предложить кроспост или провести ивент у нас.

**Comment by glitchcore** [comment]
> Без удаленных данных решить невозможно.

Да, я не совсем точно сформулировал вопрос.
Мне хотелось бы в целом понять политику в отношении подобных запросов, этот привел в качестве примера, поэтому не стал указывать конкретику. 

> В целом я против размытия контекстов постами не про место. Можно конечно предложить кроспост или провести ивент у нас.

Мне кажется:
1. постить в канал то, что совсем не имеет отношения к спейсу — не стоит даже в виде кросспоста.
2. В чат кросспост сделать можно, при условии, что аудитория второго чата нам интересна.
3. Проведение мероприятия у нас — за рамками этого обсуждения

**Comment by kaero** [comment]
Я против размещения любых материалов не о спейсе и событиях в нем в канале.

В чате — возможно, но признак «аудитория второго чата нам интересна» выглядит странным. Скорее считаем ли мы, что контент интересен аудитории нашего чата. В этом смысле чат ничем не отличается от доски объявлений, где участники могут размещать ссылки на интересные мероприятия не в спейсе, не вижу в этом ничего негативного для сообщества.

Возможно, стоит очертить только круг того, что можно или нельзя, например, «разрешены посты о бесплатных мероприятиях на темы науки, инженерного дела и искусства на сторонних площадках»

**Comment by glitchcore** [comment]
> признак «аудитория второго чата нам интересна» выглядит странным.

согласен, я не прав, ориентироваться нужно именно на то, что это нашей аудитории будет интересно.

**Comment by glitchcore** [comment]
Предлагаю перенести обсуждение в #28
