### ISSUE TITLE
Про правила или как важно быть последовательным

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#152]
Итак я подождал неделю и теперь кидаю на вентилятор. Считаю это прецедентом и этому нужно уделить внимание.

Для протокола, сейчас существует два типа обсуждений :
- На еженедельных встречах
- В гитхабе

Поправьте меня если я что-то перепутал. Если [упрощенно](https://0x08.in/issue-rules.html), то вне зависимости от типа обсуждения есть три шага принятия решения:
- Обсуждение
- 24 часовой таймер на гитхабе
- Принятие (при отсутствии обоснованных противоречий в течении 24 часов) и фиксация 
 
Так вот, руководствоваться решениями которые фактический небыли приняты и зафиксированы, мне видеться неправильным. Меня волнует два вопроса:

1. Почему так получилось ?
2. Как нам больше так не делать ?

**Comment by kaero** [comment]
> Так вот, руководствоваться решениями которые фактический небыли приняты и зафиксированы, мне видеться неправильным. 

+1 не могу не согласиться

> Почему так получилось ?

Ты в тикете не указываешь что именно "так получилось". Так не должно получаться.

> Как нам больше так не делать ?

Просто не делать, я даже не знаю что тут обсуждать, кроме как пошеймить участника, принявшего решения не в соответствии с правилами, а с личным мнением. Но это вроде тоже идет в разрез с нашими принципами, потому выход: собщить лично участнику о недопустимости принимать решения таким образом.

**Comment by glitchcore** [comment]
Мне кажется, все обсудили, согласен с Филом — «просто не делать»
/d
