### ISSUE TITLE
Регулярная встреча участников 2020-02-18

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#174]
0. Передать роль арендатора от  @kaero другому суперучастнику https://github.com/b4ck5p4c3/0x08.in/issues/182
1. Обсудить вопрос с каналом? (@z4fd)
2. Обсудить верстак, посмотреть на его чертежи, выполнить замеры на месте.
3. Посмотреть чо с дверью #163 
4. Обсудить инструменты автопостинга #142  
5. Очень важный вопрос #187

**Comment by glitchcore** [comment]
Пометить вещи согласно правилам размещения

**Comment by sntxerror** [comment]
- Вопрос подключения [виджета Кассы](https://kassa.yandex.ru/developers/payment-forms/widget) для рекурентных платежей
