### ISSUE TITLE
Структура сайта

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#175]
Мне кажется, пришло время рефакторить сайт.
Вчера @imcatwhocode говорил, что есть идеи сделать в стиле мануала, можешь озвучить?

Мои предложения
- Часть контента с /participants перенести в /evaluation, часть контента перенести в отдельный список страниц
- Сделать отдельные памятки с правилами для
  - гостя
  - участника
  - суперучастника/дежурного
  - организатора мероприятия (частично готово)

**Comment by heeeyflo** [comment]
Я немного прошёлся по текущему сайту и понял что до некоторых страниц можно добраться только в два хопа, через ссылку где-то посреди горы текста. Поэтому я решил что стоит сделать гораздо более плоскую структуру и выделить (пока) на сайте три типа больших группы страниц:
 - список эвентов и страница для каждого отдельного эвента
 - самодостаточные (?) страницы (вроде индекса, контактов)
 - Backspace 101

Последняя сущность как раз и призвана каталогизировать и упростить структуру всех страниц. В идеале, я хочу переписать сейчас всё и получить структуру в виде оглавления и отдельных страниц-глав покрывающих какую-то атомарную область. 

Например:
 - **Глава 1:** Что такое Бэкспейс
 - **Глава 2:** Принципы Бэкспейса
 - **Глава 3:** Участие и роли
 - **Глава 4:** Физическое пространство
 - **Глава 5:** Инфраструктура
 - **Глава 6:** Мероприятия и как их проводить
 - ...
 - **Глава 1337:** Этика биохакинга в Бэкспейсе

Ну и помимо этого, я разочаровался в навигации и читабельности текущего сайта, поэтому экспериментирую с лэйаутом и цветами, чтобы всё это было достаточно удобно организовано.

**Comment by glitchcore** [comment]
А ты уже делал что-нибудь? Мб создать work-in-progress PR?

**Comment by glitchcore** [comment]
Я немного вдохновился сайтом Нижегородского хакспейса https://cadrspace.ru/
Кажется на главной нужно

1. Примерно в 1.5-2 раза сократить вступительный текст
2. Написать список вариантов, как с нами взаимодействовать и поддержать (стать участником, приходить на мероприятия, приходить на open day, просто задонатить)
3. Принципы

**Comment by heeeyflo** [comment]
> А ты уже делал что-нибудь? Мб создать work-in-progress PR?

Пока ещё нет, я активно экспериментирую и ещё не дошёл до концепции, которая мне лично бы нравилась. Думаю что в ближайшее время приду к чему-то и тогда уже открою WIP PR.

**Comment by sntxerror** [comment]
@imcatwhocode твое видение глав очень резонирует с тем как я это вижу. Предлагаю только делить рефакторинг контента (текста, структуры страниц) и вижуала. Сейчас предлагаю сосредоточиться на контенте. Я начал со страницы из #187 и хочу продолжать.

**Comment by glitchcore** [comment]
Если у кого-то еще есть силы это делать, можно поднять вопрос. Мне кажется, стоит закрыть пока, есть другие задачи более насущные

/d
