### ISSUE TITLE
Проверка участником его статуса

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#176]
Какой-то механизм, который позволяет понять
1. Какой у участника баланс
2. Какой у него статус (У, СУ)

В дальнейшем, привязывать карты доступа, мб еще какие-то действия делать

**Comment by sntxerror** [comment]
Это можно сделать в бухгалтерской туле которую хотел делать Фил

**Comment by glitchcore** [comment]
@kaero обрати внимание, ты же и правда хотел что-то такое делать

Ну и тула, возможно, станет не только бухгалтерской)

**Comment by kaero** [comment]
да, все так, заассайнил на себя, сел писать код, ждите кучу говна на js

**Comment by kaero** [comment]
ну, и вся инфа есть в бухгалтерии, для СУ мы можем ее расшарить, кмк

**Comment by glitchcore** [comment]
Есть важное замечание по пресенс-свитчу: я считаю, что для смены статуса нужно выполнять авторизацию пользователя, чтобы только суперучастники могли менять состояние. Для этого предлагаю заменить переключатель на группу кнопок и добавить рядом RFID-reader

**Comment by kaero** [comment]
Думаю, что презенс можно вообще сделать ботом, и на панели на входе только статус показывать, чтобы бросалось в глаза при выходе и входе. А переключатель использовать для перевода замка в режим «держать дверь открытой».

**Comment by glitchcore** [comment]
Все обсуждение по пресенсу и аппаратной части — в #149

**Comment by sntxerror** [comment]
Будет решено в рамках #222
