### ISSUE TITLE
Принять @frogsandsocks в суперучастники

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#179]
Предлагаю принять Аню @frogsandsocks в суперучастники. 

Аня проявила себя, как человек разделяющий принципы и следующи правилам юэкспейса: помогала другим участникам на мероприятии и ДоД, заинтересована и участвовала в обсуждении и принятии решений в спейсе, хочет заниматься проектом спейса.

---

При принятии решения руководствуйтесь
 - https://github.com/b4ck5p4c3/0x08.in/blob/master/_pages/evaluation.md#суперучастники 
 - https://github.com/b4ck5p4c3/0x08.in/blob/master/_pages/principles_rules.md
 - https://github.com/b4ck5p4c3/0x08.in/blob/master/_pages/issue_rules.md

**Comment by glitchcore** [comment]
Насколько я знаю, ряд участников был против.
/d

**Comment by kaero** [comment]
> Насколько я знаю, ряд участников был против.

Думаю им стоит самим написать сюда об этом, вместе с предложениями, что человеку сделать, чтобы это исправить.

**Comment by glitchcore** [comment]
Насколько я вижу по голосованию, @elsidoi и @lomalkin были против — ребят, напишите, может ли измениться ваше решение, мб нужно предпринять какие-то действия. 
Либо же позиция принципиальна, но тогда мне важно услышать вашу аргументацию.

**Comment by kitnerboy** [comment]
Я заболел и торчу дома уже почти неделю, так что мои планы встретиться и познакомиться не сбудутся скоро.
К тому же я внял словам @kaero на тему того, что со всеми не перезнакомишься.
Мне хватит того, что за нее вполне осознанно заручились другие участники.
Я сменяю свою позицию на "воздержался".

**Comment by glitchcore** [comment]
Ок, я запускаю таймер, думаю, Лёша Ломалкин скажет свои возражения, если они у него будут
/a

**Comment by lomalkin** [comment]
Обсудили этот кейс и политику принятия участников с @aanper и @kaero, решили, что в ближайшее время будет предложено еще несколько хороших изменений в этот процесс.
/a

**Comment by glitchcore** [comment]
@frogsandsocks принята в суперучастники!
