### ISSUE TITLE
 По поводу стримов

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#18]
Я скорее против, т.к. они поощряют больше потреблять и мы вроде как все-таки больше про оффлайн. А вот смонтированные записи если они будут согласовываться с решением которое примем тут #13 я думаю будут полезны.

**Comment by glitchcore** [comment]
Я считаю, что нужно сделать средней всратости (ну, текущая камера в общем-то так и делает) трансляцию (постоянную, с возможностью отключения), а нормальные записи — да, монтировать и выкладывать

**Comment by kaero** [comment]
> против, т.к. они поощряют больше потреблять

Мне не очевидно каким образом, хочу развернутого объяснения по возможности :)

/a

**Comment by glitchcore** [comment]
Для меня это означает, что люди смотрят стримы и не приходят, появляется настроение «ну давайте, покажите что-нибудь еще» и не появляется участния».

**Comment by glitchcore** [comment]
В итоге, кажется, пришли к решению, что стримы не нужны, т.е. ничего делать не нужно: предлагаю закрывать
/d

**Comment by sntxerror** [comment]
Не согласен, стрим полезен когда частник не может присутствовать. 

Сейчас вы хотите не стримить исходя из того что альтернатива позволит кому то не приходить, даже если он может. И исходите из того что всем интересующимся обязательно нужно быть на ивенте лично. В чем цель этого? 

Мы ограничены пространством и ограничивакм регистрации для личного присутствия 40 людьми. Почему вы хотите ограничить возможность просмотра (участия) тем, для тех кто например не вместится?

/a

**Comment by glitchcore** [comment]
Честно говоря, у меня нет жесткой позиции по этому вопросу.
А еще в соседней задаче обсуждалось (#13) что мы делаем непрерывную трансляцию, но если кто-то из участников хочет чтобы он не попал в кадр, он может отключить её. Там вроде даже сошлись и надо только это в правила добавить.

Ну и технически мы сейчас не стримим скорее потому что ресурсов не хватает на это.

**Comment by glitchcore** [comment]
А вот записи докладов я бы начал делать, запись можно постмодерировать (например, замазывать тех, кто не дал согласия)

**Comment by kaero** [comment]
>  запись можно постмодерировать (например, замазывать тех, кто не дал согласия)

кто будет этим заниматься?

**Comment by kaero** [comment]
> А еще в соседней задаче обсуждалось (#13) что мы делаем непрерывную трансляцию, но если кто-то из участников хочет чтобы он не попал в кадр, он может отключить её. 

Я помню про трансляции что-то, что мы не будем их делать, чтобы люди приходили, и не поощрять потребительское отношение вроде "ну, что еще вы покажете"?

**Comment by heeeyflo** [comment]
Протокол встречи 11/26/2019.

1. Возможность и необходимость стрима и записи видео обсуждается отдельно для каждого мероприятия с докладчиками. 

2. Необходимо выработать ряд рекомендаций для докладчиков, в котором мы описываем ключевые моменты подготовки к мероприятию и риски, связанные с записью или трансляцией их докладов.

**Comment by kaero** [comment]
все в #101 эта ишью не имеет смысла
