### ISSUE TITLE
Выбрать суперучастника на роль арендатора

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#182]
Я более не хочу выполнять роль арендатора. Нужно выбрать нового арендатора из состава суперучастников, затем я организую встречу с представителем арендодателя для изменения договора аренды или закрытия текущего и заключения нового.

/deadline 2020-03-09T00:00:00

**Comment by sntxerror** [comment]
Я готов переоформить договор на себя.

**Comment by kaero** [comment]
Ок, я завтра созвонюсь с арендодателем, постараюсь договориться на встречу в спейсе во вторник или среду вечером.

**Comment by glitchcore** [comment]
Вопрос сможет дожить до конца вторника? Я хочу поднять его на встрече участников.

**Comment by kaero** [comment]
Да, я своей стороны хочу только чтобы его решили до следующей оплаты аренды. Желательно не в последний день, чтобы было несколько дней для маневров в планировании встречи.

**Comment by sntxerror** [comment]
Круто будет встретиться с Ольгой вне наших ивентов. В пятницу например или в понедельник.

**Comment by kaero** [comment]
> Круто будет встретиться с Ольгой вне наших ивентов. В пятницу например или в понедельник.

Я постараюсь это сделать, если в календаре спейса мероприятия будут отмечаться. Например, в прошлые выходные у нас как будто ничего не было:

![Screenshot from 2020-02-17 16-59-50](https://user-images.githubusercontent.com/352609/74660418-275cc180-51a7-11ea-98bf-07b9bed7dd45.png)

У людей снаружи нет никакого способа получать эту информацию как-то иначе.

Но и в случае мероприятия не вижу, что страшного произошло бы.

**Comment by glitchcore** [comment]
Насколько я понимаю, никаких возражений и предложений нет, @sntxerror теперь занимает должность арендатора, теперь нужно договориться с Ольгой.

**Comment by kaero** [comment]
@sntxerror сообщи, пожалуйста, дни и время на следующей неделе, когда тебе будет удобно встретиться в спейсе для заключения или изменения договора аренды. Желательно варианта 2-3. Тебе потребуется паспорт РФ. Также, по моему опыту взаимодействия с арендодателем, не стоит рассчитывать на очень позднее время, скорее часов до 18 включительно.

**Comment by kaero** [comment]
@sntxerror ping

**Comment by sntxerror** [comment]
@kaero если встреча начнется и закончится до 19 часов, то мне одинаково неудобен любой день кроме понедельника :) 24 февраля - официальный выходной, он мне наиболее удобен и я бы мог встретиться даже днём. В остальные дни технически могу в любое время до 19, но придется брать отгул/удаленку, что в любом случае мне не удобно. 

Скажи, непосредственные деньги для оплаты аренды понадобятся в этот момент или нет?

**Comment by kaero** [comment]
Хорошо, я постараюсь договориться на 24 февраля или 19:00+ в любой другой день.

> Скажи, непосредственные деньги для оплаты аренды понадобятся в этот момент или нет?

Если собираешься сразу заплатить за следующий период аренды, то понадобятся, если нет, то нет. Не понял в чем суть вопроса %) 

Сейчас аренда оплачена. Ты мог это узнать из:
- записи в бухгалтерии;
- каталога с квитанциями банковских переводов в счет оплаты аренды.

Период оплаты с 9 по 8 число, соответственно за март нужно заплатить не позднее 8 марта. Оплата переводом на карту Сбербанка.

25 числа каждого месяца нужно отправить представителю арендодателя показания счетчиков расхода электроэнергии, горячей и холодной воды.

**Comment by sntxerror** [comment]
Не, 19+ на любой другой день не подойдет. Вне понедельника я смогу до 19, с
определенными неудобствами. В 19 зачастую уже у нас ивенты.

Итого, круче всего пн, но пойдет и любой день до 19 часов. В пятницу судя по календарю можно и после 19.

**Comment by kaero** [comment]
Договорились на понедельник, 24 февраля. Детали в почте у @sntxerror и @aanper так как содержат чужие контактные данные.
