### ISSUE TITLE
Удалить @kaero из участников

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#183]
Сделано
- передал права на каталоги и файлы в google drive на общий аккаунт
- передал управление организацией в Я.Картах на общий аккаунт
- удалил id своей карты из списка физического доступа
- отдал ключи от механических замков и ibutton @aanper 
- освободил место в резидентской
- удалил себя из команд в github
- удалил себя из команды в bitbucket
- выдал права управления доступа google calendar общему аккаунту, и отозвал у себя
- отозвали админские права в чате и канале

Нужно сделать кому-то из суперучастников
- удалить пользователя `kaero` на сервере: я удалил ключи для аутентификации с малины и сервера, но задогиненного пользователя тривиально не удалить `userdel`
- перевыпустить все креды из keepass keychain'а в bitbucket, я не собираюсь их использовать, но для порядка
- заменить номера телефонов в организациях в Я.Картах и 2GIS, сейчас номера из моей виртуальной АТС; можно удалить номера, но скорее всего организацию забанят при следующей же модерации так как отсутствует возможность верификации (нужен номер телефона, или данные юрлица, адрес котрого совпадает с адресом организации).
- не знаю кому передать организацию в 2GIS
- https://github.com/b4ck5p4c3/0x08.in/issues/182
- удалить в бухгалтерии, свой баланс завещаю @komplivit 
- и конечно же https://github.com/b4ck5p4c3/0x08.in/issues/186

**Comment by glitchcore** [comment]
Насколько я понимаю, мы не можем удалить тебя из участников, пока ты арендатор, не нарушив при этом целостности системы правил)

**Comment by kaero** [comment]
![](https://lparchive.org/Star-Ocean-The-Second-Story/Update%2037/19-PSOGL2_028.jpg)

**Comment by kaero** [comment]
Йо, а тут что-нибудь происходить будет? Мне, например, продолжают звонить. Еще я не могу знать сделали вы что-то по списку или нет, если в ишью ничего не записано.

**Comment by sntxerror** [comment]
@kaero нужны креды от директа/adwords, либо нужно перенести кампанию на другой акк

**Comment by sntxerror** [comment]
> не знаю кому передать организацию в 2GIS

что нужно для этого?

**Comment by sntxerror** [comment]
> в Я.Картах на общий аккаунт

это аккаунт google?

**Comment by sntxerror** [comment]
> Еще я не могу знать сделали вы что-то по списку или нет

Видимо пока issue открыто, задача остается актуальной, о движении по списку будем писать сюда.

**Comment by kaero** [comment]
> @kaero нужны креды от директа/adwords, либо нужно перенести кампанию на другой акк

Компании у меня на личном аккаунте. Кто угодно может завести новые, если желает этим заниматься. Сейчас в adwords уже закончилась — дорогая и неэффективная, в Директе ещё продолжается.

> что нужно для этого?

Аккаунт в 2GIS куда передать.

>> в Я.Картах на общий аккаунт

> это аккаунт google?

Нет, общий яндекс-акк спейса.

**Comment by glitchcore** [comment]
Насколько понимаю, все выполнено, можно закрывать?

**Comment by kaero** [comment]
- Телефоны на картах всех еще телефонные номера моей АТС с редиректом на мобильный @aanper 
- Организацию в 2GIS не передал, т.к. никто не сообщил аккаунт, которому передать
- Сменили ли пароли в кичейне не могу судить, т.к. удалил кичейн со своих устройств

**Comment by kaero** [comment]
1. Удалите телефоны из карточки организации везде, они не работают с 10 и 11 марта, и вскоре будут переиспользованы другими клиентами АТС.
2. Я зашел в браузер, где был залогинен в некоторые сервисы от общих акков бэкспейса, и увидел, что сессии живы, то есть креды никто не менял.
3. Органзиацию в 2GIS никто так и не забрал.

**Comment by kaero** [comment]
Еще мне постоянно приходят отбивки о падениях actions в https://github.com/b4ck5p4c3/wiki-testing, но у меня нет никакого способа отписаться только от них. Могу только отключить уведомления о всех падениях в GitHub Actions.

**Comment by z4fd** [comment]
- Отрубил экшены, чтоб не спамили
- Заовнил 2GIS :D

**Comment by kaero** [comment]
@z4fd Спосёбо!

Осталось заменить или удалить невалидные телефоны в Я.Картах. Там организация в https://yandex.ru/sprav  на общем аккаунте спейса (по крайней мере там я ее оставлял).

Ну, и креды перевыпустить, но это на ваше усмотрение.

**Comment by z4fd** [comment]
C Я.картами там казус, просто удалить телефоны нельзя их можно только поменять или удалить организацию, я об это несколько раз ребятам говорил, сегодня затыкаю на это счет =__=

**Comment by z4fd** [comment]
Обновил телефон на новый номер из #242, изменения на модерации

**Comment by glitchcore** [comment]
Bump
Можно завершить процесс?

**Comment by glitchcore** [comment]
@z4fd сообщил, что новый номер одобрен
