### ISSUE TITLE
Сжечь тумбочку Фила

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#186]
:fire: :fire: :fire: Наконец-то можно это сделать ;D

А то, что не горит, можно истереть в пыль!

**Comment by glitchcore** [comment]
Нужно назначить исполнителя

**Comment by glitchcore** [comment]
Однако, я считаю, что тумбочка нам пригодится.
/d

**Comment by sntxerror** [comment]
Шёл медведь по хакспейсу, видит – тумбочка Фила, сел в неё и сгорел.

**Comment by kaero** [comment]
Шёл Фил по спейсу, видит -- желтый чат. Зашел в него и сгорел.

**Comment by z4fd** [comment]
Я тут api github`a ковырял щас и чуть чаем не подавился когда мне в ответе прилетело это
