### ISSUE TITLE
Нужны кабели IEC C13 и IEC C7

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#19]
Уже горит от нехватки

**Comment by z4fd** [comment]
> Уже горит от нехватки

Парочку принесу

**Comment by glitchcore** [comment]
@z4fd принес вчера пару кабелей, можно еще пару штук и можно будет закрывать

**Comment by sntxerror** [comment]
нужны не только IEC C13 но и IEC C7

**Comment by glitchcore** [comment]
Запишу это когда буду делать вишлист

**Comment by glitchcore** [comment]
Создал #39

**Comment by kaero** [comment]
Принес один C7

**Comment by glitchcore** [comment]
Влил #39 закрываю задачу
