### ISSUE TITLE
Забирайте фотографии с Hardware village / embedded meetup 2019.11.30

### ISSUE THREAD

**Issue by vazhnov** [b4ck5p4c3/0x08.in#191]
Извините, что так долго — на тот момент, когда делал фотографии, у вас на сайте не было даже email. А потом как-то всё забылось.

Фотографии № 8770-8774 отдаю под CC0 1.0 или более новой.
Все остальные фотографии отдаю под CC-BY-SA 4.0 international или более новой.

Ссылка на скачивание: http://mirror74.boot-keys.org/2019-11/2019-11-30_Hackerspace.tgz
Объём 1.2ГБ, там jpeg+raw (cr2).
Да, без https, руки не дошли ещё :)

**Comment by sntxerror** [comment]
спасибо!

**Comment by glitchcore** [comment]
> Ссылка на скачивание: http://mirror74.boot-keys.org/2019-11/2019-11-30_Hackerspace.tgz

@vazhnov Мне потребовался доступ к файлу, но ссылка уже протухла. Можно ли перезалить?

**Comment by vazhnov** [comment]
@aanper , вас тут нету: https://github.com/orgs/b4ck5p4c3/people
Можете объяснить, как вы относитесь к этому проекту?

**Comment by glitchcore** [comment]
> @aanper , вас тут нету: https://github.com/orgs/b4ck5p4c3/people
> Можете объяснить, как вы относитесь к этому проекту?

Есть, был скрыт приватностью.

Я участник хакспейса, хотел добавить фотографии в отчет о мероприятии.

**Comment by vazhnov** [comment]
@aanper , файл перезалил, URL тот же, проверйяте :)

**Comment by glitchcore** [comment]
Да, спасибо, буду выкладывать!

**Comment by lomalkin** [comment]
404. Я тоже не успел скачать.
P.S. Алсо неплохо было бы организовать файлопомойку на ресурсах спейса, чтобы ссылка не протухала меньше чем за сутки.
