### ISSUE TITLE
Регулярная встреча участников 2020-02-25

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#192]
Предлагаю в силу последних событий сместить вектор обсуждения в сторону способов увеличения числа участников и резидентов, а вопросы формулировки правил отложить на более благоприятное время.

**Comment by kitnerboy** [comment]
Из методов повышения количества участников мне видится определение, кто целевая аудитория нашего места и привлечение именно их. А именно организация мероприятий с уклоном на интерес именно этой группы людей.
У нас есть 500+ людей в канале телеграма, это достаточно крупная аудитория, достаточно лояльная и интересующаяся. Нам нужно понять, почему эти лиды не конвертируются в клиентов/участников.
Предлагаю выложить в канал ссылку на анкету с минимальным но достаточным количеством вопросов, уточняющих, почему человек интересуется, но всё никак не соберётся с участием. 
У меня пока нет идей с привлечением резидентов, но я знаю, что интересующиеся были. Хотелось бы хотя бы обратную связь получить от них, если кто-то из текущих участников сможет достать их контакты.

Усиленное привлечение участников конечно может понизить качество аудитории, но мне видится, что плохой хакспейс лучше никакого.

**Comment by glitchcore** [comment]
1. У меня идея в том, что нужно выдавать информацию более таргетированно. Например да, понять, что нужно резидентам и как их привлечь
2. В целом нужно больше информации от нас, и по участию, и постить про жизнь спейса, чтобы люди понимали, что тут можно делать
3. Нужно проводить практические мероприятия, предлагать людям делать проекты. Как показывает опыт, есть конверсия людей оттуда.

**Comment by kitnerboy** [comment]
> В целом нужно больше информации от нас, и по участию, и постить про жизнь спейса, чтобы люди понимали, что тут можно делать

Рискну побыть капитаном, но хотелось бы учтонить, что инфы не по уровням участия, правилам приёма и прочим безусловно важным и не вполне прозрачно раскрытым сейчас вещам, а именно нарисовать для участника картину того, как он может участвовать, какие роли может выполнять.
Мы с @aanper в эти выходные много это обсуждали, и пришли также к выводу, что нужно реализовывать несложные проекты, типичные для многих хакспейсов. Вот прямо классика попсы с Hackaday. Главное - не жадничать и оставлять вакантные несложные роли для новичков вместо того, чтобы делать какие-то вещи самостоятельно, быстро и надёжно.
Из спейсовых проектов сейчас у нас есть donate box, над которым работаем Аня и я. Свой интерес по корпусу проявлял Сыч. Возможно, стоит разбить проект на составляющие и подумать над тем, как вывесить трекер задач по нему в открытый доступ, чтобы люди могли подключаться, чтобы была цель.

Также нужен специалист по SMM. Нужно вести соц. сетки, освещать события, клепать мемасы. Возможно, у нас уже есть люди в окружении, которым может быть это интересно, и нужно только кинуть клич. Это помимо вполне практичного результата - развитие соцсеток - создаст ощущение наличия движухи и покажет нашу потребность в помощи. Потому что снаружи может казаться, что мы сами со всем справляемся.

**Comment by algroznykh** [comment]
Не смог найти актуальной финансовой информации, по ссылке в https://0x08.in/participants информация только до декабря. Где можно найти?

**Comment by glitchcore** [comment]
У нас сломалась публиковалка финансов :(

**Comment by sntxerror** [comment]
По итогу встречи определили множество важных задач:
- Посчитать баланс денег спэйса @sntxerror 
- Собрать список участников, отсутствующих в желтом чате @sntxerror 
- Узнать про платежи Алисы и Саши (донат или участие)  @aanper
- Создать таблицу менторов и заполнить её (предлагаю все же завести это как постоянный тул, чтобы знать кто кого когда менторит) 
- Актуализировать состав желтого чата, проведя отсутствующих в нем участников по флоу принятия в участников (кого-то ускоренно, кого-то как обычно)
- Написать пост о балансе спэйса в желтый чат
- Создать план постов с приоритетами @sntxerror + ?
- Написать анкету-опросник для уточнения пожеланий целевой аудитории
- Продолжить рерайт страниц сайта @sntxerror + @imcatwhocode 
- Накидывать идеи по практическим занятиям в отдельное issue
- Создать план мероприятий с приоритетами
- Solder Buddies 2
- Завести проект DonateBox в github-projects и декомпозировать его на отдельные issue @sntxerror + @elsidoi + ?
- Сформулировать идею общественно полезных задач в виде issue/PR @sntxerror 
- Сформулировать идею явного выделения сущности полу-резидентов @sntxerror 
- Написать пост про новую страницу "Об участии" и заанонсить день открытых дверей @sntxerror 
- Сформулировать идею приемлемого для нас формата сотрудничества с брендами @sntxerror 
- починить публиковалку финансов

**Comment by z4fd** [comment]
> Сформулировать идею приемлемого для нас формата сотрудничества с брендами @sntxerror 

Она давно сформулирована, мы об этом тебе говорили https://0x08.in/partnership.html
