### ISSUE TITLE
Soldering Buddies #2

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#193]
Нужно подготовить ивент.
- понять даты
- состав участников
- ресурсов
- сделать пост
- провести ивент

Кто возьмется?

**Comment by errorcalc** [comment]
1. Могу помочь участникам в хакспейсе с пайкой и запуском, как в прошлый раз
2. Надо выбрать что паять

**Comment by kitnerboy** [comment]
Отличный, недорогой и доступный прямо сейчас для самовывоза вариант - наборы в Робошопе.
Отличные варианты:
https://roboshop.spb.ru/kits/DIY-kit-buzzer
https://roboshop.spb.ru/kits/DIY-ki-wave

Я хотел бы взять на себя вопрос организации и проведения. 
На этой неделе уже наверное не стоит торопиться проводить, можем не дособрать людей. Предлагаю назначить дату - следующий четверг 5-го марта. Я осознанно разношу с днём открытых дверей, потому что мы предположили, что события не особо совместимы - в процессе пайки сложно поболтать, а мероприятие в прошлый раз хорошо так затянулось.

Также я хотел узнать, насколько правильной будет мысль отдавать предпочтение людям, не являющимся участниками и тем более вообще впервые желающим к нам прийти. Или сделать по-старинке -  кто первый, того и тапки?

**Comment by errorcalc** [comment]
> https://roboshop.spb.ru/kits/DIY-kit-buzzer
> https://roboshop.spb.ru/kits/DIY-ki-wave  
 
Первый, бегущий огонь думаю более интересен, но он про смд, что может затруднить сборку, для впервые взявших паяльник.

**Comment by kitnerboy** [comment]
Для впервые взявших паяльник - без разницы на самом деле при типоразмере 1206 и 0805.

**Comment by glitchcore** [comment]
Вы с датой определились? Если в этот четверг, то пора сделать уже анонс (https://0x08.in/event-rules)

**Comment by rusdacent** [comment]
@elsidoi 

> сделать по-старинке - кто первый, того и тапки

Я за этот вариант.

**Comment by kitnerboy** [comment]
> @elsidoi
> 
> > сделать по-старинке - кто первый, того и тапки
> 
> Я за этот вариант.

В следующий раз так и сделаю.

**Comment by glitchcore** [comment]
Мероприятие закончено
