### ISSUE TITLE
Выработать правила обсуждения вопросов в issues/PR

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#2]

**Comment by glitchcore** [comment]
Вообще как это происходит в нормальных проектах всяких? Бинарным голосованием — если «за» больше чем «против»? В течение какого времени должно быть принято решение, чтобы не получилось, что кто-то вышел из туалета, а все без него решили?

**Comment by kaero** [comment]
Дизайн гайд по хакспейсам предлагает противоречащие друг-другу паттерны

> Use the weekly plenum for discussion. Don’t take votes — discuss until everyone agrees. For some problems this pattern is the best.
https://wiki.hackerspaces.org/The_Consensus_Pattern

Мне не нравится такой подход, это звучит как возможность неучастием саботировать любые работы или мероприятие. 

С другой стороны мы можем потребовать от участников принятия решений или хотя бы объективной (ой) мотивации отказа в какой-то разумный срок.

> Use the weekly plenum for discussion. Do take votes — the strongest minority wins over the weaker minorities. For some problems this pattern is the best. 
https://wiki.hackerspaces.org/The_Democracy_Pattern

С голосованиями, учетом воздержавшихся, весом голосов есть много разных интересных вопросов. Если закрываем по голосам, то нужно как минимум ответить на вопросы: Кто вообще имеет голос? Организаторы? Резиденты? Все участники? Означает ли это, что за стоимость месячного взноса можно влиять на решения в спейсе? А если я приведу 10 людей с улицы, заплачу за них взнос, то получу контрольную массу голосов?

**Comment by kaero** [comment]
У меня пока есть такое предложение: инициатор проблемы, задачи, обсуждения может сам принимать решение, когда достаточно обсуждать и пора остановиться на чем-то и действовать. 

Он должен помнить только о том, что останется ли он после этого решения участником хакспейса могут принимать решение другие участники хакспейса голосованием. 

Устройство этого голосования вызывает те же вопросы, что я описал выше в отношении демократического паттерна. Кроме того, есть возможность остракизма. Непонятно как дружить это все с юридической точки зрения в отношении юрлица, его учредителей и директора. Например, если они будут принимать неугодные другим участникам решения, то как их выгнать? Или у них неприкосновенность?

**Comment by glitchcore** [comment]
Предлагаю закрывать задачи только если в результате issue возникает артефакт (PR в вики или реальный результат выполнения), либо если автор issue соглашается с тем, что задача wontfix

**Comment by glitchcore** [comment]
> Дизайн гайд по хакспейсам предлагает противоречащие друг-другу паттерны

Там пачка паттернов контакта и, насколько я понял, авторы не говорят о том, что есть серебряная пуля, просто разные паттерны подходят в разных ситуациях.

**Comment by glitchcore** [comment]
Обсуждение ведется в #30

**Comment by glitchcore** [comment]
Влил PR, задачу закрываю
