### ISSUE TITLE
Перевод субтитров к  All Creatures Welcome

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#20]
Судя по тому как сделаны [арабские сабы](https://vimeo.com/345191474), исходники видео похоже были утеряны. Я предлагаю:
- Перевести сабы (notabenoid?)
- Добавить сабам фон, чтобы перекрыть существующие
- ...
- Запланировать и посмотреть всем вместе :)

https://sandratrostel.de/media/

**Comment by kitnerboy** [comment]
Notabenoid окуклился по инвайтам. 
Не проще ли в гите делать перевод, если найдётся больше одного человека?

**Comment by z4fd** [comment]
> Notabenoid окуклился по инвайтам.
> Не проще ли в гите делать перевод, если найдётся больше одного человека?

Как вариант, но вообще у @sntxerror есть инвайты. Найдутся, желающие были, мне сейчас чуть-чуть не до этого просто. Через пару дней кину нормальный клич в канал и чаты, для начала надо будет людей найти :)

**Comment by z4fd** [comment]
Достали русские сабы, пора планировать показ! :)
