### ISSUE TITLE
Написать анкету-опросник для уточнения пожеланий целевой аудитории

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#201]
Пока нужно только создать саму анкету, публиковать будем отдельным issue

**Comment by kitnerboy** [comment]
Набросаю пока вещи, которые мне кажутся важными.
- Откуда люди приходят. Хотя сейчас основной канал распространения инфы - телега, возможно, кто-то узнал от нас другим способом.
- На каких мероприятиях человек был, оправдали ли мероприятия его ожидания.
- Если человек ещё не участник, есть ли у него интерес к участию? Если да, то чего не хватает.
- Есть ли интерес к возможности иметь отдельное рабочее рабочее место в рамках бэкспейса? Чего не хватает?
- Какие мероприятия из проводимых наиболее интересны? Какие хотелось бы, чтобы проходили?
Мой набор вопросов неполный, и местами может быть излишним. Дополняйте и критикуйте.

По вопросам про интерес к участию у меня двоякое мнение насчёт анонимности опроса: анонимный опрос позволит стесняшкам ответить более близко к их ощущениям без боязни, что мы набросимся со всем пылом желания затащить их в спейс, а неанонимный очевидно позволит нам найти конкретно заинтересованных людей и работать с ними.

**Comment by sntxerror** [comment]
какой здесь статус? может быть оформить это на google forms с привязкой ответов к таблице?

**Comment by kitnerboy** [comment]
Так я и планировал, но всё руки не доходили.

**Comment by sntxerror** [comment]
@elsidoi тут как дел?

**Comment by glitchcore** [comment]
Предлагаю закрыть, контекст изменился в связи с особыми условиями содержания
/d
