### ISSUE TITLE
Идеи по воркшопам

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#202]
Делитесь вашими идеями для вокршопов, мастер-классов и других мероприятий где посетители могут в чем-либо практиковаться.

**Comment by heeeyflo** [comment]
Есть идея сделать местный [breathe.moscow](https://breathe.moscow) и так же проводить хакатоны по сборке датчиков, но для начала надо их достать и обкатать, а с текущими логистическими условиями это может быть не так-то и просто.

Можно сделать хакатон по сборке Stratum 1 NTP-серверов с GPS и Raspberry Pi, но мне не особо понятен формат, если честно.

Как-то продвигать дальше тему с крышей и dayofradio тусовкой (Дима говорил что вроде бы @darkk поставил туда мониторинг точности GNSS).

**Comment by darkk** [comment]
> мониторинг точности GNSS

Да, это проект galmon.eu, на крыше стоит [станция № 51](https://galmon.eu/observer.html?observer=51). Если точнее она три часа как лежит :-)

Я не то чтоб много интересных деталей знал об этом проекте, тем более не понимаю особо, как его обворкшопить.

**Comment by sntxerror** [comment]
- вокршоп AR/VR

**Comment by p-hash** [comment]
mesh-net workshop?
