### ISSUE TITLE
Идеи мероприятий

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#204]
Делитесь своими идеями сходок, митапов и любых дргуих событий, на которых посетителям будет интересно побывать.

Из старой таблички:

| Stack | Who | Timing | Details | State
| --- | --- | --- | --- | --- |
| LAN party | @z4fd | Февраль после CC | _ | |
| AR/VR intro | @sntxerror @groznykh  | конец марта |  | |
| Space² | хз кот | хз когда |  | |
| Nordic + Юрьева ночь |  | Апрель |  | |
| День радио |  | 7 Мая |  | |
| Nordic + Юрьева ночь |  | Апрель |  | |
| Охота на лис (esp8266) | @z4fd  | ??? |  | |
| CoreWars | @z4fd  | ??? |  | |

**Comment by sntxerror** [comment]
Из старой таблички:

| Stack | Who | Timing | Details | State
| --- | --- | --- | --- | --- |
| LAN party | @z4fd | Февраль после CC | _ | |
| AR/VR intro | @sntxerror | март? |  | |
| Space² | хз кот | хз когда |  | |
| Nordic + Юрьева ночь |  | Апрель |  | |

**Comment by kitnerboy** [comment]
На фоне паялки есть идея реализовать многодневный курс по созданию простого девайса с нуля на основе домашних технологий.
Травление платы, монтаж компонентов, написание простой прошивки (я вообще хотел бы попробовать реализовать что-то с использованием Blockly/Scratch, но тут надо будет прямо заморочиться).
На выходе какая-нибудь мигалка светодиодами или что-то такое.

**Comment by z4fd** [comment]
- Охота на лис (esp8266)
- CoreWars

**Comment by heeeyflo** [comment]
- Охота на ~лис~ упавший балун

**Comment by sntxerror** [comment]
Встречка по IPv6 @mike-lambert

**Comment by sntxerror** [comment]
@aanper нужны идеи как провести юрьеву ночь онлайн

**Comment by sntxerror** [comment]
И в целом идеи онлайн мероприятий приветствуются)

**Comment by sntxerror** [comment]
- постримить HL:Alyx 
- вокршоп по AR/VR

**Comment by heeeyflo** [comment]
Содержание маркерной доски на 3/10/20:
1. Инфраструктурный х.
2. WebVR/AR intro
3. День Радио
4. Soldering Buddies
5. Примитивные нейросети
6. 3D Printer (party?)
7. DSGN
8. Проба II

**Comment by p-hash** [comment]
mesh-net workshop?
