### ISSUE TITLE
Починить публиковалку финансов

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#206]

**Comment by sntxerror** [comment]
Как временное решение необходимо поддержать публикацию данных из приватной [новой таблицы ](https://docs.google.com/spreadsheets/d/1qEI_kRydZOoUk2sqILITtgGzLl8rzfjAbXt3pXNNn60/edit?usp=sharing)учета финансов в старую [публичную таблицу](https://docs.google.com/spreadsheets/d/1axxo8_JOMkHQfMpo-TbR6vLCXhowdyu8iZRUjZ59F04/edit#gid=0).

**Comment by sntxerror** [comment]
Кто готов загняться - пишите, выдам доступ

**Comment by sntxerror** [comment]
Нужно написать JS скрипт выгрузки данных из одной таблицы в другую.

**Comment by glitchcore** [comment]
Мне сегодня приснилась эта задача)
Давай я попробую на выходных сделать

**Comment by heeeyflo** [comment]
Задача является частью финансовой системы хакспейса и его бухгалтерии, поэтому должна быть дополнена и перенесена в репозиторий финансового сервиса когда до него дойдут руки.
