### ISSUE TITLE
Общественно полезные задачи

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#207]
Описание в процессе

**Comment by glitchcore** [comment]
Предлагаю еще раз подумать, о каких задачах идет речь, мне кажется это три типа задач:

1. Разобрать стафф в хакспейсе
2. Решение инфраструктурных проблем хакспейса
3. Починка вещей, которые есть в хакспейсе.

Мне кажется, задачу по разбору стаффа можно выполнять в рамках дня уборки.

Под остальные задачи, я считаю, лучше заводить отдельные issues, может выясниться, что «общественно полезных задач» не так уж и много.

Про починку девайсов — это вообще могут быть отдельные проекты.

/d
