### ISSUE TITLE
Вступление @mrrubel в участники

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#209]
Миша @mrrubel хочет стать участником!
Я смогу быть его ментором только до субботы, потом уеду, так что предлагаю кому-нибудь помочь в этом вопросе.

Миша, м.б. ты видеть кого-то конкретного на должности ментора?

Напоминаю, ментор — участник, который поможет освоиться в хакспейсе, кому смело можно задавть любые вопросы касательно жизни, спейса и вашей работы в нём.

Также напоминаю, что по основному сценарию для вступления в участники нужно посетить 2 встречи участников, они проходят по вторникам в 20:00

**Comment by sntxerror** [comment]
Могу быть ментором после @aanper

**Comment by heeeyflo** [comment]
Тоже могу быть ментором!

@MrRubel а чем ты интересуешься? @aanper сможешь подсказать?

**Comment by MrRubel** [comment]
Интересует пайка, в частности соединение геймбоя и мидиклавы, а так же любые музыкальные примочки и модульные синты. В идеале хочу собрать модульный синт на основе геймбоя и денди, и отправиться с ним в тур по миру (но это уже влажные мечты).

@imcatwhocode @sntxerror вы будете во вторник в бэкспейсе? Там можно будет договориться

**Comment by heeeyflo** [comment]
@MrRubel ай эм! Тогда, действительно, там и заобщаемся. В теме синтов я разбираюсь довольно так себе (намутил несложный VCO пару лет назад и MIDI-CV бридж, а потом забил), вероятно что с Лёней @sntxerror тебе будет интереснее :)

**Comment by ardenfian** [comment]
@aanper @sntxerror @imcatwhocode   возьмите тоже в участники. Был на hw village и синт пати. Решил здесь написать, кто есть кто не знаю пока.

Сам пилю потихоньку синт из Sega MD. Так что, @MrRubel  мб есть о чем поговорить ;)

**Comment by heeeyflo** [comment]
@Vepsian приходи завтра на встречу в 19:00!

**Comment by z4fd** [comment]
@Vepsian А почитай вот это https://0x08.in/evaluation и если желание все еще будет, напиши суда в ответ и я прямо сразу сделаю issue :) 

Ну и да, приходи завтра на встречу вечером

**Comment by ardenfian** [comment]
@z4fd ага, читал уже. Завтра приду
