### ISSUE TITLE
Выложить чертежи стола

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#21]
Столы от Нейрона (https://habr.com/ru/post/427959/), которые мы делали. Фил рисовал 3D-модель стола, хорошо бы ее выложить, одобрение от автора я получил.

**Comment by sntxerror** [comment]
@aanper О каком столе речь? Уточни в заголовке плиз.

**Comment by glitchcore** [comment]
Обновил описание

**Comment by NetBUG** [comment]
Я испугался и в https://github.com/b4ck5p4c3/universal-table чертежи тоже выложил (заодно поправил некоторую неевклидовость, которая ирл привела бы к проблемам).
Но тут поможет только @kaero

**Comment by kaero** [comment]
https://github.com/b4ck5p4c3/desktop/
