### ISSUE TITLE
Вступление Давида в участники

### ISSUE THREAD

**Issue by frogsandsocks** [b4ck5p4c3/0x08.in#210]
[Давид](tg://resolve?domain=DavRekhvi) хочет стать участником!
Из смежных интересов: синты, схемотехника, микроконтроллеры. (Со слов Давида)

Нужно определиться с ментором для нового кандидата.

**Comment by sntxerror** [comment]
Я смогу! :)

**Comment by glitchcore** [comment]
Привет! Как дела со вступлением?
/a
