### ISSUE TITLE
Вступление @Alisianyan в участники

### ISSUE THREAD

**Issue by frogsandsocks** [b4ck5p4c3/0x08.in#212]
Алиса хочет стать участником :)

Интересуется: 
администрирование Linux, администрирование Windows, hardware/электроника, Arduino, STM32

Нужен ментор для нового кандидата!

**Comment by heeeyflo** [comment]
Учитывая схожие интересы, могу быть ментором!

**Comment by glitchcore** [comment]
Привет! Как дела со вступлением?
/a

**Comment by sntxerror** [comment]
@imcatwhocode закрываем?

**Comment by heeeyflo** [comment]
> @imcatwhocode закрываем?

@sntxerror я видел Алису только на одной нашей встрече (и знаю что Алиса была ещё раз когда-то до этого), поэтому не могу однозначно высказать своего мнения. 

Предлагаю придать этот вопрос публичному обсуждению и решить по его итогам.
