### ISSUE TITLE
Регулярная встреча участников 2020-03-03

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#214]
- Сделать чеклист для менторов
- #206 
- #195 
- #163
- #92 
- #149

**Comment by heeeyflo** [comment]
- #190 
 - определиться окончательно с тем, кто кого менторит

**Comment by sntxerror** [comment]
- нужен ли кандидатам аккаунт на github?
- единый день оплаты взносов
- чего не хватает для резидентской
- как учитывать членские взносы сверх 1337
- хлам в переработку
- система выпуска и замены пропуска

**Comment by glitchcore** [comment]
> * нужен ли кандидатам аккаунт на github?

я всем кандидатам говорю о том, что аккаунт желателен, так как все обсуждения проходят на гитхабе. При этом никакой привязки, например, пропуска, к гитхабу нет, поэтому технически можно обходиться и без него

**Comment by glitchcore** [comment]
> * как учитывать членские взносы сверх 1337

считаю, что участник сам должен явно высказать, как распорядиться средствами — либо зачесть их на баланс для оплаты след. месяцев, либо списать как безвозмездный взнос

**Comment by glitchcore** [comment]
> * система выпуска и замены пропуска

кажется, сильно пересекается с единой системой авторизации в целом (#176)

**Comment by glitchcore** [comment]
> * единый день оплаты взносов

обуждалось в #106

**Comment by heeeyflo** [comment]
1. **Source of truth для людей** — МАЙОР-ИДП (@sntxerror, @imcatwhocode)
2. Разработка CRM для хакспейса (@sntxerror, @imcatwhocode, @mike-lambert) — ПРАПОРЩИК a.k.a КАПТЁР
3. Составить маршрут до приёмки и договориться по перевозке дичи в приёмку (@aanper)
4. Решить проблемы с огнетушителем (~сдать в приёмку~)
5. **ГОРИТ** — Пофиксить публиковалку финансов (@sntxerror, @imcatwhocode)
6. Найти аналоговый телефон для лэндлайна
