### ISSUE TITLE
Вступление Лёши в участники

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#215]
Лёша @a-andreyev хочет быть участником и я буду ментором :)

**Comment by a-andreyev** [comment]
Всё так! Для отчетности попробую написать, что мне сейчас близко:
- мобильные линуксы (mer/sailfish/postmarketos/etc)
- instant messaging (matrix.org)
- qt/qml
- iptv / video streaming
- наверняка что-то забыл
