### ISSUE TITLE
Платформа для приема взносов

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#22]
Нужно выбрать платформу для приема взносов.

Я предлагаю патреон как что-то, с чего можно очень быстро начать. Если появятся юридические проблемы — переедем. (тем более что в будущем стоит задуматься об оформлении юрлица и там новые какие-то варианты приема денег могут стать доступны/необходимы)

**Актуальный план выработанный в ходе обсуждения**: создать страницу с описанием наших тарифов, инструкциями для пользователей, ссылкй на ясоберу.

**Comment by glitchcore** [comment]
Обновил описание
/a

**Comment by sntxerror** [comment]
Есть абсолютно неясная ситуация с переездом. Я почти уверен, что краудфандинговые площадки и площадки по сбору средств булут заметно ограничены в РФ с 2020 гола. Информация из надежных и авторитетных источников.

**Comment by sntxerror** [comment]
Предлагаю интегрироваться с кассой. Способов интеграции не мало. В качестве юридического лица пока что использовать имеющиеся ЮЛ.

**Comment by sntxerror** [comment]
Я готов реализовать интеграцию на сайте.

**Comment by glitchcore** [comment]
А в чем неясность ситуации с переездом?
Про ограничение с 2020 я понял, но что мешает нам 2+ месяца работать на них?

Мне нравится твое желание реализовывать интеграцию, но мб потратить ресурсы на что-то другое?

**Comment by kaero** [comment]
> Мне нравится твое желание реализовывать интеграцию, но мб потратить ресурсы на что-то другое?

Все простые интеграции на самом деле со всех сторон готовы. Все большие провайдеры кассового обслуживания интегрированы с Я.Кассой, другими средстами интернет-эквайринга, платежными платформами или имеют свои. Когда у тебя уже есть касса, завести экваринг и формочку для приема денег стоит несколько минут-часов: все интерфейсы разной степени кастомности есть прямо у операторов.

----

**Касательно приема денег юрлицом через кассу** 

Чтобы легально принимать деньги кассой нам нужно:
- ИП или юрлицо на рассчетный счет которого это делать
- ИП или юрлицу нужна квалифицированная ЭЦП
- нужно заключить договор с каким-либо сервисом онлайн-касс (я имел дело с Модуль.Кассой, например)
- получить кассовый аппарат и фискальный накопитель
- поставить на учет в наловогой
- завести договор и подлючиться к Яндекс.Кассе или другому средству интернет-эквайринга (например, их предоставляют комании предоставляющие обслуживание онлайн-кассы и банки)
- завести договор с ОФД

По моему опыту открытия ООО прошлым летом и выполнения всех этих операций для существующего юрлица все это при благоприятном стечении обстоятельств проворачивается за 3 рабочих дня, мне удалось за 5.

Чтобы сократить количество действий в реальном мире можно использовать пакетные предложения банков или компаний обслуживающих онлайн-кассы, типичная стоимость порядка 7-15к рублей или входит в стартовые пакеты обслуживания и аренды ККТ, [например, у Модуль.Кассы](https://modulkassa.ru/online-kassy/mobilnaya-onlajn-modulkassa-s-ehkvajringom-54-fz/#EasyStart).

Все шаги и процесс неплохо описаны, например, на сайте [Яндекс.Кассы](https://kassa.yandex.ru/recipes/online-kassy/chto-takoe-onlayn-kassa/)

Если регистрировать ООО, то это еще регистрация ООО в налоговой. [Это 3 рабочих дня в СПб.](https://www.nalog.ru/rn78/yul/interest/reg_yl/register/)

Но сама по себе подготовка к открытию ООО подоразумевает некоторую работу, например, если мы не хотим использовать типовой устав, а зафиксировать какую-то кастомщину в нашем.

Итого реализуемый минимум срока, если посмешить с решениями -- это 6 рабочих дней. Я бы расчитывал на примерно 10, плюс нам нужно будет принять минимум два решения, что означает еще минимум два кулдауна по 24 часа при отсутствии обсуждения. Итого: 8 дней на то, чтобы принимать деньги онлайн на счет юрлица -- это самый-самый минимум, который я не считаю реалистичным на основе того, сколько времени мы потратили на дискуссии о других достаточно важных для нас темах с максимумом заинтересованных лиц.

Также нужно понимать, что содержание ООО даже с нулевыми расходами и доходами обходится в некоторое количество денег (как минимум бухгалтерия в виде бухгалтера или сервиса полуавтоматизации) и/или времени. При наличии же расходов и доходов это количество денег и времени растет с ростом сумм и количества операций. Также не забываем про комисии: банка, компании обеспечивающей кассовое обслуживание, провайдера эквайринга.

----

**Касательно приема средств онлайн на счет физлица**

На мой взгляд без разницы Я.Соберу, Патреон или что-то еще. 

Мне кажется, что мы можем рассматривать это как безвозмездное дарение и принимать на счет физлица, если только это не членские взносы, так как они предполагают предоставление услуг в обмен на денежные средства, что классифицируется как предпринимательская деятельность, которая предполагает учет доходов и уплату налогов.

Физлицо, на счет которого будет происходить вывод должно осознавать риски попасть под следствие на основании 115-ФЗ, например. Риск мал, но негативные эффекты даже в процессе следствия весьма так себе, как минимум это ограничение контроллируемого оборота средств в отношении физлица.

Также ФНС вправе потребовать указать источник этого дохода и уплатить налоги и штрафы, если для них появятся основания, или доказательства того, что данные средства не являются доходом. Размеры штрафов могут достигать 100% суммы.

Мне известен один случай, когда вышеупомянутые риски были реализованы в отношении человека, с которым я лично был близко знаком, чтобы судить о достоверности сведений.

**Comment by kaero** [comment]
> В качестве юридического лица пока что использовать имеющиеся ЮЛ.

Нужно иметь в виду, что если имеющееся ЮЛ или ИП не работает с физлицами и не имеет ККТ, то кроме самого по себе подключения ККТ это приведет для него к увеличению бухгалтерской работы и стоимости и/или времни подготовки отчетности для ФНС. 

Также вид деятельности ЮЛ/ИП может непредполагать предоставления услуг физлицам, что может потребовать корректировки данных ЮЛ/ИП в ФНС. Это не блокер, но, согласно КоАП, ведение деятельности не декларированной ОКВЭДами предполагает штраф от 5к до 10к рублей.

**Comment by glitchcore** [comment]
Да, я не готов на свое ИП, например, вести такую деятельность как раз из-за ОКВЭДа и необходимости вести отчетность. Если мы хотим работать вбелую — надо регистрировать ООО и начинать работать.

Если мы хотим прямо сейчас принимать деньги — я бы взял любую самую незатратную по нашим ресурсам платформу для этого. Я готов на свое физлицо принимать деньги в течение 2 месяцев, считаю, что риск компенсируется возможностью быстрого старта.

**Comment by glitchcore** [comment]
С Леонидом обсудили этот вопрос, позиция такая: сейчас предлагать людям патреон и через месяц-два их перетаскивать на другую платформу будет неудобно.

Предлагается сейчас использовать в качестве временного решения ясоберу, где для оплаты нужны минимальные усилия, интеграцию с тем же СКУДом пока вести руками по назначению платежа, принимать деньги на физлицо (я все еще согласен).

Параллельно прорабатывать вариант с юрлицом и нормальной кассой.

Нужно создать страницу с описанием наших тарифов, инструкциями для пользователей, ссылкй на ясоберу.

**Comment by glitchcore** [comment]
важный момент в этом — назначение платежа должно быть какое-то уникальное, чтобы потом в СКУД его можно было использовать.

Например, можно сначала регать людей в системе, а потом они могут использовать свои никнеймы для оплаты

**Comment by sntxerror** [comment]
Про yasobe.ru. 

Предлагаю на странице с тарифами генерировать и показывать уникальный хэш для указания в комментарии к платежу. Человеку этот хэш нужно будет сохранить, для идентификации своего платежа.

Еще есть вариант, спрашивать у людей почту или телефон или ФИО.

Что скажете?

**Comment by glitchcore** [comment]
Про хэш — он где-то будет сохраняться? Например, сможет ли человек вместо хэша подставить какую-то свою строку?

**Comment by glitchcore** [comment]
Почта вроде более-менее ок, телефон или ФИО мне меньше нравится

**Comment by sntxerror** [comment]
Платежи можно принимать здесь https://yasobe.ru/na/b4cksp4ce, проверьте текст.

Нужна страница на сайте с тарифами.

**Comment by glitchcore** [comment]
Текст норм

**Comment by sntxerror** [comment]
Страница приёма средств есть. Страница с тарифами будет создана в отдельном issue

/d

**Comment by glitchcore** [comment]
А, ну да, вроде можно давно закрывать
