### ISSUE TITLE
Вступление Vepsian в участники

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#220]
В рамках обсуждения #209 @Vepsian выразил желание присоедениться к спэйсу в качестве участника. 

> Был на hw village и синт пати... Пилю потихоньку синт из Sega MD

**Comment by ardenfian** [comment]
Добавлю ещё, что основная сфера интересов - разработка Embedded систем и всё, что прямо или косвенно с этим связано
