### ISSUE TITLE
Инфраструктурный хакатон

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#222]
Что нужно сделать:
 - МАЙОР-IdP (единая точка авторизации / списков людей) 
 - КАПТЁР-CRM (бухгалтерия, календарь, что-то ещё)
 - ...

**Comment by sntxerror** [comment]
+Payment Gate

**Comment by sntxerror** [comment]
еще хорошо бы сюда прикрепить фотки доски со встречи про архитектуру сервисов

**Comment by sntxerror** [comment]
плюс интересно узнать какой статус работ по idp?

**Comment by heeeyflo** [comment]
@sntxerror у меня не осталось фотографии доски, кажется, фотографировал или ты, или @razve. 

По IdM/IdP я пока ничего не сделал, планирую плотно им заняться с четверга.

**Comment by vazhnov** [comment]
Для единой точки авторизации рекомендую попробовать FreeIPA. К сожалению, у меня нету опыта использования в prod, но игрался дома, очень впечатлило. Коллеги использовали в prod, полёт нормальный.

**Comment by NetBUG** [comment]
У нас FreeIPA в конь торе работает. Почти идеальный полёт.

**Comment by glitchcore** [comment]
Bump

@sntxerror @imcatwhocode я готов поучаствовать удаленно. Давайте запланируем на какой-нибудь выходной в июле?

**Comment by glitchcore** [comment]
Связанные задачи:
#237 про креды
#223 тоже про группы/креды
#190 еще про креды
#106 про оплату
#206 публиковалка финансов

**Comment by glitchcore** [comment]
Предлагаю собраться в выходные 18-19

**Comment by glitchcore** [comment]
В итоге решили, что собираемся 1-2 августа, нужно накидать scope работ

**Comment by p-hash** [comment]
Кажется хакатон остался в прошлом. Предлагаю закрыть эту issue и завести отдельные issue для каждого проекта:
1. IdP/LDAP/etc (связанные: #237)
2. CRM/бухгалтерия (связанные: #106 #206)
3. payment gate (я полагаю, невозможно без IdP)

Tag: @imcatwhocode @sntxerror @glitchcore

**Comment by glitchcore** [comment]
Думаю, да, идея хакатона не получила поддержки.

Я не вывожу участвовать в этой части.

/d

**Comment by heeeyflo** [comment]
Мы с @sntxerror недавно пришли к выводу, что мы не хотим возиться ни с разработкой своего IdP, ни с допиливанием и мейнтенансом какой-нибудь FreeIPA. Вместо этого сошлись на том, что будем использовать Github как абстрактный OAuth2-провайдер и завязываться на него. Возможно, облегчим часть наших задач через Auth0, но у него свои ограничения, с которыми мы ещё не до конца разобрались.

Касаемо бухгалтерии и прочего — бесполезно пытаться сейчас вывезти эти сервисы, у нас просто полгода опускались руки от объёма работы, а запала хватало максимум на планирование архитектуры. Как @sntxerror закончит с переносом сайта на Gatsby, мы начнём разбираться одновременно и с Payment Gateway для приёма платежей и донатов, и с Github OAuth / Auth0. После этого уже будем итеративно это дорабатывать, как было со СКУД.

**Comment by p-hash** [comment]
@imcatwhocode good point. Осталось только
1. Закрыть эту issue
2. Создать еще парочку релевантных issue (на те задачи, которые хочется, но пока не можется) 
3. Обновить те issue, что я прилинковал выше

**Comment by heeeyflo** [comment]
Ввиду того, что функции IdP будет выполнять Github или Auth0, issue перестаёт быть актуальной. 
Задачи по КАПТЁР-CRM (оно же, условно, финансовый сервис) будут созданы в соответствующем репозитории, когда начнётся работа над этим сервисом.
