### ISSUE TITLE
Составить список рабочих групп и ресурсов

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#223]

**Comment by sntxerror** [comment]
@z4fd надо освежить постановку задачи, сейчас не очень понятно что нужно сделать и как это двигать

**Comment by glitchcore** [comment]
Мне кажется, дублирует #237, предлагаю закрыть

/d

**Comment by sntxerror** [comment]
поддерживаю мысль, идея не особо развилась.

думаю стоит позже отразить в инфе для участников, что для внутренних задач спейса участники самоорганизуются в рабочие групы и генерируют и получают друг от друга необходимые доступы, можно там же указать ссылку на ишью с доступами, потом сделаем IDP в которой будет прозрачно видно у кого что есть. нужно будет так же указать в правилах что при создании обдщего ресурса креды от него нужно внеси в репу в gh. факт внесения кредов от сервиса/ресурса через PR можно будет считать "официальным принятием" того или иного ресурса.

/d
