### ISSUE TITLE
Перенести управление DNS из Google Domains

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#224]
В разговоре с @rusdacent вчера снова поднялась тема нарезки физического сервера на виртуалки, и я упёрся в своих размышлениях в вопрос терминации TLS на хосте. Самый оптимальный вариант, на мой взгляд, выпустить стандартный wildcard для *.0x08.in в Let's Encrypt, а это возможно только через DNS-01 challenge, подразумевающий валидацию через TXT-запись. Для этого нужна возможность рулить DNS-записями 0x08.in через апишку, а Google Domains такого функционала не даёт.

Есть обходной путь — сделать CNAME нужной записи на другой домен, записями которого можно рулить через апишку, но это похоже на велосипед с очень квадратными колёсами.

За всем вышеперечисленным, предлагаю вынести управление записями из Google Domains во что-нибудь другое, например, Cloudflare в DNS-only режиме.

/a

**Comment by sntxerror** [comment]
два чая этому господину поджалуйста!!

**Comment by heeeyflo** [comment]
Готово, управление доменом теперь в Cloudflare, DNSSEC активирован, креденшелы к CF лежат в KeePassXC-кейчейне в репе.
