### ISSUE TITLE
Формат новостного дайджеста

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#227]
Предлагаю регулярно собирать у участников новости спэйса о том, что появилось, кто стал участником и чем занимается, и публиковать в виде поста об активностях и различном движении в жизни места в канале.

Необходимо зафискировать формат новостного сообщения. Для примера предлагаю первые сообщения в канале с микро отчетами о происходящем.

**Comment by glitchcore** [comment]
У меня какое-то время висит в голове идея сделать канал с новостями (BRE4CKING News, B4CKSP4CE Fake News, etc. ), куда с помощью бота любой из участников сможет постить любой контент, который ему захочется: фотоотчеты с мероприятий, адовые видео с зеленой жижей и экологинчыми хлопушками и прочее.
Зафиксировать правила канала. В будущем бота можно настроить на постинг в vk/twitter/instagram.

Основной канал оставить для анонсов мероприятий и, как вариант, делать еженедельный дайджест событий (как вариант, привязать дайджест к анонсу ДОД).
