### ISSUE TITLE
Стратосферный проект

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#229]
Начинаем псевдокосмическую программу Бэкспейса! Идея в запуске небольшого метеозонда ближе к лету.

Имеет смысл начать с небольшой встречи для того чтобы:
- сформировать первичную рабочую группу
- порешать задачу рюкзака с фичами и габаритами
- прикинуть роадмап 
- попить чаю 

Предлагаю провести встречу в пятницу или субботу (3/20 или 3/21, соответственно).

**Comment by heeeyflo** [comment]
Вероятно, анонс за день / два это слишком мало и стоит перенести встречу на неделю.

**Comment by glitchcore** [comment]
Сделал репозиторий проекта: https://github.com/b4ck5p4c3/aerospace
