### ISSUE TITLE
Join-request

### ISSUE THREAD

**Issue by NetBUG** [b4ck5p4c3/0x08.in#23]
Сабж.

**Comment by glitchcore** [comment]
Уже говорил: если речь о существующих репозиториях, то добро пожаловать с PR/issues. Если хочешь добавить новый в гитхаб спейса, то давай предметно — что именно хочешь добавлять

**Comment by glitchcore** [comment]
Добавил тебя в группу sudoers. Например, репозиторий со столом форкнул в эту группу
