### ISSUE TITLE
Участие в makers against covid #3дврачам

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#236]
Есть инициатива https://habr.com/ru/post/495692/
Ребята предлагают печатать элементы защитных масок и переходников для фильтров.

Сейчас задача в том, чтобы печатать детали и передавать волонтерам.

Для печати предоставляют пластик и запчасти к принтерам.

Текущая ситуация (детали, которые делают в питере, потребность и покрытие): https://docs.google.com/spreadsheets/d/14ltI_DRrYaryVln5akK4DPJDlYjn8jvaJnCO8buNxqY/edit#gid=0

Есть локальный питерский чат https://t.me/CVD3D_Spb, что-то обсуждают в https://t.me/spb_3d_printing

У меня сейчас есть несколько вопросов по всей этой инициативе:

1. Мне пока не очень понятна эффективность предлагаемых изделий.
2. Прорабатывал ли кто-нибудь вопрос регистрации мед.изделий? Я некоторое время работал с регистрацией мед.изделий и наслушался историй, как врачей привлекали к уголовной ответственности за использование изделий без рег.удостоверения.
3. Волонтеры перемещаются по городу, вы как-то решали вопрос с нарушением режима самоизоляции?
4. В хакспейсе есть принтер, он годится для участия?
5. В комментариях я почитал про альтернативный вариант, для которого нужен лазер: https://www.protohaven.org/proto-shield/. В теории можно из нашего ЧПУ гравера сделать лазерный, сделав крепление для лазера и продумав вытяжку.
6. В связи с некарантином доступ в хакспейс затруднен (кстати, насколько?). Я думаю, что работать с принтером смогут только ребята, которые живут рядом.

**Comment by kitnerboy** [comment]
В СПб никакой изоляции пока нет, перемещение свободное,  самоизоляция добровольная. 
Пропуска никто не проверяет.

**Comment by glitchcore** [comment]
nobody cares
