### ISSUE TITLE
Список субъектов доступа спэйса

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#237]
Собираем что у нас есть: почты, карты, репозитории, сервера и прочее. Пишем у кого к чему есть доступ.

*Не публикуйте креды!*

**Comment by heeeyflo** [comment]
Что есть у меня:
1. Доступ к cred-репозиторию в Bitbucket.
2. Доступ к Яндекс.Облаку.
3. Мембер с ограниченными возможносятми в Github.
4. Суперпользовательский доступ к Matrice (ВМ в Облаке для Space API и пресенс-бота) — __**кажется доступ есть только у меня и это нужно пофиксить как можно быстрее.**__
5. Суперпользовательский доступ к Escape (сервер в предбаннике)
6. Суперпользовательский доступ к RPi со СКУДом.
7. Доступ к BotFather для пресенс-бота.

Upd:
8. Доступ к IP-телефонии спейса.

**Comment by sntxerror** [comment]
У меня есть:

1. Доступ к таблице учета финансов
2. Доступ к папке в Гугл Диске (квитанции, счета)
3. доступ к bitbucket
4. админ в github
5. sudo на серваке (Escape)
6. sudo на RPi
7. админ в чатах и каналах спэйса
8. Админ в паблике vk
...

**Comment by glitchcore** [comment]
У меня есть

1. Доступ к таблице учета финансов
2. Доступ к папке в Гугл Диске (квитанции, счета)
3. Доступ к bitbucket (репа с кредами) + мастер-пароль от keepass
4. Админ в github
5. Учетка с sudo на серваке (Escape)
6. Ключ для пользователя pi на RPi
7. Админ в чатах и каналах спэйса
8. Админ в паблике vk
9. Доступ к странице хакспейса на hackaday.io

**Comment by sntxerror** [comment]
@z4fd добавь плиз если у тебя есть чтото

**Comment by heeeyflo** [comment]
Вроде бы сейчас в Keepass относительно актуальный список общих креденшелов к различным ресурсам. 

Для тех ресурсов, у которых нет общего аккаунта (Облако, группа ВК, чаты в Telegram) я создам плейсхолдер-учетки в Keepass, в заметках к которым укажу список людей обладающих доступом к ним, согласно информации выше.

**Comment by glitchcore** [comment]
@imcatwhocode ты делал плейсхолдеры, таску можно закрыть?
