### ISSUE TITLE
Выработать подход к проведению онлайн встреч и ивентов

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#238]
пределиться с инструментами и ресурсами (например jitsy), понять ограничения

**Comment by vazhnov** [comment]
Оно называется Jitsi.
Можете вот тут попробовать готовый: https://meet.infomaniak.com/?lang=en , мопед не мой.

**Comment by a-andreyev** [comment]
Плюсую за jitsi.

Если пробовать, то, наверное, напрямую от разработчиков: https://meet.jit.si/ (если не ошибаюсь, @z4fd так и включал существующие конференции?)

Из подвохов слышал про какие-то временные мелкие ограничения на firefox, которые чинят.

Также jitsi встраивается в matrix, вот свежий обзор от авторов matrix: https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi. Т.е. долгосрочно можно поднимать на своем серваке, и matrix будет служить для инициализации встречи, а jitsi — для webrtc конфы (даже подготовлены Ansible/Docker решения для развертывания https://github.com/spantaleev/matrix-docker-ansible-deploy)

Кроме того, интеграция с jitsi также поднята и на (вечно перегруженном) публичном matrix.org, на котором мы хостим свою [комнату](https://matrix.to/#/%23b4ck5p4c3:matrix.org) — так что можно тыкать кнопку "videocall" там и конференция поднимется.

**Comment by glitchcore** [comment]
Какие вопросы мы хотим решить этим issue?

Сейчас если у кого-то возникает идея, он может анонсировать ее как мероприятие, или спонтанно собрать народ без анонса, далее создать комнату в jitsi и базарить там. Впрочем, можно и другой инструмент использовать, если это будет в конкретном случае удобно.

**Comment by glitchcore** [comment]
Мне кажется, стоит закрыть, мы уже неоднократно собирались в онлайне

/d
