### ISSUE TITLE
Рассчитаться за пиццуню

### ISSUE THREAD

**Issue by mcheshkov** [b4ck5p4c3/0x08.in#24]
@mcheshkov заплатил за пиццу 27.10.2019 своей картой 
Телепицца
Заказ 274595, _вроде бы_ был оформлен на @sntxerror
Списали 4297 руб.

**Comment by glitchcore** [comment]
Есть срочность компенсировать тебе или ты готов пока подержать долг?

**Comment by mcheshkov** [comment]
Да

**Comment by mcheshkov** [comment]
Если серьёзно - не горит

**Comment by kaero** [comment]
я компенсировал @mcheshkov , записал в расходы спейса

**Comment by mcheshkov** [comment]
Получил перевод

Михаил Чешков
