### ISSUE TITLE
Добавить спэйс на hackaday.io

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#240]
https://hackaday.io/hackerspaces

**Comment by sntxerror** [comment]
Надо немного фоток и небольшой список тулов

**Comment by glitchcore** [comment]
Оу, был уверен, что мы добавились туда

upd: аа, мы на https://wiki.hackerspaces.org/B4CKSP4CE есть, а не на hackday

**Comment by glitchcore** [comment]
https://hackaday.io/hackerspace/170863-b4cksp4ce

пишите свои аккаунты на hackday, кто хочет присоединиться к редактированию

**Comment by lomalkin** [comment]
Еще стоит зафолловить пространство, нажав на кнопку по ссылке спейса.
Т.к. там идет сортировка по количеству фолловеров, чтобы быть более заметными.
