### ISSUE TITLE
Телефония в спейсе

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#242]
Предлагаю решение для телефонии в спейсе: я регистрирую на себя номер в IP PBX и при первой возможности притаскиваю в спейс SPA2102 к которой мы подключаем аналоговый телефон.

Проблема этой схемы в том, что сейчас в спейсе почти не бывает людей, соответсвенно никто не сможет ответить на звонки. Предлагаю выработать какие-то правила маршрутизации, чтобы этого не происходило.

**Comment by sntxerror** [comment]
Обсудили с арендодателем подклчюение к РТ. Выяснилось что сейчас в связи с короновороной заявления не оформляются. И да,  случае если в спэйсе никого нет, аппарат становится не актуальным.

Поддерживаю идею регнуть номер в IP-BBX. Маршрутизировать предлагаю рандомно на добровольцев из списка.

**Comment by lomalkin** [comment]
Зачем в спейсе нужна телефония? Мне только про модемное назначение мысли в голову приходят, м.б. BBS поднять.
Зачем еще?

**Comment by heeeyflo** [comment]
@lomalkin по-сути, единственное зачем она нужна — это городской номер для регистрации организаций в гео-сервисах.

**Comment by glitchcore** [comment]
Если это только для реги  — Фил же решал проблему виртуальной АТС, почему плох этот вариант?

**Comment by heeeyflo** [comment]
> Если это только для реги  — Фил же решал проблему виртуальной АТС, почему плох этот вариант?

@aanper то же самое ведь и делаем, только ещё и с VoIP-коробкой в спейсе чтобы подключить _Машину Автоматического Ответа Со Встроенным Тэйп Дисторшеном_ и потенциальный таксофон.

**Comment by heeeyflo** [comment]
Давайте теперь считать что у спейса номер +7 (812) 507-92-41.

Кто готов принимать звонки — скиньте мне в тележную личку номер телефона или тыкните и я скину данные для SIP-а.
