### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by p-hash** [b4ck5p4c3/0x08.in#244]
Плюсы: 
+ звонки
+ видеоконференции 
+ шаринг экрана
+ видно кто сейчас в звонке и кто стримит экран
+ можно стримить одновременно (!) в одной конфе (!!)
+ можно делать несколько текстовых и/или войс каналов
+ гибкие настройки приватности, правил доступа, группы админов, лычки всякие
+ после создания право владения сервера передам кому-то более ответственному, если оно взлетит конечно

Минусы: 
- текстовые сообщения работают медленно и неудобно

Пример: 
[Дискорд клавиатурных фанатов МехКульта](https://discord.gg/RFSjmV9)

**Comment by z4fd** [comment]
Из чата:

1. Какую проблему будет решать новая сущность ?


"Насчёт первого:

Дискорд какой-то более открытый нежели чем джитси и, как мне кажется,  воспринимается по другому. Там легче создать стихийную встречу, потому что встреча в джитси воспринимается как какое-то собрание раз в неделю, для которого надо выбрать время, потом создать комнату и позвать всех. В дискорде у нас есть сервер: текстовые чатики + голосовые каналы, в которые могут зайти любые участники в любое время и общаться. 

При этом ничего не мешает также собираться в конкретное время как в джитси"


1. Какую проблему будет решать новая сущность ?

"почему бы не создать еще один канал взаимодействия — если кому-то удобнее там, почему бы не дать выбор"

**Comment by glitchcore** [comment]
Не вижу возражений. @p-hash создай сервер и отправь креды/передай владение любому из участников

**Comment by p-hash** [comment]
https://discord.gg/fGYjgtM

**Comment by p-hash** [comment]
Передал server ownership участнице @frogsandsocks
