### ISSUE TITLE
Итоги встречи 09.06.2020

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#245]
Мы на собрании обсудили только вопрос размещения станков, потому что сейчас они стоят на временных местах, которые рискуют стать постоянными.
После обсуждения мы решили переделить территорию спейса, и вот **к чему пришли**:

- Большой зал остаётся чистой зоной для чилла с хакерами, мероприятий, мастер-классов. Здесь не должно быть станков, грязных и шумных. 

- Средний зал (нынешняя резидентская) становится станочно-слесарной или _грязной_ комнатой. Там размещается токарник, 3D принтер, CNC. Также есть идея установить верстак во всю левую стену (обшитую вагонкой), а на стену налепить перфолент под инструмент. Вся грязная и шумная работа будет происходить здесь.

- Мелкая комната с лежанкой (текущая "переговорная") становится резидентской.

Такой расклад спорный и обязательно вызовет недовольство кого-то из участников, но вот наше **обоснование**:

1. 1 Это позволит административно отделить резидентскую дверью с замком, ограничив доступ обычных участников.
2. 2 Также для проведения мероприятий не нужно будет перетаскивать инструмент и станки куда-либо. Чистая зона остаётся чистой без лишних хлопот.
3. 3 Наконец убирается половичок, под который мы заметали мусор (я про текущую "переговорку"). Пора уже перестать использовать небесплатную площадь под неэффективное хранение хлама, который нам не хватает сил разложить.

Есть и **минусы**:

1. 1 Резидентская отделена от грязной зоны достаточно тонкой стеной без намёка на звукоизоляцию. Но что тут поделаешь - такова особенность нашего помещения.
2. 2 Мы пока отказываемся от сущности переговорки. Возможно, стоит подумать над переорганизацией входной части спейса (до большого зала) и каких-то рокировок там. Как минимум нужно более эффективно использовать "серверную", и не хранить там хлам.

**Comment by sntxerror** [comment]
В изначальной идее была еще мысль установить прозрачный экран, для отеления прохрда к ркзидентской от работающих с оборудование/за верстаком людей

**Comment by sntxerror** [comment]
Плюс в общем пространсве всеж верстакпригодился бы и паяльный стол оттуда убирать не планировалось по задумке

**Comment by sntxerror** [comment]
К тому же, предлагаю размещать вкрстаки как в хв зоне так и в обшемпространстве, вдоль стены с окном. Так в хв зоне мы не потеряем доступ к подоконникам из-за установленного оьорудования, а в общем пространстве сможем еще и не потратить много места необходимого для мероприятий. Плюс в общемзале будет на чтотопереться/присесть в заднем ряду

**Comment by sntxerror** [comment]
Еще бы хотел отметить вопрос переговорки.

С собственником помещения согласована установка перегородки для неё в текущем тамбуре-кухне. На месте нынешней вешалки.

Серверную я предлагаю максимально освободить, чтобы сделать место для вещей там, ращместив на стенах крючки.

Полки стоит убрать, CNC уедет в хв зону. Скуд можно закрепить выше, у потолка, а сервер разместить в резидентской.

**Comment by glitchcore** [comment]
В целом я поддерживаю инициативу:
1. Со станками сейчас и правда непонятная ситуация, + уже были прецеденты, когда нерезиденты работали в резидентской. В целом помещение-нынешней-резидентской позволяет во время мероприятий и прочей активности отделиться от остальных, даже если речь не идет о грязных-шумных работах.
В связи с этим я предлагаю помимо верстака в грязной комнате оставить хотя бы один рабочий стол для общей работы.

2. Сколько у нас сейчас резиденстких столов, влезут ли они в нынешнюю-переговорку?
3. Про переговорку: мы думали в будущем сделать ее у входа (#77)
4. Про нынешнюю серверную: раз из нее уезжает оборудование, можно там организовать хранение более активно.

**Comment by sntxerror** [comment]
>     2. Сколько у нас сейчас резиденстких столов, влезут ли они в нынешнюю-переговорку?

В перкговорку комфортно влезет три рабочих места. 

Сейчас у нас 3 резидентских стола и 1.5 резидента. Эти полтора резидента занимают 1.5 стола соответственно. Один стол свободен целиком.

**Comment by glitchcore** [comment]
> В изначальной идее была еще мысль установить прозрачный экран, для отеления прохрда к ркзидентской от работающих с оборудование/за верстаком людей

мне кажется, сейчас это не так обязательно, у нас полтора резидента и поток людей будет небольшой + всех резидентов проще предупредить о мерах предосторожности при хождении рядом с работающими станками (типа «не заглядывать из-за плеча когда кто-то точит»), а тот же токарник можно поставить так, чтобы стружка и прочие несовместимые с жизнью предметы не летели в проход

**Comment by sntxerror** [comment]
> В связи с этим я предлагаю помимо верстака в грязной комнате оставить хотя бы один рабочий стол для общей работы.

Один стол для общей работы я бы предложилоставить там где есть, в общем зале. В хв-зоне будет верстак, за которым можно работать., Так же верстак я бы предложил размещатьв общем зале тоже.

**Comment by glitchcore** [comment]
> Плюс в общем пространсве всеж верстакпригодился бы и паяльный стол оттуда убирать не планировалось по задумке

я за то, чтобы не делать верстак в общей зоне. Ну вот насколько часто нам нужен верстак в наших задачах? И работы эти почти всегда грязные-шумные, так что целесообразно пойти их делать в грязную комнату.

**Comment by glitchcore** [comment]
> Серверную я предлагаю максимально освободить, чтобы сделать место для вещей там, ращместив на стенах крючки.

можно поставить стеллаж размером с половину серверной или полок навешать

**Comment by glitchcore** [comment]
> Один стол для общей работы я бы предложилоставить там где есть, в общем зале.

Согласен, рабочий стол в общем пространстве часто пригождается

**Comment by sntxerror** [comment]
> > Плюс в общем пространсве всеж верстакпригодился бы и паяльный стол оттуда убирать не планировалось по задумке
> 
> я за то, чтобы не делать верстак в общей зоне. Ну вот насколько часто нам нужен верстак в наших задачах? И работы эти почти всегда грязные-шумные, так что целесообразно пойти их делать в грязную комнату.

А паяльный стол текущий? Может тогда он и есть тот общий? Может тогда все таки убрать его в хв?

**Comment by kitnerboy** [comment]
> Серверную я предлагаю максимально освободить, чтобы сделать место для вещей там, ращместив на стенах крючки.

Вчерашний путч неспроста назывался дождливым.
В случае дождя мокрые куртки на крючках будут неприятны для копания там, вещи не будут сохнуть вовсе. Стоит подумать над тем, как можно разместить штангу для плечиков всё же.

**Comment by sntxerror** [comment]
> > Серверную я предлагаю максимально освободить, чтобы сделать место для вещей там, ращместив на стенах крючки.
> 
> можно поставить стеллаж размером с половину серверной или полок навешать

Проблема хранения вещей людей втсвала уже не один раз, всякие материалы и полещный стафф я бы лучше хранил в понятном, видном месте, в общем зале.

**Comment by glitchcore** [comment]
> А паяльный стол текущий? Может тогда он и есть тот общий? Может тогда все таки убрать его в хв?

Мне кажется, пайка меньше относится к станочным-хардкорным работам и ей больше место в общем помещении. Я бы предпочел работать с электроникой не рядом со стружкой, маслом и пылью.
И на мероприятиях типа мастер-классов нужен паяльно-электронный стол.

**Comment by glitchcore** [comment]
В общем, я думаю, что стоит

* первым приоритетом сделать верстак во второй комнате, если возникнет необходимость — сделать еще один в общей зоне.
* Оставить во второй комнате один рабочий стол для тех, кто хочет отделиться от тусовочки
* Организовать во второй комнате стол для CNC и 3D-принтера (мой стол, возможно, подойдет для этого)
* Паяльный стол из общей зоны не трогать
* Перенести два стола в переговорку и сделать ее резидентской. Возможно, перенести магнитный замок на дверь переговорки

**Comment by glitchcore** [comment]
> Проблема хранения вещей людей втсвала уже не один раз, всякие материалы и полещный стафф я бы лучше хранил в понятном, видном месте, в общем зале.

у нас сейчас куча сомнительного стаффа лежит в переговорке (хотя у меня могут быть неактуальные представления). Возможно, логичным вариантом будет перенести его в серверную, организовав там хранение

**Comment by glitchcore** [comment]
По планировке ХВ: я предлагаю

* у одной стены сделать угловой верстак: во всю стену + на углу место для токарного станка, чтобы он стоял так, чтобы говно летело преимущественно вдоль комнаты, не в проход.
* у второй стены поставить с одной стороны рабочий стол, с другой стороны стол с CNC и принтером

Где делать верстак, у окна или у стены — не понимаю.

Доступ к подоконникам в любом случае остается. Если верстак у окна — можно подоконники использовать как доп. поверхность, если верстак у стены — появляется возможность на деревянную стену накрутить крепежа для инструмента  во всю высоту.
