### ISSUE TITLE
Создание Wishlist с оборудованием и инструментом 

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#246]
Собственно, консолидируем сюда все хотелки, а также варианты по созданию простой системы внесения и отображения этого вишлиста в нашей системе.

**Comment by kitnerboy** [comment]
Нам нужно что-то для пиления не вручную.

- Лобзик
- Паркетка

**Comment by kitnerboy** [comment]
~~Для smd уроков в рамках Soldering Buddies нужна пачка пинцетов. Металлические, штук 10.~~
Также туда нужно USB БП с током от 1А для проверки готовых девайсов. Для других целей они тоже не помешают.
Подставки под паяльники. Не больше 8.

**Comment by kitnerboy** [comment]
~~Ноутбук для гостевого доступа, способный крутить хотя бы современные браузеры и имеющий WiFi.~~

**Comment by heeeyflo** [comment]
> Ноутбук для гостевого доступа, способный крутить хотя бы современные браузеры и имеющий WiFi.

@elsidoi а мы не можем для этих целей использовать один из неттопов, которые сейчас в хакспейсе? Например, оставить одну учётку для участников с нормальными правами, и вторую учётку гостевую, с временным профилем (правда, IDK есть ли такая фича в Windows).

**Comment by kitnerboy** [comment]
@imcatwhocode можно и так, но с ноутом как-то мобильнее. Места со стационарным монитором у нас нет, так что каждый раз гость вынужден будет подключать этот неттоп к чему-то, морочиться. А так взял ноут - и сиди делай дела.
На безрыбье то конечно обойдёмся хоть чем.

**Comment by glitchcore** [comment]
Я напомню, что страница уже есть: https://0x08.in/needs.html
можно попробовать поддерживать ее в актуальном состоянии.
Если вы поддерживаете эту идею, перенесите в эту страницу свои предложения из этого треда.

_Алсо можно смягчить правило про редактирование-только-через-PR для некоторых страниц (вишлист, список вещей), что бы cooldown не был препятствием, а участники могли сразу (например, через вебморду гитхаба) писать_

**Comment by sntxerror** [comment]
https://github.com/b4ck5p4c3/spacebot/issues/11

**Comment by p-hash** [comment]
Привязываю сюда
#221 -- нужна память для 286
#269 -- нужен переходник vesa100-vesa200

**Comment by lomalkin** [comment]
> Привязываю сюда
> #221 -- нужна память для 286
> #269 -- нужен переходник vesa100-vesa200

Мне кажется верным подход **создавать на каждую требуемую вещь отдельный issue**, но стоит также все их объединять под каким-нибудь тегом, например #needs, т.к. поддерживать статическую страницу в актуальном состоянии не получается, как показала практика.
Это позволит тому, кто запросил вещь закрывать issue при появлении этой вещи в спейсе.
Я вот до сих пор не могу понять, все еще нужны ли спейсу кабели или нет.

Со страницы:
> Вишлист
> 
> Прямо сейчас нам требуются:
> 
>     кабели IEC C13
>     кабели IEC C7
>     ручной инструмент: отвертки, пассатижи, гаечные ключи, кусачки, пинцеты.
>     оборудования для записи и проведения трансляций (камеры, микрофоны, карты захвата и так далее)
> 

2. Было бы здорово сделать либо возможность автоматической выгрузки на эту страницу заголовков issue по этому тегу, либо просто заменить список на ней на ссылку на гитхаб.

**Comment by glitchcore** [comment]
Идея про тег звучит разумно.

Можно сделать несколько фильтров, чтобы эти ишью не мешались в общем списке, или по проектам их раскидать

**Comment by heeeyflo** [comment]
Нужно учесть это по завершению работ над новой версией сайта, и собирать страницу с вишлистом по данным Github API. Возможно, даже, эти issues можно будет подгружать динамически через открытое Github API, но нужно проверить.

**Comment by glitchcore** [comment]
Кажется, вишлист никем не поддерживается, но если что — по результатам обсуждения вижу что не вызывает возражений вариант создавать здесь или в канале отдельные ишью с потребностью.
