### ISSUE TITLE
Пост о возвращении

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#249]
**B4CKSP4CE 1.0.0**
_Длиннопост на 5 минут_

Привет, друзья!

Как вы уже успели заметить, мы практически пропали с радаров: не проводим мероприятий, не делимся новостями. Можно было подумать, что мы закрылись или остановились в развитии, но спешим вас обрадовать – это не так! :) Хоть некоторые из нас и переболели, все мы живы и здоровы, а самое главное – у нас много новостей! 

В самом начале весны мы быстро поняли, что ивенты проводить не удастся, что у людей поубавилось желания бывать в людных местах. Естественным образом, мы со всеми участниками взяли неофициальную паузу.

Пока спэйс тихо покрывался пылью, его участники и друзья не переставали поддерживать место финансово.  Благодаря вашим ресурсам место продолжает жить и развиваться!

**ОГРОМНОЕ ВАМ СПАСИБО!!!**

Нам еще есть к чему стремиться, у нас много идей и задач, обещаем радовать :) 

В мае мы потихоньку начали оживляться. Нам исполнилось полгода и мы вышли из Public Beta! Изменений – масса, смотрите CH4NGEL0G в последней части поста, но кое что важно отметить отдельно.

**Как мы работаем в период продолжающейся пандемии**

В основном всё как раньше: **бэкспэйс работает и его можно посещать, когда он открыт**. Гости могут приходить, когда в спэйсе есть кто-то из участников, а участники могут приходить с гостями.

Вопрос безопасности всегда был для нас на ~~третьем~~ первом месте, поэтому к сожалению, в новой реальности было решено временно отказаться от еженедельного Дня Открытых Дверей. Вместо этого мы приглашаем вас приходить в любой удобный момент, когда спэйс открыт (об этом чуть дальше).

Тем не менее, при любом посещении спэйса нужно учитывать следующее:

1. Публичные мероприятия, события и встречи, где планируется больше 5-7 человек проводятся только в онлайне. Целиком или совмещёно. Если в спэйсе уже набралось 5-7 человек – приходить лично не стоит.
2. Посещая спэйс вы принимаете на себя риски, и поэтому приходите только если вы:
  а) не болеете и в последние пару дней у нас не было симптомов ОРВИ
  б) не боитесь заболеть и заразить ваших друзей, близких и родственников

В спэйсе есть немного одноразовых перчаток, антисептик для рук, спиртовой раствор для обработки поверхностей. Мы обсуждаем проект принудительной вентиляции, рециркуляции и дезинфекции воздуха в помещении, но пока что этот проект не завершен. В этом вы можете нам помочь.

**Как понять что спэйс открыт**

Перед посещением важно убедиться, что спэйс открыт и предупредить участников. Для этого мы создали бота @b4cksp4ce_bot. Он подскажет вам открыт ли спэйс, а так же позволит отправлять сообщения напрямую участникам и получать от них оперативные ответы. Пользуйтесь командой /help чтобы узнать подробности.

**Где ещё новости, Карл?**

В прошлой версии спэйса был только один канал для получения официальных анонсов и новостей (этот пост опубликован в нём). Ещё до паузы, мы осознали, что в этом канале осталось мало повседневной жизни и внутренней кухни, нас это огорчало.

Поэтому мы решили оставить имеющийся канал @b4ck5p4c3 только для официальных анонсов и больших новостей, а для ~~неконтронтролируемого трэша и угара~~ неформальных постов мы завели новый, более лучший @b4cksp4ce_l1ve.

В него могут писать все Участники, на любую тему околоспэйса, проектов и технологий. Локальные мемы тоже будут.  Подписыйвтесь и делитесь, а мы будем делиться с вами!

Подытоживая, мы рады вернуться и приглашаем вас в гости, пить чай, кодить, паять, фрезить, точить, печатать, _делать устройства_, творить, расти и делиться опытом и создавать B4CKSP4CE! Пишите боту, участникам, подписывайтесь на новый канал. 

Спасибо!

**CH4NGEL0G**
- произошел дождливый путч :)
- на путче приняли новую конфигурацию помещений
-- резидентская комната переехала вглубь спэйса 
-- кухня обросла микроволновкой, сушилкой посуды, скоро подъедет обеденный столик
-- появилась общедоступная комната выделенная под Hardware Zone, в ней установлены:
--- токарный станок по металлу JET BD-7VS 
--- 3D принтер TL-D3 Pro (два экструдера!)
--- CNC станок (да, он был всё это время)
--- стол для пайки и отладки (станция, БП, осцилограф etc...)
- починили входные двери, теперь они исправно открываются и закрываются без услилий
- прокачали интернет-подключение спэйса до 300+ mbit/s 
- прокачали СКУД, теперь работает presence switch
- заменили раковину и смеситель в уборной
- уронили экран проектора и снова его повесили
- создан чат в Discord
- создан канал b4cksp4ce_l1ve
- создан бот b4cksp4ce_bot
- канал и чат единообразно переименованы b4cksp4ce и b4cksp4ce_chat (никто не заметил, да?)
...

T0DO:
- окраска стен помещений
- рабочее место с PC в HW Zone
- вентиляция в общем зале и HW Zone
- верстаки в общем зале и HW Zone
- peg board в в HW Zone
- дежурные розетки в HW Zone
- перенос сервера в HW Zone
- рефакторинг сайта
- донаты с общедоступными логами
- обустройство гардеробной
- обустройство кухни
-- столешница со шкафами
-- небольшой холодильник
-- круглый обеденный столик

... и многое другое!

**Comment by sntxerror** [comment]
Пост будет разделен на четыре части. Пишите замечания, дополняйте в коментах changelog,

**Comment by algroznykh** [comment]
предлагаю выпилить вступление до 'Как мы работаем в период продолжающейся пандемии', как-то безрадостно от него

**Comment by glitchcore** [comment]
А как именно будет разделен пост? В начале есть ссылка на changelog «в конце поста», как это будет?

**Comment by sntxerror** [comment]
> А как именно будет разделен пост? В начале есть ссылка на changelog «в конце поста», как это будет?
1. B4CKSP4CE 1.0.0 ... кое что важно отметить отдельно.
2. Как мы работаем ... В этом вы можете нам помочь.
3. Как понять что спэйс открыт ... Спасибо!
4. CH4NGEL0G

**Comment by sntxerror** [comment]
> предлагаю выпилить вступление до 'Как мы работаем в период продолжающейся пандемии', как-то безрадостно от него

Я все же считаю что нам важно отразить и наше серьезное отношение к топику и прозрачно для всех обозначить ситуацию.

Могу понять безрадостность, и да это звучит как бе официально, но на мой взгляд это именно то что в такой ситуации ожидается.

**Comment by glitchcore** [comment]
> > А как именно будет разделен пост? В начале есть ссылка на changelog «в конце поста», как это будет?
> 
> 1. B4CKSP4CE 1.0.0 ... кое что важно отметить отдельно.
> 2. Как мы работаем ... В этом вы можете нам помочь.
> 3. Как понять что спэйс открыт ... Спасибо!
> 4. CH4NGEL0G

Ты планируешь сделать паузу между частями? Просто получается что обещаем changelog, а его в конце сообщения не будет

**Comment by sntxerror** [comment]
> Ты планируешь сделать паузу между частями? 

Планировал без паузы.

**Comment by sntxerror** [comment]
>  Просто получается что обещаем changelog, а его в конце сообщения не будет

Написал "... changelog в последней части поста"

**Comment by kitnerboy** [comment]
По changelog:
Уронили экран. Я уронил.
Был дождливый путч , который и определил будуший расклад помещения.
