### ISSUE TITLE
Ввести раздельный сбор мусора

### ISSUE THREAD

**Issue by NetBUG** [b4ck5p4c3/0x08.in#25]
Провести мероприятие по раздельному сбору: прочитать пару лекций, собрать круглый стол.
Целью мероприятия будет разработка схемы утилизации.
Необходимо составить описание мероприятия, пригласить докладчиков.

**Comment by glitchcore** [comment]
Ксюша хотела даже лекцию про это зачитать.
И Люба, я думаю, может подключиться

**Comment by sntxerror** [comment]
Предлагаю начать с небольшого ивента-воркшлпа на эту тему. В рамках него разработать схему утилизации

**Comment by sntxerror** [comment]
Добавил discuss, постановке задачи слишком обобщенная. В текущем виде выполнить невозможно.

**Comment by glitchcore** [comment]
Мне нравится идея про воркшоп, осталось найти, кто этим займется.

**Comment by glitchcore** [comment]
Обновил описание
/a

**Comment by LiebeLibelle** [comment]
Я, как минимум, могу рассказать про свой опыт раздельного сбора
