### ISSUE TITLE
Приостановить участие sasha__bau

### ISSUE THREAD

**Issue by AlBau** [b4ck5p4c3/0x08.in#250]
Приостанавливаю своё участие в B4CKSP4CE.
Меняю свой статус с "участник" на "гость".
Снимаю с себя все права и обязанности участника B4CKSP4CE (https://0x08.in/participants).

Отозвать:
1. доступ в СКУД

**Comment by sntxerror** [comment]
Убрал из СКУД. Спасибо за поддержку и участие! Будем ждать в гости)
