### ISSUE TITLE
HID-панель

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#256]
Для управления состоянием хакспейса, привязкой пропусков и прочим, @imcatwhocode предложил установить в тамбуре панель. Задачи:

- [ ] Протянуть в тамбур питание и ethernet
- [ ] Поставить в серверной БП и воткнуться в свитч
- [ ] Повесить панель
- [ ] Накатить на нее систему
- [ ] Написать софта (я думаю, хром в киоск режиме с прогрессивной вебстраницей — наш вариант)
- [ ] Что-то сделать с NFC (тут нужны комментарии @imcatwhocode)

**Comment by heeeyflo** [comment]
> нужны комментарии @imcatwhocode 

Here I am!

## Предисловие
Девайс, о котором идёт речь, это Synqera Slate (Simplate). Это детище образца 2013 года от одноимённого питерского стартапа. В итоге, нифига не выгорело особо и кроме коллаба с Улыбкой Радуги, как я понял, эти девайсы нигде не использовались.

## Характеристики
Внутри — какой-то i686 Atom (т.е., убунту на него уже не накатишь), 1Gb RAM, 16Gb mSATA SSD, камера, динамик, прикольный тачскрин (дюймов семь, наверное) и собсна NFC. 

Хоть местный Atom и кушает всего ничего, а на девайсине висит внушительный радиатор, вендор всё равно затроттлил проц до 800МГц (потолок у него 1.5ГГц). Намекнуть скейлеру что так делать не нужно, можно таким сниппетом:
```
echo 1 > /sys/module/processor/parameters/ignore_ppc
echo 1500000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 1500000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
```

**Warning:** хз чё как у этой железки с длительной работой на 1.5ГГц, может она в тыкву превращается через пару дней. Би кэрфул, короч!

## NFC — описание
А NFC-модуль у него не простой, а некая кастомная разработка терминала для эквайринга от Castles Technologies, для  I-Free (IP-адрес командного сервера в прошивке этого девайса тоже принадлежит этой конторе, видимо они были партнёром или акселлератором Синкверы).

Основная и SAM-платы выглядят примерно так:
![image](https://user-images.githubusercontent.com/1366386/87812393-c37b1980-c868-11ea-936a-9f12a1afb45a.png)

Отдельно ридер (NXP MFRC531):
![image](https://user-images.githubusercontent.com/1366386/87811560-86faee00-c867-11ea-8455-c384ccf7f670.png)

Всего там три платы:
1. Основная (IFREE-CL-1147A), с STM32 и MRFC531. Имеет три FPC-коннектора: UART к x86-плате, I2C (?) к SAM-плате, и последний на PCB-антенну.
2. SAM (IFREE-SAM-1147A). с интерфейсом-мультиплексором и тремя слотами для SAM-модулей
3. Плата с PCB-антенной и четырьмя светодиодами, для отображения статуса бесконтактной оплаты, судя по логотипам на корпусе

## NFC — рисёрч
Расшифровка тестпойнтов на основной плате:
```
SWD
DIO — TP4
CLK — TP5
NRST — TP8

Motherboard connector
Тест-пойнты TP27-TP23 последовательно соответствуют пинам на шлейфе, слева-направо.

TP27 — ?
TP26 — 3V3
TP25 — USART1_TX (PA9)
TP24 — USART1_RX (PA10)
TP23 — GND
```

USART 8N1 @ 115200 (емнип) bps, бинарный кастомный протокол, имплементация есть в .so-файле вместе с самим приложением на системном накопителе.

Модель самого МК я уже не помню, разве что, вроде бы, это была F4-серия, с включённой защитой от чтения.

**Comment by heeeyflo** [comment]
Собственно, моей идеей было выкинуть плату ридера, найти подходящий FPC-шлейф, развандалить его, припаять к PN532 и засунуть его внутрь корпуса. Всё получится мило-круто-аккуратно, да ещё и с поддержкой libnfc out of box.

**Comment by heeeyflo** [comment]
Задачу по разработке HW & SW для терминала взял на себя @p-hash. Последующие дискуссии касательно программного и аппаратного обеспечения конкретно терминала должны быть вынесены в отдельный репозиторий этого проекта.

В данном issue остаётся только обсуждение вопросов связанных с инфраструктурой (сеть, питание) и расположения (крепление) этого терминала. Возьму ответственность за это на себя.

**Comment by heeeyflo** [comment]
В первую очередь, хочу предложить закрепить этот терминал не в тамбуре (где тесно и неудобно), а на кухне. На первое время его даже можно будет просто положить на кухонный гарнитур, так как в этом положении им максимально удобно пользоваться.

**Comment by heeeyflo** [comment]
Вынесено в отдельный репозиторий [HMI](https://github.com/b4ck5p4c3/HMI) и [соответствующий проект](https://github.com/orgs/b4ck5p4c3/projects/3).
