### ISSUE TITLE
Туристический слет

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#264]
Хотелось бы поднять вопрос проведения туристического слёта участников и сочувствующих. Лето уже заканчивается, а дело так и не продвигается.
Встреча пройдёт частично/полностью в онлайн. 
Убедительная просьба подготовиться к встрече, проработать обозначенные вопросы. 
- Основной вопрос - место проведения. Нужно понять логистику заброса: нужна ли автомобильная доступность, готовы ли мы мириться с возникающей из-за этого потнециальной проблемой - возможностью нахождения на этом же месте другой группы, не разделяющих наши интересы. В случае отсутствия прямой автодоступности нужно понять, какая пешая удалённость будет приемлема для большинства участников.
- Определиться с тематикой мероприятия - будет ли это IT выезд на природу с ноутбуками, железками, либо же возврат к корням с костром, байками, песнями под гитару и пр.
- После понимания цели мероприятия определиться с тематическим снаряжением, его поиском и доставкой до места.
- Определиться с бытовым групповым снаряжением, его поиском и вопросами доставки.

**Comment by p-hash** [comment]
@elsidoi Слёт будет?

**Comment by kitnerboy** [comment]
Туристический слет был успешно проведен, хоть и в ограниченном количестве участников.
