### ISSUE TITLE
Принять Альберта Мухина в участники

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#267]
Альберт @Albert-Mmm хочет стать участником. Медиахудожник.
Он неоднократно был в хакспейсе, на МЭМ и делал проект с телевизором.
Я сам с ним работал и буду рад видеть его в числе участников.

Нужно выбрать ментора

**Comment by sntxerror** [comment]
Ментор Артём. Нужно чтобы он завел гитхаб.

**Comment by greenbastadb** [comment]
> Ментор Артём. Нужно чтобы он завел гитхаб.

Кому нужно?
Почему принятие новых участников завязано на третьи сервисы?

**Comment by glitchcore** [comment]
> Кому нужно?

«Ко второму посещению встречи ментор в issue рекомендует кандидата к принятию в участники.» — https://0x08.in/evaluation

> Почему принятие новых участников завязано на третьи сервисы?

Гитхаб является основным средством принятия решений (https://0x08.in/issue-rules.html)

**Comment by greenbastadb** [comment]
Как ментор не возражаю против принятия Альберта в участники.
