### ISSUE TITLE
Поддомены для сервисов и их список с описанием и мйэнтейнерами

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#268]
Предлагаю собрать список поднятых у нас сервисов, выделить их по смыслу в виртуальные машины если еще нет и выделить им осмысленные поддомены. Если нужно доступные извне и изнутри сети спэйса.

Итоговый список сервисов оформим в виде страницы, по примеру https://bitlair.nl/Services.

Например уже сейчас напрашиваются: mqtt, jitsi, acs, bots, vps, kvm.

Подход, похожий на bitlair позволит не потерять знания о том что из сервисов у нас есть/будет, и сведет всё в единообразную систему имен.

В текущем подходе внутри спэйса мы вынуждены помнить IP, и создавать proxy для доступа к некоторым VM. При этом никто достоверно не знает какие сервисы уже подняты, какие у них адреса и кто может помочь в них разобраться. В то же время доступ извне не тривиален.

**Comment by heeeyflo** [comment]
В целом, список доменов сейчас крайне невелик:
 - 0x08.in — основной сайт, Github Pages
 - local.0x08.in — заглушка, указывающая на адрес хакспейса 
 - meet.0x08.in — Jitsi
 - portainer.local.0x08.in — Portainer для деплоя небольших сервисов, вроде бота, пока в статусе обкатки, чтобы понять, подходит ли он нам
 - sentry.local.0x08.in — Sentry для сбора ошибок, но пока там пусто

Внутри менеджемент-подсети такие девайсы:
 - b4cksp4ce-gw.mgmt.local.0x08.in — Mikrotik hEX
 - sw01.mgmt.local.0x08.in — основной свитч
 - escape.mgmt.local.0x08.in — сетевой интерфейс управления ESXi
 - escape-idrac.mgmt.local.0x08.in — iDRAC основного сервера
 - unifi-controller.mgmt.local.0x08.in — ВМ с UniFi Controller
 - spaceap.mgmt.local.0x08.in — UniFi AP AC Pro в опен-спейсе
 - mgmt-gateway.mgmt.local.0x08.in — ВМ, гейтвей для прыжков в mgmt-сеть из локальной

В локальной сети есть:
 - corleone.local.0x08.in — Raspberry Pi с автоматизацией и СКУДом, через неё же мы сейчас прыгаем из интернета в локальную сеть
 - mgmt-gateway.local.0x08.in — см. **mgmt-gateway.mgmt.local.0x08.in**
 - harbour.local.0x08.in — ВМ, на которой раньше крутился бот, теперь там Docker Swarm + Portainer, в одном из сервисов которого теперь крутится бот
 - bksp-hwpc.local.0x08.in — десктоп в хардвейр-зоне
 - bksp-t420.local.0x08.in — задоначенный Thinkpad T420
 - rocinante.local.0x08.in — ВМ, @z4fd 
 - balancer.local.0x08.in — ВМ, _intended точка входа во внутреннюю сеть из интернета_, пока балансировщик для HTTP & HTTPS
 - jitsi.local.0x08.in — ВМ, Jitsi
 - sentry.local.0x08.in — ВМ, Sentry
 - xxxx.local.0x08.in для каждого устройства внутри локалки
 - xxxx.guest.local.0x08.in для каждого устройства, внутри гостевой сети (SP4CE)

Сейчас с этим несколько проблем:
1. Нет единой точки аутентификации (привет, IdP) для сервисов, чтобы ими полноценно пользоваться
2. Что внутри, что снаружи спейса, зоны *.local.0x08.in & *.mgmt.local.0x08.in резолвятся на local.0x08.in и попадают на балансировщик. Это не всегда ожидаемое поведение (например, находясь в сети спейса, я хочу подключится по RDP/VNC к bksp-hwpc.local.0x08.in, но он вместо локального 10.0.2.1337, резолвит меня на внешний адрес спейса, на котором, очевидно, никакого VNC не заэкспоужено). Для решения этой проблемы, придётся либо выделять какую-то отдельную зону, типа lo.0x08.in (lo — loopback), либо идти на какие-то дикие ухищрения.

**Comment by heeeyflo** [comment]
В связи с большим количеством инфраструктурных изменений, происходящих прямо сейчас, эта issue становится нерелевантной.
