### ISSUE TITLE
Вывоз ламп

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#27]
Собственники предлагают вывезти лампы, если LED панели будут оставлены как неотделимое улучшение.
Соглашаемся?

**Comment by dm-shi** [comment]
Да

**Comment by sntxerror** [comment]
Да

**Comment by kaero** [comment]
Да

**Comment by kaero** [comment]
Напомню, что лампы заменены не в счёт спейса, а за мой личный, так что считаю, что моего согласия достаточно.

**Comment by glitchcore** [comment]
> Напомню, что лампы заменены не в счёт спейса, а за мой личный, так что считаю, что моего согласия достаточно.

ок, тогда пишу что мы согласны. Я бы предложил рассмотреть записать расходы в счет спейса, но это по твоему усмотрению.
