### ISSUE TITLE
Встреча 18-08-2020

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#271]
-  Апрувы для пулл реквестов @sntxerror

**Comment by heeeyflo** [comment]
- Поездка на природу в эти выходные (#264)
 - @sntxerror & @imcatwhocode про инфраструктуру, платежи и переход на Gatsby

**Comment by glitchcore** [comment]
Добавить в бота функционал рассылки уведомлений о PR/issue
