### ISSUE TITLE
Поднять discourse на поддомене

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#278]
По итогу #275 решено пробовать использовать https://github.com/discourse/discourse

Необходимо понять что для этого потребуется (виртуалка/swarm) и какие тонкости важно учесть. Надеюсь на помощь @imcatwhocode 

В качестве названия поддомена предлагаю moot.0x08.in. В переводе с английского to moot - обсуждать, спорить, собираться. Появляется созвучие с имеющимся поддоменном meet.0x08.in.

https://en.wikipedia.org/wiki/Moot

**Comment by heeeyflo** [comment]
Ишью в процессе, я пока вожусь с фундаментальными.. кхм.. особенностями NFS для организации персистентного хралища, надеюсь, что закончу с ним сегодня и успею нормально завести Traefik для работы позади Nginx.

**Comment by heeeyflo** [comment]
Апдейт от 9/14: поднял Traefik за nginx, накатал стеки для него и Spacebot, однако деплой пришлось отложить из-за дебага оверлейных сетей (как оказалось, дефолтное адресное пространство Swarm отличается от standalone Docker, и накладывается на часть адресного пространства основной сети спейса). 

Заодно начал писать инструкцию по деплою хакспейса из коробки. Думаю что завтра закончу с ботом, Traefik и инструкцией, возможно успею ещё зацепить форум.

**Comment by heeeyflo** [comment]
Дублирует #275 по смыслу.
