### ISSUE TITLE
Диммер в общее пространство

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#284]
В общем пространстве слишком квантованная освещенность, по вечерам народ сидит при свете красной лампы, а включать свет как будто очень ярко.

Я хочу объединить обе линии освещения (у экрана и у окна) и поставить диммер.

Нужно понять, диммируются ли наши лампы. Если нет — можно ШИМ-регуляторов повкорячить на каждую лампу и устроить модбас-пати.

**Comment by glitchcore** [comment]
Попробовали поставить диммер, не прокатило. Думаем диммировать после БП на каждой лампе отдельно

**Comment by frogsandsocks** [comment]
Предполагаю, что проблема не в ярком свете, а в холодном. Если сделать свет темнее, то мы просто будем сидеть под холодным, но ещё и тусклым, что будет скорее вдвойне неприятно. 

Холодный свет неплохой, просто для работы, а не для посиделок

**Comment by p-hash** [comment]
Говорят там @greenbastadb что-то сделал хорошее: повесил лампу над рабочей зоной

**Comment by glitchcore** [comment]
Так и есть, светодиодная лента во многом зарешала проблему с освещением.
