### ISSUE TITLE
Освещение в аквариуме

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#285]
Хочу попробовать сделать автоматическое освещение в аквариуме и соответственно проверить, насколько человек-со-стороны может разобраться в нашем СКУДе

**Comment by heeeyflo** [comment]
@glitchcore посмотри, пожалуйста, #287.

**Comment by heeeyflo** [comment]
@glitchcore какой сценарий автоматизации ты видел для освещения в аквариуме?

**Comment by glitchcore** [comment]
1. Режим холодильника с задержкой: при открытии любой из двух дверей аквариума свет включается, после закрытия всех дверей свет горит еще порядка 10-15 минут.
2. Индикация срабатывания пропуска — открытие замка валидной карточкой аналогично включает свет.
