### ISSUE TITLE
Перевести ядро автоматизации на Node-RED

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#287]
Собственно, сабж. 

Текущее ядро автоматизации значительно усложняет введение новых сценариев тем, что их приходится писать прямо кодом — это нифига не наглядно и не удобно, а асинхронные сценарии (с таймерами, задержками, етц) превращают код в подобие лапши. 

Вместо того, чтобы дальше мейнтейнить своё решение, я предлагаю полностью перевести автоматику на Node-RED, который стал отраслевым стандартом для такого. Можно будет пилить красивые графы, потом экспортировать их в JSON и сохранять в репозитории, получится почти-что нормальный Git-ops.

Мелкие шажки к переносу логики автоматизации я уже делал у себя в докере на ноуте, могу экспортнуть и заделиться графами которые у меня получились.

**Comment by glitchcore** [comment]
Оке, я посмотрю как это все

**Comment by a-andreyev** [comment]
Я щупал когда-то Node-RED, но не слышал насчёт широкого внедрения в производства. Насколько я понимаю, он скорее воспринимается как [удобный инструмент для прототипирования](https://discourse.nodered.org/t/would-you-use-node-red-in-a-production-environment-for-iot-industry-applications/19358).
В любом случае, попробовать кажется хорошей идеей. Надеюсь, экспорт в JSON действительно позволит не утонуть в лапше не из кода, а из gui-схемок :) Рад буду помочь чем смогу.

**Comment by heeeyflo** [comment]
Готово, [чек ит аут](https://github.com/b4ck5p4c3/acs-automation)!

**Comment by glitchcore** [comment]
Получил досутп, вроде работает, каеф

**Comment by heeeyflo** [comment]
> Получил досутп, вроде работает, каеф

Омичи ломают нам дверь, алярм!
