### ISSUE TITLE
Сделать резервный ограничитель импульса для двери

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#288]
Сейчас соленоид двери напрямую подключен к IO на главном контроллере. Проблема в том, что длительность импульса, выдаваемого на соленоид в замке никак не ограничивается ни физически, ни в прошивке контроллера.

Фактически, логика автоматизации на RPi только подаёт команду на установку высокого уровня на вывод к соленоиду. При этом, systemd-служба запускает шелл-скрипт, который каждую секунду отправляет команду на установку низкого уровня.

Чтобы как-то решить эту проблему, изначально задумывалось сделать отдельный hardware генератор импульсов, подключаемый к выходу endpoint_pp и лимитирующий продолжительность импульса, если вдруг на контроллер своевременно не выдаётся команда на установку низкого уровня.

**Comment by heeeyflo** [comment]
Призываю @glitchcore. 
Возможно это можно будет сделать софтверно? Например, выделить часть адресного пространства holding registers для задания задержки изменения состояния, а другую часть адресного пространства койлов использовать под выходы с задержкой изменения состояния.

Например:
```
# Имейджин, регистр 44444 отвечает за задержку изменения состояния IO4 в миллисекундах
modbus.write(44444, 1000)

# А регистр 04444 отвечает за задание состояния IO4, которое должно измениться через время, указанное в 44444
modbus.write(04444, 1)
```

Эндпойнт, обрабатывая запись по адресу 44444, сохраняет величину задержки для IO4 в памяти / пишет в флеш. 

В момент записи по адресу 4444, он применяет к IO4 состояние из принятого пакета и ставит таску / заводит таймер на инвертирование этого состояния через время, принятое и сохраненное в пакете из записи в 44444.

**Comment by lomalkin** [comment]
Аппаратно будет гораздо надежнее и безопаснее, имхо.

**Comment by glitchcore** [comment]
> Возможно это можно будет сделать софтверно?

Да, давайте напилим, тоже думал об этом

**Comment by glitchcore** [comment]
> Аппаратно будет гораздо надежнее и безопаснее, имхо.

Я думаю, оверинжиниринг, даже в случае зависания контроллера сработает WD и отключит выход, а риски связанные с какими-то ошибками в софте я считаю не выше чем риски того, что сломается какая-то еще часть нашей системы.
