### ISSUE TITLE
Большая встреча участников 15-09-2020

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#289]
Обсудим видение, планы, идеи развития спейса от @sntxerror. Поделимся наболевшим, пройдемся по issues и если останутся силы - обсудим свежие анонсы от одной яблочной компании.

**Comment by z4fd** [comment]
- Анонсы плана встреч за сутки до самой встречи

**Comment by glitchcore** [comment]
@sntxerror выложит планы
