### ISSUE TITLE
Шеймить Фила 2 дня

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#29]
Он форспушит ветки!
пруф: https://github.com/b4ck5p4c3/wiki/pull/16

**Comment by glitchcore** [comment]
Он еще и мой коммит заамендил!!!11

**Comment by sntxerror** [comment]
@kaero так нельзя

/a

**Comment by sntxerror** [comment]
Фил эшэймд

/а

**Comment by glitchcore** [comment]
Зачем ты ставишь /a, это не дискуссия

**Comment by kaero** [comment]
/b/ применимо ко всем обсуждениям в интернете

**Comment by glitchcore** [comment]
> /a применимо ко всем типам issue

А какой смысл в этом, если таймера нет и никакое решение не обсуждается?

**Comment by lomalkin** [comment]
Я думал, issue нужны, чтобы в чатах не было флуда, ан нет.
