### ISSUE TITLE
Медиасервер в опенспейсе

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#290]
У нас есть задоначенный компьютер в корпусе [DNK-H](https://3dnews.ru/931675), NJ3700/Intel HD Graphics/4GB Ram/1TB HDD. Хочется сделать из него kind of медиасервер для следующих задач:

* крутить музыку с yandex music/soundcloud/YT
* запускать видосики с YT
* запускать на нем произвольный контент (видео/аудио)
* стримить на него изображение
* запускать созвоны с jitsi

Соответственно план примерно такой:

- [x] Поставить на него линуксы
- [ ] Запилить API/Бота для управления типичными стриминговыми сервисами (@algroznykh делал для включения soma.fm)
- [ ] Научиться на нем удаленно запускать VLC, браузер с JITSI, какой-нибудь стриминг экрана
- [ ] Подключить к нему нормальную камеру
- [ ] Подключить к нему пару норм микрофонов
- [ ] Мб даже поставить туда OBS для мультиплексирования видео на созвонах и стримах

## Алсо я давно думаю про мультиплексирование звука

Хочется добавить HDMI-экстрактор, чтобы из него доставать звук, пробросить над столом свободный jack-конец.
Получается несколько источников: BT, HDMI sink, медиасервер, свободный jack-хвост. Поставить микшер или коммутатор для вывода звука на колонки.
А еще можно сделать удаленное управление кнопкой на BT-адаптере, чтобы можно было написать в бота/API команду и привязать свой девайс.

**Comment by glitchcore** [comment]
Пишите, мб мои концепции говно и можно более лучше сделать

**Comment by sntxerror** [comment]
идея хорошая, в компе сколько видеовыходов? у нас ведь еще будет телик напротив экрана,

**Comment by glitchcore** [comment]
Тоже думал про телик. Выходы HDMI + VGA. Мб стоит взять четвертую малину, у нее два выхода. Ну или пока сделать на нем, а потом перенести все на другой комп помощнее не проблема будет.

**Comment by glitchcore** [comment]
@z4fd предложил https://github.com/ytdl-org/youtube-dl

**Comment by p-hash** [comment]
kodi может крутить youtube и кажется soundcloud. Проблемы будут со стримингом экрана и с jitsi

**Comment by glitchcore** [comment]
Для яндекс-музыки есть плагин под kodi. Другой вопрос, может ли kodi управляться удаленно — с вебстраницы или из бота? Я хочу сидя в опенспейсе со своего ноута или телефона рулить  громкостью или контентом

**Comment by p-hash** [comment]
может: есть rpc, есть андроид приложение kore (kodi remote), есть веб-интерфейс

https://kodi.wiki/view/JSON-RPC_API

**Comment by kitnerboy** [comment]
Кто-то находил варианты запуска Miracast на ПК? Такой вариант был бы очень удобен для доставки контента с мобильников.

**Comment by glitchcore** [comment]
Для запуска трансляции можно юзать хромиум в режиме киоска
`chromium --noerrdialogs --kiosk "https://meet.0x08.in/b4cksp4ce_everytime"`

**Comment by glitchcore** [comment]
Потыкал kodi, у него есть веб-интерфейс и прочие рюшечки, и поддержка горы стандартов, так что я бы смирился с тем что эта херня выглядит как ~~булшит~~ медиацентр.

Так что пока план у меня такой:

1. Kodi в автозапуске для музыки и видео
2. Remote desktop для кастомного контента
