### ISSUE TITLE
Покраска стены на кухне

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#300]
Хватит это терпеть ! Поступило предложение, покрасить размурованную стену на кухне (https://t.me/b4cksp4ce_l1ve/159)

Как я вижу:
- надо загрунтовать 
- выбрать цвет и покрасить

Предложения, дополнения и пр. жду в комментариях :)

**Comment by algroznykh** [comment]
загрунтовать и покрасить в красный.
/a

**Comment by heeeyflo** [comment]
Загрунтовать, покрасить в белый/чёрный/красный/бело-красный, запилить вывеску неоном/эл-вайром и поставить пару красных Лёниных полок с каким-нибудь visual attractive стаффом.

Что-то похожее на [это](https://www.instagram.com/p/CGt3qPhFADx/).

**Comment by frogsandsocks** [comment]
Я предлагаю сделать какой-нибудь минималистичный орнамент, вроде такого:

![IMG_7092](https://user-images.githubusercontent.com/32378601/97339857-23d01d00-1894-11eb-9eb3-c75a86b46bfa.JPG)

**Comment by sntxerror** [comment]
Итоговое предложение

- разобрать перпендикулярную стену
- загрутновать обе стены
- покрастить обе стены в нейтральные цвета черный и белый
- предложить участникам выбрать сегменты и украсить по своему усмотрению для самовыражения

**Comment by kitnerboy** [comment]
Интересно, что мы не можем принять это решение по обычному workflow, так как мнение по этому вопросу нельзя никак аргументировать, опираясь на принципы сообщества.
У нас спор о вкусах, который непонятно как решать.

Я против предложения разбирать что-то ещё, потому как до сих пор нет никакого понимания, что хочется сделать. У каждого своё предложение, которые никто не обсуждает.

**Comment by van2048** [comment]
Я предлагаю сделать что-то такое:
- убрать гипсокартон с обоих стенок в прихожей
- закрепить потолок
- расшить швы, зашпаклевать отверстия
- нанести рисунок (можно пиксельный, где пиксели - отдельные кирпичи)
- покрыть лаком

Не так долго и дорого, однако стена станет функциональна - на нее можно будет вешать разные штуки. Ну и будет нормально выглядеть

**Comment by kitnerboy** [comment]
Я снимаю все письменные и устные запреты на изменения в области кухни, если я вообще имел право на подобные запреты.
Если есть заинтересованные лица и виденье концепции у них - делайте как посчитаете нужным. Но решение по этим стенам принималось без предварительного оповещения участников, и следует либо правила под это подправить, либо признать, что мы их нарушаем.
По факту мы форсируем принятие решение под давлением эмоций, и как это будет эксплуатироваться дальше - неизвестно.

**Comment by sntxerror** [comment]
Итого:
>     * разобрать перпендикулярную стену
>     * загрутновать обе стены
>     * покрастить обе стены в нейтральные цвета черный и белый
>     * предложить участникам выбрать сегменты и украсить по своему усмотрению для самовыражения
