### ISSUE TITLE
Еженедельная встреча участников 27.10.2020

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#305]
- the стена за #300 
- А что там с ботом ?
- Еще раз про сайт

**Comment by heeeyflo** [comment]
1. @sntxerror про легализацию хакспейса.

2. Про планы на кухню.

3. Гараж

**Comment by sntxerror** [comment]
> А что там с ботом ?

занимаются @imcatwhocode и @sntxerror

**Comment by sntxerror** [comment]
Планы на кухню:
- починить стены
- поставить шкаф на подиум
- убрать большую батарею
- установить маленькую батаерю
- сврить каркас барной стойки
- вырезать столешницу барной стойки
- провести воду и поставить раковину в гарнитуре

**Comment by sntxerror** [comment]
Про гараж:
- смотрим, думаем, ищем варианты, приглядываемся
- надо сделать опрос в чате участников о том кто готов поддержать гараж финансово
