### ISSUE TITLE
rc3

### ISSUE THREAD

**Issue by algroznykh** [b4ck5p4c3/0x08.in#307]
https://events.ccc.de/2020/10/17/rc3_call_for_assemblies/#english

> We activated our registration where we ask you a couple of important questions for the development of rC3. Please sign up at signup.c3assemblies.de until November 8, 2020 so we know you’ll be a part of the experience and we can estimate capacities.

**Comment by sntxerror** [comment]
что нужно сделать?

**Comment by algroznykh** [comment]
https://signup.c3assemblies.de/assembly/3555fc37-9b56-4c92-910a-619051d46764
