### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#31]
План действий на ближайшее время:

1. Принять метаправила про задачи, обсуждения и PR ( #30 ) — без этого, кажется, не сдвинемся вообще. (OK)
2. Создать задачи, распределить людей и описать все события, которые у нас происходили, написать пост — это технический долг, считаю, что его нужно закрыть как можно раньше (IN PROGRESS)
3. Выложить принципы, о которых мы говорили на презентации (создать задачу, назначить человека, создать его силами PR, принять) (OK)
4. Обсудить про финансы (Платформа для приема взносов #22 (OK), Публикация финансов #7 (OK)), написать отдельную страницу с правилами про финансы
5. Обсудить дальнейший roadmap.

**Comment by sntxerror** [comment]
Сегодня я был гостем в подкасте Фронтенд Юность, выпуске многое было посвящено нам. Можно ожидать некий рост интереса к проекту. Считаю что необходимо к его выходу (7-10 ноября) иметь прозрачную и понятную схему принятия участия как делом так и средством. В этой связи пункты 3 и4 из постановки считаю критичными. Предлагаю назначить им дедлйн 7 дней.

**Comment by glitchcore** [comment]
Нужно ли менять последовательность? Мне кажется нет, т.к. по моим оценкам все эти пункты можно за 3-4 дня сделать

**Comment by kaero** [comment]
Так как на все пункты заведены issue и все в работе, ничего не подвешено в воздухе, то предлагаю его закрыть, так как он кажется бессмысленным.

/a

**Comment by glitchcore** [comment]
Я предлагаю закрыть его в тот момент, когда все пункты будут завершены, а то будут таски-зомби

**Comment by kaero** [comment]
> Я предлагаю закрыть его в тот момент, когда все пункты будут завершены, а то будут таски-зомби

Что мешает этой таске быть зомби вместе с ними?

**Comment by glitchcore** [comment]
Это родитель.
Всегда можно посмотреть на роадмап и вспомнить, что мы запланировали сделать

**Comment by glitchcore** [comment]
Считаю таску устаревшей
/d
