### ISSUE TITLE
Приделывание лазера к ЧПУ.

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#312]
Имеется ЧПУ станок с фрезой. Также отдельно есть лазерный модуль.
Нужно спроектировать с распечатать деталь, которая будет держать лазер на подвижной голове ЧПУ.
Также нужно разобраться с управление лазером, чтобы из G-Code можно было его включать и резать всякие тонкие материалы/гравировать всякое.
Разобраться с фокусом лазера, его там вроде как ловить надо грамотно.

**Важно** перед началом тестирования лазера обзавестись очками для защиты важных смотрительных органов участников и гостей. Выяснить длину волны имеющегося лазера, найти в продаже защитные очки и убедиться, что они действительно 100% безопасны.

**Comment by glitchcore** [comment]
Очки (зеленые) были в комплекте, я пробовал через них смотреть на лазер и не получал неприятных ощущений.

По поводу управления — вроде лазер подключается вместо шпинделя и управляется через M03/05 c указанием скважности вместо скорости (нужно проверять и определять диапазон управления).

Еще один важный момент: нужно сдувать дым/пар от лазера (условным вентилятором, который дует в область реза) + обязательно добавлять короб и вентиляцию

**Comment by glitchcore** [comment]
Фокус вроде настраивается просто поворотом настроечного кольца, думаю, это придется делать руками на горячую (или предусматривать процедуру калибровки)
