### ISSUE TITLE
Обеспечение безопасности помещения

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#315]
Необзодимо купить и установить ASAP%

- пожарные датчики 
- блокиратор вилки электрической для токарного станка
- видеорегистратор для токарного станка

После установки:
- повесить в помещениях планы выхода
- заключить договор на пульт пожарки с УК

**Comment by glitchcore** [comment]
Хочется услышать основания для критичности именно этих мер. Если пожарка давно горит (азаза), то с токарним станком менее понятно: почему именно токарный станок, в спейсе хватает травмоопасного оборудования (прилететь и от дремеля может, а паяльник умеет гореть) и почему именно такие меры (например, что такое блокиратор вилки)?

**Comment by sntxerror** [comment]
#168

**Comment by sntxerror** [comment]
Арендатор несет ответсвенность за многое происходящее в нанятом помещении.

Меры призваны снизить риски для арендатора и людей приходящих в спейс.

**Comment by elsidoi** [comment]
@sntxerror укажи пожалуйста требования к пожарным датчикам.
На прошедней встрече мы выяснили, что никто не знает, какие датчики нужно брать, потому хотелось бы понять, каким требованиям они должны соответствовать.
На встрече было произнесено "Чтобы в случае пожара они сработали", но я не уверен, как мы можем проверить подобное без повреждения спейса. Может есть какие-то ещё критерии, на которые стоит опираться при выборе?

**Comment by heeeyflo** [comment]
Камера в аквариуме успешно пишется вот уже два месяца, посему можно считать связку IP-камера + Kerberos.io достаточно надёжной.

Постараюсь на этих выходных смонтировать камеру над станком и завести запись с неё.

**Comment by glitchcore** [comment]
1. Опасность токарного станка считаю переоцененной — риски повреждения участников для себя как арендатора вижу не выше рисков повреждений от всего остального инструмента.
2. Пожарка обсуждается в #168
