### ISSUE TITLE
Soldering Internals

### ISSUE THREAD

**Issue by kitnerboy** [b4ck5p4c3/0x08.in#316]
Название обсуждаемо, каждый может проявить свою креативность.

Уже не первый раз поднимается вопрос о проведении  внутреннего секретного Soldering Buddies для элитного круга участников нашего хакерспейса.
Это обусловленно тем, что изначально Soldering Buddies был задуман как мероприятие, которое позволит интересующимся прийти к нам и не чувствовать себя неловко при отсутствии каких-либо задач. Именно поэтому я скептически смотрел на возможность вписки в эвент участников спейса. Скептировал и не вписывал.

Но раз есть запрос, нужно его закрывать.
Отсюда прошу вызваться организатора этого мероприятия, который возьмёт на себя заказ и доставку наборов для пайки, утверждение даты эвента, сбор списка участников и утверждение даты.
Я поддержу полностью советами по закупу и техническим момента, но в ближайшее время не хочу заниматься организаторством вне официального SB - малость устал. 
Также я с удовольствием проведу инструктаж и буду помогать в процессе мероприятия как ментор.

**Comment by kitnerboy** [comment]
В принципе бываю в районе Roboshop, так что и заказом могу заняться, и доставкой.
Вы только соберитесь.

**Comment by glitchcore** [comment]
Переехало во внутренние Issues
