### ISSUE TITLE
Робот-пылесос

### ISSUE THREAD

**Issue by van2048** [b4ck5p4c3/0x08.in#317]
Есть предложение собрать DIY, либо купить на авито с возможностью тюнинга робот-пылесос. Так как сменная обувь не прижилась а робот-пылесос позволит оставить чистыми полы от песка и прочих мелких фракций, занесенных с улицы

**Comment by van2048** [comment]
Было предложение от @imcatwhocode взять iRobot Roomba, так как к нему есть описание
https://www.usna.edu/Users/weaprcon/esposito/_files/roomba.matlab/Roomba_SCI.pdf
https://www.irobot.lv/uploaded_files/File/iRobot_Roomba_500_Open_Interface_Spec.pdf

**Comment by glitchcore** [comment]
Пылесос появился, пробуем пользоваться.
