### ISSUE TITLE
Закрыть красный чат

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#32]
Само его существование провоцирует дискуссии в нем, которые не удается удерживать конструктивными. 

Предлагаю закрыть чат. Не смог придумать, какие уникальные функции он сейчас выполняет.

**Comment by glitchcore** [comment]
Мне тоже пришла эта мысль вчера, когда я увидел 160+ сообщений и отправил его в архив.
Возможно, этот чат может быть местом реакции на какие-то очень срочные вопросы которые не являются публичными, но кажется можно решить их и в личке.

/a

**Comment by sntxerror** [comment]
Как будут обсуждаться вопросы публикации постов от лица места? Это зачастую приватные обсуждения.

**Comment by kaero** [comment]
> Как будут обсуждаться вопросы публикации постов от лица места? Это зачастую приватные обсуждения.

Есть ли причины, чтобы они были приватными? Для всех приватных обсуждений можно использовать security issues или командные обсуждения -- и те и другие доступны только команде.

**Comment by glitchcore** [comment]
Мне тоже кажется, что обсуждать посты можно публично, если уж там будет какая-то чувствительная информация, можно решить вопрос лично или в командном обсуждении

**Comment by sntxerror** [comment]
Координация текстов постов в публичном чате участников это слишком. Помимо того что они увидят это в канале и в общем чате они еще будут видеть как мы правим текст короче это полная хрень. Тексты постов порой могут содержать то, что нельзя публиковать раньше определенного срока, или то, о чем хочется говорить эсклюзивно.

> командном обсуждении

Раньше мы согласовывали посты в красном **командном** чате. Сейчас нам необходим новый **командный** инструмент для согласования постов, доступ к нему должен быть ограничен, чтобы согласовывать посты только с участниками **команды/редакции**. До наличия такого инструмента закрывать красный чат нельзя.

Все остальное я поддерживаю. Красный чат избыточен и опасен)

**Comment by glitchcore** [comment]
> они еще будут видеть как мы правим текст короче это полная хрень

да, представляешь, мы настоящие и можем ошибиться, а еще мы прямо сейчас обсуждаем публично много инфы, которую раньше обсуждали персонально, и никто пока не умер.

> то, что нельзя публиковать раньше определенного срока

мне видится в этом потребительское отношение со стороны «админов», типа — вот, мы подвезли вам контента.

Командное обсуждение — я буквально об обсуждениях внутри гитхаба внутри команды.
Координировать тексты в публичном чате я и не собирался ни в каком из сценариев

**Comment by sntxerror** [comment]
> Командное обсуждение — я буквально об обсуждениях внутри гитхаба внутри команды.

Кулдаун в сутки звучит не очень оперативно. К тому же не все всегда доступны в гитхабе настолько чтобы быстро согласовать срочный пост.

Плюс ко всему ты упустил два важных момента из моих слов: 

- контент может быть эксклюзивный (тот который не хочется публиковать вообще где то ещё)
- контен может быть привязан ко времени (тот который не хочется публиковать нигде раньше определённого срока)

Это означает необходимость приватного согласования текстов постов.

Я предлагаю сформировать редакцию. В редакцию войдут те, кто хочет согласовывать тексты постов. В рамках этой редакции я предлагаю согласовывать тексты постов инструментом удобным для редакции. Тоесть функцию Public Relations вести в *приватном командном* месте.

Например красный чат может быть переименован в редакционный и использоваться только с этой целью.

**Comment by sntxerror** [comment]
Я против того чтобы посты в канал подготавливались публично. Канал в этом случае теряет смысл.

Потребительского отношения здесь нет. Это все служит цели повыешия качества постов.

**Comment by glitchcore** [comment]
Короче проблема, кажется, шире чем просто закрытие чата.

Еще раз скажу, что мне не кажется правильной практикой выпуск «эксклюзивного контента» в канале и необходимости скрывать информацию от читателей я не вижу.

Приведи пример такого эксклюзива?

Считаю, что важнейшая задача канала — доносить информацию до людей, которые не хотят/не могут из других источников её получать.

**Comment by kaero** [comment]
И я снова и снова не понимаю: инструмента приватных осуждений никто не отнимает, их целых два в гитхабе, они были перечислены выше. Предлагается перестать использовать чат. Для редактирования постов группового так вообще лучше гугл-документ или другое реалтайм средство командного редактирования текста. Доступ к нему можно ограничить, а ишью держать открытым или закрытым.

**Comment by kaero** [comment]
> Потребительского отношения здесь нет. Это все служит цели повыешия качества постов.

Как ограничение количества возможных обсуждающих и вкладывающих в контент повышает его качество? В таком случае единолично написанные посты должны быть лучше, чем обсужденные хоть с кем-то.

**Comment by glitchcore** [comment]
Закрываю Issue, прошло 24 часа, не договорились.

**Comment by glitchcore** [comment]
@kaero  меня поправил, что вроде против не было аргументов, так что да, закрываем чат.

Про правила публикации и пайплайн публикации постов предлагаю завести отдельный PR, возможно @sntxerror  готов этим заняться?

**Comment by sntxerror** [comment]
Просто мой аргумент заигнорили) Ну окей, чат закрыт.

**Comment by glitchcore** [comment]
Погоди, твои аргументы были про обсуждение постов. Я их не заигнорил, просто считаю, что это не имеет отношения к закрытию чата и стоит обсудить отдельно (как вариант может и правда создать редакторский чат, если придем к этому).

Либо я и правда упустил какой-то аргумент, тогда напомни.

**Comment by kaero** [comment]
> Просто мой аргумент заигнорили) Ну окей, чат закрыт.

1. Ты нигде не оставил `/d`.
2 Все твои аргументы против публичного обсуждения постов, а не закрытия, в треде я уже дважды указал на то, что и чат не является лучшим местом для их редактуры и обсуждения, и предложил другой инструмент, а также указал на другие возможности дискуссий с ограниченным кругом участников. Опровержений не поступало.
