### ISSUE TITLE
Претенденты на роль арендатора

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#321]
Продумываю сценарий выхода из роли арендатора помещения. Хочу понять кто из участников или резидентов готов взять на себя эту роль в случае моего перехода в ранг простых участников.

Отпишитесь ниже, если вы готовы в недалеком будущем взять на себя следующие обязательства:

- подписание и исполнение условий договора аренды
- прием платежей

**Comment by glitchcore** [comment]
Готов заняться приемом платежей.
Не готов взять на себя роль арендатора в силу своей удаленности.

**Comment by algroznykh** [comment]
готов быть арендатором.

**Comment by van2048** [comment]
я подмал и решил что тоже готов быть арендатором

**Comment by sntxerror** [comment]
Спасибо за отклик! Буду иметь в виду, если возникнет потребность. Пока что мне стало спокойнее что на случай необходимости есть претенденты.
