### ISSUE TITLE
Вишлист

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#33]
Issue #12 и #11 создавались как пункты вишлиста — чтобы кто-то, у кого она вдруг есть, мог бы задонатить, например.
Хотел обсудить, в каком виде вести вишлист. Можно создать страницу на вики и все, что необходимо и все что предлагают — принимать туда как PR

**Comment by kaero** [comment]
Поддерживаю страницу на вики -- это заодно позволит обсуждать пункты вишлиста.

**Comment by sntxerror** [comment]
То что нам предлагают и то что нам нужно это  разные сущности. Вишлист подразумевался мной как публичный список точно необходимых нам материалов, инструментов и устройств)

В финском хакспейсе есть отличный гайд на тему что хорошо приносить что плохо. Предлагаю его локализовать под наши реалии. Это нужно помимо вишлиста.

**Comment by glitchcore** [comment]
Согласен, предложения можно принимать в виде issues.
Идею про локализацию гайда концептуально поддерживаю, но сам гайд еще не читал

**Comment by glitchcore** [comment]
Влил PR #39 обсуждение завершаю.
