### ISSUE TITLE
Установка кухонного гарнитура

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#332]
1. Выпиливаем боковую стенку
![image](https://user-images.githubusercontent.com/12886640/101247742-432c5680-372c-11eb-8b1c-8ccf201e89fb.png)

2. Выпиливаем середину из дна, выпиливаем внутренние стенки, ставим в правую тумбу полку (розовая)
![image](https://user-images.githubusercontent.com/12886640/101247766-5e976180-372c-11eb-8d53-a18179390518.png)

3. В средней тумбе уже есть полка на нужном уровне
4. В левой тумбе убираем полку

![image](https://user-images.githubusercontent.com/12886640/101247800-7cfd5d00-372c-11eb-974b-80d1ddc9cebd.png)

5. Делаем вырез под сантехнику и трубы
![image](https://user-images.githubusercontent.com/12886640/101247818-8edf0000-372c-11eb-8e91-774d0b5a9c8e.png)

**Comment by glitchcore** [comment]
Еще нужно поднять на 1-2 см полку в центральной тумбе

**Comment by glitchcore** [comment]
Резонное замечание про то, что раковина вообще-то справа задумывалась.
Сантехника туда дотянется

**Comment by glitchcore** [comment]
Так что полку не переносим, остальное вроде в силе

**Comment by sntxerror** [comment]
На последнем снимке зеленым помимо места под трубы есть высокая ниша. Чем обсуловлена такая большая высота? Насколько помню мы можем позволить себе разместить трубы отвода от подвода воды заметно ниже

**Comment by glitchcore** [comment]
Высота канализационной трубы порядка 60 см от пола, высота шкафа — 82 см

**Comment by sntxerror** [comment]
> Высота канализационной трубы порядка 60 см от пола, высота шкафа — 82 см

тоесть ниже уже совсем никак? насколько помню еще будет уклон, тоесть справа высота будет выше чем слева

**Comment by glitchcore** [comment]
нет, никак

**Comment by sntxerror** [comment]
Вот здесь есть вполне подробный гайд: https://www.ikea.com/ru/ru/files/pdf/49/fc/49fc9ec3/planning_guide_web.pdf

Назначения для кухни у нас заметно проще, в основном предполагается только мытьё и хранение. Приготовление в нашем случае это просто разогрев в микровоновке. Максимум – собрать бутерброд. Выделенная зона под полноценную готовку не критична. Ключевая активность на мой взгляд - мытьё.

Исходя из эргономики мытья посуды, для моющего взрослого нужно место шириной примерно 80 см, из которых примерно 20см это отступы по бокам, для свободы движения локтей и около 40 см - сама раковина.

Если я правилно помню размер  нашем случае, при боковом отступе хотя бы 20см, мы вынуждены ставить раковину в средний шкаф. Вариантов размещения вижу пожалуй два:

1. Немного забить на эргономику и отступы, чтобы оставить больше полезной свободной поверхности и поставить небольшую мойку с чашей ~30 см в самый правый шкаф. 
2. Исходя из эргономики поставить раковину в средний шкаф, ближе к правой или левой его части.

Мойку предполагаю лучше устанавливать хотя бы с небольшим крылом (от 10см). Считаю что важно чтобы это была именно врезная мойка, для которой не нужно демонтировать столешницу над шкафом. Но можно обдумать варианты с цельной мойкой, заменяющей столешницу. 

Посуду и приборы считаю что следует размещать в ящиках и на рейлах на стене. Вероятно стоит принять за правило как модно более чистую и пустую столешницу, то есть оставлять минимум предметов для комфортного использования участниками под разогрев еды, наливание напитков.

Микроволновку имеет смысл закрепить на стене, над чистой плоскостью столешницы, в нашем случае в самой левой её части, с небольшим отступом (~5см) для открывания дверцы. Чайник предполагается держать на столешнице.

Поскольку эта техника размещена в левой части - имеет смысл понять как подвести розетку на 3-4 прибора (СВЧ, чайник, + 2 для временных приборов). Например, подвести можно из той розетки что раньше была на белой стене а сейчас скрыта под потолок. 

Так же между микроволновкой и правой стеной следует предусмотреть одну или две настенных полки, на комфортной высоте для людей разного роста. Как вариант использовать одну широкую красную полку либо две узких красных.

Важно так же не забывать, что позднее будет установлена барная стойка. Поэтому часть функций разогрева/наливания её поверхность сможет взять на себя.

**Comment by glitchcore** [comment]
> Выделенная зона под полноценную готовку не критична. Ключевая активность на мой взгляд - мытьё.

Тут я не согласен, исходя из предыдущего опыта пользования кухней, мы используем стол для хранения еды, каких-то действий с едой (заварить чай, порезать что-нибудь).

Мне нравится вариант с 30 см мойкой в левой части правого шкафа, [который скидывали в чат](https://www.ikea.com/ru/ru/p/vattudalen-vattudalen-odinarnaya-vreznaya-moyka-s-krylom-nerzhaveyushch-stal-s59243049/?utm_source=google&utm_medium=surfaces&utm_campaign=shopping_feed&utm_content=free_google_shopping_clicks%20_Kitchen).

Если размещать мойку в середине, и без того небольшой стол делится на две зоны шириной 30-40 см.

**Comment by glitchcore** [comment]
https://spb.leroymerlin.ru/product/moyka-58x50x16-sm-82522651/ вот такая мойка, влезает по размерам четко, но отзывы неоднозначные
https://spb.leroymerlin.ru/product/moyka-mln6049u-60x49x18-sm-82520259/ еще такая

**Comment by glitchcore** [comment]
Всем спасибо, все молодцы!
