### ISSUE TITLE
Сидячие места на встречу HWV

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#34]
У нас завтра мероприятие, куда зарегистрировалось 40 человек. По опыту нулевого дня придут 20-30. Сидячих мест в спейсе примерно 10 -- это стулья и мешки, еще человек 6 может присесть на короб, еще сколько-то постоит. Не хотелось бы, чтобы стоять пришлось половине пришедших.

Предлагаю купить еще 10 складных или стекающихся стульев.

Опции по покупке:
- Икеа белые 799 рублей за штуку https://www.ikea.com/ru/ru/p/gunde-stul-skladnoy-belyy-90360880/
- Икеа черные 799 рублей за штуку https://www.ikea.com/ru/ru/p/gunde-stul-skladnoy-chernyy-10360879/
- Авито, 25 стульев в объявлении, по 800 за штуку https://www.avito.ru/sankt-peterburg/mebel_i_interer/skladnoy_stul_ikea_1832190863, [в Икее они стоят 1 199](https://www.ikea.com/ru/ru/p/nisse-stul-skladnoy-chernyy-40360180/), забирать на Восстания

/deadline 2019-11-01T16:00:00+0300

**Comment by sntxerror** [comment]
Предлагаю купить 12 складных стульев в Икее 2 ноября утром. Мне кстати надо туда энивэй, купить для дома стул и пару других вещей. Могу поехать конечно один, но это будет дольше (добираться от дома до Икеи ~1:20 общественным либо ~500р на такси) и придется оплачивать доставку (примерно 800р)

**Comment by kaero** [comment]
Если мы решаем покупать, то я могу съездить и купить сегодня сегодня вечером, чтобы к утру все точно было готово, и не возникло никаких накладок. Иначе пробки, стулья опоздали, ...

https://www.ikea.com/ru/ru/p/gunde-stul-skladnoy-belyy-90360880/
https://www.ikea.com/ru/ru/p/gunde-stul-skladnoy-chernyy-10360879/

Тут по 800рублей есть 25 стульев получше, и они на Восстания, что всяко удобнее в плане логистики, чем Икея
https://www.avito.ru/sankt-peterburg/mebel_i_interer/skladnoy_stul_ikea_1832190863

**Comment by sntxerror** [comment]
Отлично! Нужно брать те что на восстания, они качественнее! Сколько штук будем брать?

**Comment by kaero** [comment]
Я обновил описание, предлагаю 10

**Comment by sntxerror** [comment]
предлагаю уменьшить дедлайн до 16:00, чтобы планировать вечер раньше

**Comment by kaero** [comment]
Объявление ок, договорился забрать в 19:00-20:00.

**Comment by kaero** [comment]
12 стульев приобретено
