### ISSUE TITLE
Отключить требование обязательно ревью для фич и багфиксов

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#342]
Считаю, что ограничение на обязательный аппрув от двух ревьюеров нужно только для веток **content/***, и не имеет смысла для веток feature и bug.

**Comment by sntxerror** [comment]
Не согласен. Ничего не помешает попрпвить контент в feature ветке вмержить и зарелизить.

**Comment by heeeyflo** [comment]
> Не согласен. Ничего не помешает попрпвить контент в feature ветке вмержить и зарелизить.

Всё так, однако ничего не мешает так же просто пойти и изменить политику пулл-реквестов.
Получается проблема СКУДа и разбитого окна. Бэкспейс это не наша основная работа, а Гитхаб для большинства отнюдь не такой же ежедневный инструмент, как какой-нибудь Телеграм, поэтому всё что происходит здесь — максимально stalled. 

В итоге, минутные аппрувы растягиваются на дни. Мне кажется что если для контента это ограничение ещё как-то можно оправдать и смириться с проблемой, то для функциональных элементов это лишено всяческого смысла и лишь тормозит прогресс.

**Comment by sntxerror** [comment]
Уверен найдутся сторонники позиции "лучше просить прощения за дикпик на гланге, чем разрешения на него", но я напомню основные задачи которые решает обязательность аппрува 2+ людей сейчас:

1. Обмен экспертизой и вовлечение разных участников к изменениям на сайте.
2. Осведомленность. Больше внимания к изменениям – больше людей вкурсе, что происходит. 
3. Коллективное редактирование и модерация. Меньше ошибок, меньше шансов залить код/содержимое противоречащее правилам, принципам, целям, задачам.

**Comment by sntxerror** [comment]
> В итоге, минутные аппрувы растягиваются на дни.

Не помню ни одного минутного PR который растянулся бы на дни по этой причине. То что PR с сайтом висел два месяца проблема автора PR и отсутствия у него ресурса на задачу.

Тоже самое и с PR рабочих групп.

**Comment by heeeyflo** [comment]
> Не помню ни одного минутного PR который растянулся бы на дни по этой причине. То что PR с сайтом висел два месяца проблема автора PR и отсутствия у него ресурса на задачу.

Лично у меня такое происходило с событием по метеозонду (три дня ушло на одну реакцию от трёх ревьюеров, и то со слов Саши это вышло довольно случайно) и вот сейчас уже сутки висит ПР по Github Actions с нулём реакций от трёх ревьюеров. Найти одного человека ещё как-то было можно, но по всему репозиторию не было не одного ПР кроме рабочих групп, у которого было бы больше одной реакции от ревьюеров. 

Мне не кажется что введение ограничений поможет решению перечисленных задач до тех пор, пока не увеличиться активность сообщества на Гитхабе. Пока нет рабочих групп и людей ответственных за, кхм.. сайт и вики, даже не понятно кого ставить в ревьюеры.

**Comment by heeeyflo** [comment]
Для меня, как для автора изменений, существует в итоге всего два варианта действий:
1. Ждать пока два случайных человека случайно наткнутся и отревьюят мои изменения.
2. Вкидывать ссылку на каждый свой пулл-реквест в жёлтый чат.

Первый вариант просто очень медленный. Второй – анноит людей полумашинными уведомленями в чате для людей. Получается так, что эти обременяющие механики демотивируют меня как контрибьютора — я фрустрирую от неопределённости насчёт моих изменений, либо вынужден идти зазывать людей их отревьюить. Мало приятного.

Мне казалось что именно для решения подобных вопросов мы и затеяли всю тему с рабочими группами:
 - Кто ответственнен за технологическую сторону сайта? Кого реквестить в мой #340?
 - А кто должен аппрувить события? 
 - А страницы в вики?
 - А значит ли то, что меня не засунули в ревьюеры по какому-то вопросу, отсуствие интереса к моему мнению?

Если бы существовали рабочие группы людей, ответственных за технологическую составляющую сайта, за организацию событий, за публичный контент, то было бы сразу ясно на кого вешать ревью, в Гитхабе даже есть нативные механизмы для этого.

Дело только в том, что рабочих групп у нас нет, и не совсем ясно когда появятся, а проблемы уже есть.

**Comment by glitchcore** [comment]
> Не помню ни одного минутного PR который растянулся бы на дни по этой причине

https://github.com/b4ck5p4c3/0x08.in/pull/356
https://github.com/b4ck5p4c3/0x08.in/pull/353

ни один из этиз PR не вызвал каких-то возражений, но завис из-за аппрува

**Comment by glitchcore** [comment]
Я предлагаю переехать в дискуссию https://github.com/b4ck5p4c3/0x08.in/discussions/363, а этот тред закрыть
