### ISSUE TITLE
Добавить дату на страницу встречи

### ISSUE THREAD

**Issue by algroznykh** [b4ck5p4c3/0x08.in#349]
Ожидаемый результат:
(на странице встречи,например https://0x08.in/events/glsl_2 есть после с датой)

**Comment by heeeyflo** [comment]
В коде есть упоминания этого элемента (компонент EventDate в Heading), но отсутствует его имплементация и сломан детект страницы события.

Проблема с детектом в [src/components/Heading/index.tsx](https://github.com/b4ck5p4c3/0x08.in/blob/dev/src/components/Heading/index.tsx#L31), **sourceInstanceName** всегда равен "page".

@sntxerror
