### ISSUE TITLE
Разработать порядок приема обращений

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#35]
по мотивам https://github.com/b4ck5p4c3/wiki/issues/14

Периодически к нам обращаются люди. Необходима общая точка входа с понятным гайдлайном для удобного формирования обращения.

**Comment by kaero** [comment]
Я не понимаю про что этот тикет. В не обозначена проблема и нет предложения по ее решению.

**Comment by sntxerror** [comment]
> Я не понимаю про что этот тикет. В не обозначена проблема и нет предложения по ее решению.

Поправил описание.

**Comment by glitchcore** [comment]
Общая точка именно для обращений — github issues.
В крайнем случае, можно написать в чат, на почту или персонально кому-то из нас.
Если человек не может/не хочет завиодить тикет, мы можем сделать это за него, обсудив с ним публичность.

**Comment by glitchcore** [comment]
В #14 у Фила были годные мысли на этот счет и я предложил ему добавить в вики их.

**Comment by sntxerror** [comment]
в #14, в постановке описан сценарий где обращение через issue излишне. Нам нужна почта или другая единая точка входа для обращений, намример формы обратной связи, так, чтобы мы все могли это прочитать и направлять людей из лички туда.

**Comment by kaero** [comment]
> в #14, в постановке описан сценарий где обращение через issue излишне

Прочитал и не нашел там такого.

На мой взгляд нужно завести ISSUE_TEMPLATE.md & SECURITY.md. Для непубличного обращения использовать Security -> Advisory -> New draft security advisory. Пример использования я заводил, владельцы и участники группы founders могут его видеть.

Также в обсуждении фигурировал момент: если обращающийся не может завести issue по какой-то причине (но мы же как-то об этом узнали), то можно сделать это за него.

Можно, как вариант, завести форму на сайте, которая будет заводить эти обращения от лица робота.

**Comment by kaero** [comment]
> Периодически к нам обращаются люди. Необходима общая точка входа с понятным гайдлайном для удобного формирования обращения.

Сейчас у нас есть такая точка. Вероятно, стоит на вики уточнить, что issues можно и нужно использовать так.

**Comment by glitchcore** [comment]
Конкретного решения не сформировано и острой потребности на данный момент, считаю, что можно закрывать /d

**Comment by heeeyflo** [comment]
Закроется после #90, но требуется почта + PGP.

**Comment by glitchcore** [comment]
Добавил почту
