### ISSUE TITLE
Встреча участников 09.02.2021

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#351]
- Вещи в "желтой меткой" от неучастников спейса. То есть вещи, которые человек готов дать в пользование спейса, но не готов к их дезинтегрированию.
- принять правила для чатов
- Приём @ilazeev в участники
- Вопроса введения формата голосовых совещаний

**Comment by glitchcore** [comment]
По вопросу заимствования:
Если неучастник хочет дать нам вещь, то брать её должен один из участников и нести за неё ответственность.
Это во-первых позволит использовать имеющиеся механизмы, а также исключит ситуацию, когда коллективное-бессознаельное будет неспособно нести ответственность за эту вещь, а также нормально и оперативно вещь вернуть хозяину.

**Comment by rusdacent** [comment]
> принять правила для чатов

К решению мы не пришли.
Мы не смогли сформулировать, какие проблемы с модерацией у нас есть, и что введение правил может решить.
Переспим с этой мыслью неделю, может вернёмся к ней в следующий вторник.

> Приём @ilazeev в участники

Принят в участники.

> Вопроса введения формата голосовых совещаний

Не пришли к решению, было несколько вариантов:

1. Введение модератора
2. Введение перды* (!)
3. Введение удвоенной перды* (!!) — чтобы можно было вести диалог, и асинхронно менеджить распределение перд
4. Опционально — электронная перда* (нажал, загорелась лампочка, ждешь когда можно говорить, можно запихать в бота)

`* непереводимый фольклор населения Хакспейса`
