### ISSUE TITLE
В футере сайта ссылка на мертвого бота

### ISSUE THREAD

**Issue by glukki** [b4ck5p4c3/0x08.in#374]
> этот забросили
> есть бт @mrvn_bot, который только открывает двери

https://github.com/b4ck5p4c3/0x08.in/blob/fa4c628139b7bf366897d0bdc1af0c5fd1a0cdf0/src/components/Footer/constants.ts#L4

**Comment by glukki** [comment]
И на главной:
https://github.com/b4ck5p4c3/0x08.in/blob/fa4c628139b7bf366897d0bdc1af0c5fd1a0cdf0/pages/index.mdx#L14

**Comment by glukki** [comment]
И вообще: https://github.com/b4ck5p4c3/0x08.in/search?q=b4cksp4ce_bot

**Comment by glitchcore** [comment]
Сможешь собрать из этого PR?

**Comment by glukki** [comment]
А что мы хотим получить в итоге?
Дать публичную ссылку на бота, который работает только по вайтлисту?
Удалить упоминание бота в принципе?
Что-то иное?

**Comment by heeeyflo** [comment]
Мы хотим починить основного бота, чем я сегодня занимаюсь.

**Comment by glukki** [comment]
В результате, этот таск на мне, и я уже 3 месяца урывками делаю этого бота :)
Решил делать его на Cloudflare Workers, потому что так интересней. А бесплатной квоты должно хватить с головой.

А еще код бота написан на фреймворке Grammy, и потому его будет несложно перенести вообще куда угодно, в случае необходимости.
