### ISSUE TITLE
Описать роль Участник

### ISSUE THREAD

**Issue by glukki** [b4ck5p4c3/0x08.in#381]
Любой, кто как-то взаимодействовал с Бекспейсом, онлайн или оффлайн — Участник.
Нужно добавить описание на сайт, к прочим ролям.
Рекомендовать участнику следовать принципам и правилам сообщества.

По результатам собрания 2021-12-14

**Comment by heeeyflo** [comment]
Добавлена информация в вики на странице про участие.
