### ISSUE TITLE
Заменить замок на оранжевой входной двери

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#45]
Сейчас замок заедает на открывании и иногда на закрывании. Зачастую тратится несколько минут чтобы открыть основную дверь. 

Предлагаю во избежание инцидентов заменить замок и при необходимости передать мастер-ключ представителю собственника.

**Comment by glitchcore** [comment]
Я посмотрю замок, если необходимо — поменяю.

А вообще, см. #52

**Comment by glitchcore** [comment]
@lomalkin помазал, теперь работает
