### ISSUE TITLE
Доводчик на дверь в резидентскую

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#47]
В простанство резидентов планируется ограниченный доступ. Сейчас дверь чаще всего открыта совсем, что создает плохую привычку у гостей - свободно ходить в резидентской. Необходимо установить доводчик на дверь резидентского кабинета, уже сейчас, не дожидаясь СКУД.

**Comment by kaero** [comment]
сделал @komplivit
