### ISSUE TITLE
Стеллажи в холл и общий зал

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#48]
Необходимо спроектировать и закупить стеллажи для холла и для общего зала.

**Comment by glitchcore** [comment]
@sntxerror сможешь на себя взять эту задачу?

**Comment by kaero** [comment]
> спроектировать

Я предлагаю настолько не упарываться, а поискать и купить максимально подходящие.

**Comment by glitchcore** [comment]
Ну проект не обязательно подразумевает конструирование новых стеллажей

**Comment by kaero** [comment]
> проект не обязательно подразумевает конструирование новых стеллажей

Ок, это не очевидно. В описании буквально написано: 

>> спроектировать и закупить стеллажи

**Comment by glitchcore** [comment]
Короче я надеюсь, что Лёня займется этой задачей и более подробно её распишет

**Comment by z4fd** [comment]
Тёма нашел такой вариант: https://www.avito.ru/sankt-peterburg/oborudovanie_dlya_biznesa/stellazhi_bu_1574975144

**Comment by sntxerror** [comment]
1. Предлагаю брать 2 стеллажа 800x400x2000 и 2 стеллажа 800x500x2000 [здесь](https://stillage.pro/shelving/titan-ms-arxivnyie-stellazhi.html).

В сумме получится два составных стеллажа шириной 1600 и варьируемой глубиной. Они усиленные (<150кг), а два типа полок 800+400/500 можно будет по разному комбинировать.

Хочется сохранить побольше пространства помещения, поэтому предлагаю глубину стеллажа не больше 500мм.

2. Так же предлагаю взять два стеллажа 1000x200x1900 для мелочи здесь:
https://www.avito.ru/sankt-peterburg/oborudovanie_dlya_biznesa/stellazh_10002001900_1290777372

Сомневаюсь про глубину 200, нужно мнение. Они деревянные, не глубокие и их легко подрезать под нужную ширину. Ставить предлагаю вдоль стены резидентская/зал.

**Comment by kaero** [comment]
Про картотеку для мелочи: я не понимаю, чем они лучше металлического стеллажа. Можно взять просто больше полок в металлический стеллаж. 

Если бы у них в комплекте были картотечные боксы за эти деньги -- было бы круто, можно туда наваливать всякую мелочевку, а так нужно еще подобрать или изготовить боксы по размеру ячеек. С металлическим стеллажем имхо больше гибкости в ячейках хранения.

**Comment by kaero** [comment]
Про стеллажи: зачем брать разную глубину? Если взять все одной, то можно перемещать полки между стеллажами, иначе -- нет. 

Еще я не увидел у них ширины 800мм в калькуляторе. Откуда инфа, что такие есть?

**Comment by sntxerror** [comment]
Переоформил заказ. В итоге заказаны 2 стеллажа 2000x1000x400 и 2 стеллажа 2000x700x400.

**Comment by sntxerror** [comment]
Стеллажи доставлены. Расходы внесены. Создаю задачку на сборку.

**Comment by NetBUG** [comment]
А был бы CI/CD, задача на сборку создалась бы сама.

**Comment by glitchcore** [comment]
> А был бы CI/CD, задача на сборку создалась бы сама.

А потом и на тест, и на деплой

**Comment by glitchcore** [comment]
А потом и на тест и на деплой

>
