### ISSUE TITLE
Большой стол в общий зал

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#49]
Необходимо спроектировать и заказать большой стол в общий зал. По плану он должен состоять из двух одинаковых секций и быть разборным при необходимости.

**Comment by glitchcore** [comment]
Насколько я помню, пришли к концепции стоек типа [Лерберг](https://www.ikea.com/ru/ru/p/lerberg-opora-dlya-stola-belyy-70384919/),  @kaero хотел заказать из нормальной стали их.
+ составная двойная столешница из фанеры
+ и у @sntxerror была идея, чтобы центральные ножки скрепляли столешницы, мне нравится

**Comment by glitchcore** [comment]
Короче ребята затарили 4 стола 60×120, временно вопрос решен
