### ISSUE TITLE
Регистрация на HVW

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#5]
Нужна ли регистрация, сколько человек ограничивать?
Вроде у нас будет страничка на meetups, можно видимо там и сделать регу.

**Comment by kaero** [comment]
Исходя из опыта нулевого дня, не более 40 -- тогда придет около 25.

**Comment by kaero** [comment]
Я бы делал регу. Исходя, опять же из опыта 0дня, просил бы настоящие email (можно перейти на какой-то инструмент, который не дает организатору доступ к email, только прозрачную возможность обратиться), чтобы иметь канал для экстренной коммуникации.

**Comment by z4fd** [comment]
> на какой-то инструмент, который не дает организатору доступ к email, только прозрачную
> возможность обратиться), чтобы иметь канал для экстренной коммуникации.

Кстати вот вопрос, а почему канал в телеге таковым не является ? 

A: Люди узнали, пришли на ивент не из телеги
B: Можно явно в анонсе указывать, что все оперативные обновления и новости будут транслироваться в канал

А: Не у всех есть телега
B: Я думаю мы не сможем найти такой вариант которым бы пользовались все (Мейл сейчас все чаще используют не как средство коммуникации и заходят туда крайней редко)

Ну или тогда мейл не должен быть единственным средством экстренной коммуникации

**Comment by kaero** [comment]
email есть у всех (ну, правда, я не знаю ни одного человека, у которого нет gmail/yandex/icloud аккаунта), телеги у некоторых нет, у некоторых она работает с переменным успехом. 

Речь исключительно о распространенности и технической возможности, а не предпочтениях людей, в том числе наших.

**Comment by glitchcore** [comment]
> B: Я думаю мы не сможем найти такой вариант которым бы пользовались все (Мейл сейчас все чаще используют не как средство коммуникации и заходят туда крайней редко)

я думаю, нужно просто оперативные оповещения распространять по нескольким каналам, вот и все
