### ISSUE TITLE
Про масло и полки

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#50]
Считаю масление всех оставшихся полок не критичным. Эксплуатировать предлагаю как есть.

**Comment by glitchcore** [comment]
Ну, мы уже их эксплуатируем)

Тут скорее вопрос, у кого найдется время этим заняться. Люба и Артем (брат Фила) в разное время высказывали желание это сделать, я поспрашиваю

**Comment by glitchcore** [comment]
И да, мы отказались от тега discuss, достаточно поставить /a в каком-то сообщении, и отсчет начнется

**Comment by LiebeLibelle** [comment]
Да, я готова домаслить полки. Вот прям в среду или в четврег. Только вопрос надо ли их заново шлифовать после n дней эксплуатации?

**Comment by glitchcore** [comment]
Думаю, нужно помыть чем-нибудь типа спирта, и может быть шлифануть если в каких-то местах они прям грязные

**Comment by LiebeLibelle** [comment]
Всё есть? Спирт, масло, шкурка?

**Comment by glitchcore** [comment]
Масло есть, шкурка есть, спирт надо купить

**Comment by LiebeLibelle** [comment]
За спиртом могу зайти, окей. Тогда понабегу в ближайшие несколько дней

**Comment by glitchcore** [comment]
Про спирт #54. Назначь на себя?

**Comment by komplivit** [comment]
>высказывали желание

05.11 приеду
недавече мне просто не ответили кто будет на месте или нет)

**Comment by glitchcore** [comment]
@LiebeLibelle вроде тоже сегодня собиралась

**Comment by glitchcore** [comment]
@komplivit и @LiebeLibelle  Намаслили три полки, пошкурили одну и собрали один стол. Завтра дошкурят.

**Comment by komplivit** [comment]
полки прошкурены. нужно длинные болты и барашки для крепления к столам 4шт.
