### ISSUE TITLE
СКУД hackathon

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#52]
Задачи, котрые должнен решать низкий уровень системы:
1. Управление магнитными замками:
1.1 на уличной (стеклянной) двери
1.2 на входной (оранжевой) двери
1.3 на двери в резидентскую
2. Управление обычным замком на входной (оранжевой) двери
3. Управление магнитным замком на двери в резидентскую
4. Аутентификация человека по карточкам (?)
5. Гостевой доступ: кнопка для звонка и камера
6. Датчики закрытия дверей
7. Датчик защелки в переговорке
8. Управление освещением на улице и в коридоре
9. Мигающая лампа на входе чтобы головой не биться

У меня есть идея о том, что его стоит провести в два этапа:
1 этап:

* собраться, решить чисто бытовые вопросы с замками и доводчиками 
  * из задачи #45 — починить/заменить замок на входной двери
  * из задачи #46 — установить доводчик на внешнюю дверь
  * из задачи #47 — установить доводчик на резидентскую
  * поставить магнитные замки на внешнюю дверь и на резидентскую
  * сделать в переговорке возможность закрываться изнутри ручкой
  * поставить на входе читалку NFC и кнопку с камерой
  * протянуть провода

в общем все, что можно решить на месте и сразу сделать

* обдумать архитектуру самого СКУДа

2 этап: уже подготовить контроллеры, софт, собраться и запустить все

**Comment by kaero** [comment]
> сделать в переговорке возможность закрываться изнутри ручкой

Поместить ключ в замке внутри переговорки сойдет за workaround?

Можно ли в переговорке заменить механизм ручки-замка на такой же как в туалете без потерь?

**Comment by glitchcore** [comment]
> Можно ли в переговорке заменить механизм ручки-замка на такой же как в туалете без потерь?

Вроде это типичный межкомнатный замок, должно прокатить. Если будет сложно — вставим ключ, но это не ынтерпрайзно, ключ украдут потеряют согнут

**Comment by komplivit** [comment]
> Можно ли в переговорке заменить механизм ручки-замка на такой же как в туалете без потерь?

Можно заменить дверь в переговорке и туалете, просто поменять местами) 
всех неугодных закрывать там. 

Как вариант сделать по принципу туалетов в поездах, занято/свободно.

**Comment by glitchcore** [comment]
Добавил требования к системе
