### ISSUE TITLE
Анонс HVW meetup

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#6]
**Что такое hardware hacking и как им обмазаться**
_Aanper_
_Zaf0d_

Узнаем что это и зачем этим заниматься, посмотрим на минимальный набор, необходимый для того, чтобы начать исследовать железо.

**Loss, noise and two Friis equations**
_Юшков Иван, embedded engineer_

Попробуем разобрать основные моменты про шумы в приемниках, посмотрим на вопросы согласования СВЧ цепей — почему длина имеет значение.

**Особенности проектирования систем сбора данных при работе с биологическими объектами.**
_Арман, магистрант МГТУ имени Баумана._

Одна из ключевых задач в медицине и человеко-машинных интерфейсах — регистрация различных параметров, например, активности мышц. Узнаем, на что следует обратить внимание при работе с биологическими сигналами, и почему кроме познаний в электронике и антенной технике при проектировании важно понимать биофизику исследуемых процессов.

**Применение Rust для архитектуры RISC-V**
_Disasm_

Доклад посвящён применению языка Rust для embedded-разработки. В качестве целевой архитектуры рассматривается RISC-V и её реализации как в чипах, так и на FPGA.

Мероприятие пройдет 2 ноября в нашем пространстве. Начинаем в 15:30

**Comment by kaero** [comment]
lgtm

**Comment by glitchcore** [comment]
Опубликую как только разберемся с регистрацией
