### ISSUE TITLE
Вернуть тэг discuss

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#61]
И да, мы отказались от тега discuss, достаточно поставить /a в каком-то сообщении, и отсчет начнется

_Originally posted by @aanper in https://github.com/b4ck5p4c3/wiki/issues/50#issuecomment-549524255_

Предлагаю вернуть тэг, потому что он необходим для фильтрации обсуждений от непосредственных задач. Кроме того я не видел где произошел отказ, я против.

**Comment by glitchcore** [comment]
> Кроме того я не видел где произошел отказ, я против.

произошел в ходе обсуждения PR с правилами принятия.
Окей, мне не так принципиально, можно и вернуть.

Иронично, что у этого обсуждения нет ни тега, ни команды /a в первом сообщении)

**Comment by kaero** [comment]
> Предлагаю вернуть тэг, потому что он необходим для фильтрации обсуждений от непосредственных задач. 

Зачем?

**Comment by glitchcore** [comment]
Вроде решили, что размечаем задачи статусами hold - to do - doing - done
/d
