### ISSUE TITLE
Уважаемая редакция

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/0x08.in#62]
Предлагаю сформировать редакцию b4cksp4ce, и выделить в зону её ответственности:

- написание постов, анонсов
- написание, вычитка и редактирование текстов сайта
- вычитка и редактирование текстов wiki (без изменения сути, смысла, предмета)
- задачи дизайна внешних коммуникаций (фирстиль, мерч и тд)
- ведение календаря и плана мероприятий, поиск докладчиков, подготовка событий
- другие задачи связанные с Public Relations, информационной поддержкой, дизайном 

Состав редакции предлагаю формировать отдельно от состава участников и резидентов. Процессы и иснтрументы предлагаю определять самой редакцией.

**Comment by glitchcore** [comment]
1. Что мешает прямо сейчас вычитывать тексты сайта, wiki, делать мерч, предлагать мероприятия, предлагать посты?
2. Означает ли появление редакции, что у нее будут какие-то исключительные права на вышеперечисленные действия?

**Comment by z4fd** [comment]
Это вообще зачем ? Мало того что я сейчас это вижу как прямо противоречащие принципам сообщества. Может я конечно не так понял, но это выглядит как какая-то внешняя сущность имеющая контроль над всеми коммуникациями и хочется сжечь это

**Comment by glitchcore** [comment]
> хочется сжечь это

not so excellent.

> прямо противоречащие принципам сообщества

прошу указать, каким принципам и как противоречит

**Comment by z4fd** [comment]
> not so excellent.

Немного подгорело, извиняюсь

> прошу указать, каким принципам и как противоречит

Как я уже написал, возможно я не прав, нужны комментарии от топикстартера. Но из написанного я понял, что предлагается выделить группу людей НЕ из состава участников или резидентов, наделив их правами см. по списку. И тут возникает вопрос, если права исключительные, то это нарушает "Каждый может заниматься тем, чем хочет, не мешая другим". Т.е. если кто-то захочет сделать вычитку текста, ему не пулреквест надо будет слать, а идти с поклоном к Редакции и проходить еще один фильтр. Если нет, то непонятен смысл этого issue т.к. это все задачи которые можно делать уже сейчас

Главные мои претензии  это:
- Не понятен смысл существования
Если кто-то захочет группой людей например задезайнить и наверстать сайт, ни что не мешает им коммуницировать так как угодно, а потом кинуть пулл с результатом
- Напрягает подчеркнутое "формировать отдельно от состава участников и резидентов"
Казалось что это один из смыслов всей затеи, делать все самим. Или я не прав ?


Контр предложение:
- Сделать блеклист для канала
- Разобрать задачи из списка и расставить приоритеты
- Лично договориться о инструментах для взаимодействии друг с другом (например если текст hackmd, etherpad, googl docs и т.д.)

**Comment by kaero** [comment]
Я не понимаю, зачем редакция. Любой участник может что-то предложить опубликовать, предложить правки к готовящемуся материалу. Именно поэтому я не вижу смысла в закрытом обсуждении постов. 

Также я против зоопарка инструментов без рациональных для этого оснований.

Я допускаю, что в некоторых случаях организаторы могут готовить какое-то секретное для других участников объявление, но в таком случае достаточно ограничить доступ к собственно готовящемуся контенту (благо google docs позволяет это сделать). 

Я против выделения специальных полномочий для какой-то группы людей, так как это влечет за собой две проблемы:
1. эта группа становится бутылочным горлышком процесса: нельзя опубликовать больше контента, чем эта группа может обработать, а мы уже без всякого деления слишком медленно записываем и публикуем
2. факт наличия исключительных привелегий без функционального смысла становится основанием для коррупции, спекуляций, разделения социума

Любого одного из перечисленных пуктов считаю достаточным, чтобы избегать всему возможными способами появления таких групп.

Я вижу процесс работы со всем описанным, как и с любым другим issue: предложение, обсуждение, решение, выполнение решения. Инструменты для ограничения доступа у нас есть, как уже много раз обсуждалось в других тикетах на эту тему.

**Comment by kaero** [comment]
> прошу указать, каким принципам и как противоречит

- [Участники вкладывают больше, чем потребляют](https://github.com/b4ck5p4c3/wiki/pull/63/files#diff-4109d9630b0fbf20890954fd1bf8e78cR16) -- так как предполагается, что какая-то ограниченная группа обслуживает остальных
- [Do-ocracy](https://github.com/b4ck5p4c3/wiki/pull/63/files#diff-4109d9630b0fbf20890954fd1bf8e78cR12) -- так как предполагется, что участники без участия редакции не могут опубликовать материал, особенно странно это по отношению к вики, которая по сути является документацией по хакспейсу и должна правиться без приложения усилий и тем более какой-то редакции. Вики -- это я сделал сегодня кнопку "эвакуировать хакспейс на луну" и написал об этом на вики, чтобы была документация на кнопку и процесс эвакуации.
- [Каждый может заниматься тем, чем хочет, не мешая другим](https://github.com/b4ck5p4c3/wiki/pull/63/files#diff-04c6e90faac2675aa89e2176d2eec7d8R68) -- так как не будучи представителем редакции учасник не может заниматься вмененными редакции задачами, а если может, тогда в чем смысл выделения редакции и ее круга обязанностей?

**Comment by kaero** [comment]
И претензия к тикету: он предлагает решение (создание редакции), но не декларирует проблему, которую это предложение должно решить.

**Comment by NetBUG** [comment]
Стоп, я не понял, а где ответственное лицо хакспейса, с которым будут связываться кураторы из ФСБ, и которое будет выполнять контроль?

**Comment by glitchcore** [comment]
> Стоп, я не понял, а где ответственное лицо хакспейса, с которым будут связываться кураторы из ФСБ, и которое будет выполнять контроль?

обратитесь в кабинет № 4 для обращения к ответственному лицу хакерспейса

**Comment by glitchcore** [comment]
Обсудили, что посты пишем в формате issue, постим на сайт, распощиваем (руками или ботом) по всем информационным каналам
/d
