### ISSUE TITLE
Регулярная встреча участников хакспейса

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#64]
У нас регулярно накапливаются вопросы требущие обсуждения, но обсуждение онлайн не задается. При этом стихийно собираться очно трудно: никто не планирует эти встречи заранее. 

Предлагаю завести регулярную встречу участников, например, раз в две недели вечером в среду в 20:00 (потому что это время такое же плохое как и любое другое).

Встречу завести в календаре спейса.

К участию преглашать: организаторов, резидентов, участников.

К каждой встрече формировать список вопросов к обсуждению из issues в GitHub, где не удается достичь консенсуса, но их решение кажется важным.

Записать регламент проведения встреч: как минимум нужен модератор, чтобы не скатываться в срач. Эта роль может быть переходящей.

**Comment by glitchcore** [comment]
> потому что это время такое же плохое как и любое другое

Во вторник же!)

**Comment by kaero** [comment]
> Во вторник же!)

Можно и во вторник. Я к тому, что всегда кому-то почему-то любое выбранное время будет неудобно временно или постоянно. Сложно собрать больше чем двух человек, а чем больше нас будет, тем будет еще сложнее.

На мой взгляд, это в том числе должно мотивировать участников к уменьшению необходимости такой коммуникации, то есть к конструктивному решению максимума вопросов в issues.

**Comment by glitchcore** [comment]
@kaero создай PR
