### ISSUE TITLE
Публикация финансов

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#7]
Обсуждаем, какой инструмент использовать и кто может распоряжаться финансами.

Предлагаю:
1. Т.к. у нас нет расчетного счета и все деньги лежат буквально у нас на руках, вести закрытую таблицу с именами о том, кто сколько взял-положил
2. Расчеты вида «в хакспейс пришло, хакспейс потратил» вести отдельной публичной гуглотаблицей
3. Интеграцию делать руками, из закрытой таблицы сослаться на публичную и навернуть формул, которые будут проверять, что баланс/история транзакций сходится между таблицами.

Редактирование таблицы ведется фаундерами, все траты и поступления должны производиться либо на основании правил, либо на основании решения в issues.

**Comment by kaero** [comment]
@aanper я предлагаю быть последовательными, и изменить и ограничить скоуп этого обсуждения. 

Предлагаю тут решить:
1. Публикуем ли мы финансовую информацию открыто? Я не помню, чтобы мы окончательно приняли такое решение.
1. Если публикуем, то какую именно.

**Comment by glitchcore** [comment]
на 0-day я заявил о том, что для того чтобы быть некоммерческими, мы должны публиковать анонимно все поступления денег к нам, и все расходы

**Comment by kaero** [comment]
Я не против, но не помню, чтобы у всех участников было согласие по этому поводу (это не означает, что это не так, я правда не помню).

В люом случае нужно решить что именно публиковать и как часто. Исходя из этого выбрать вид экспорта, а сам экспорт делать из инструмента ведения бухгалтерии, который нам все равно понадобится.

**Comment by glitchcore** [comment]
> В люом случае нужно решить что именно публиковать и как часто. Исходя из этого выбрать вид экспорта, а сам экспорт делать из инструмента ведения бухгалтерии, который нам все равно понадобится.

я как раз думал, что мы будем, так сказать, в live режиме отображать происходящее. Условная гуглотаблица (так сделано, кажется, в новосибирском хс)

> Я не против, но не помню, чтобы у всех участников было согласие по этому поводу (это не означает, что это не так, я правда не помню).

в любом случае, это согласие стоит получить в явном виде, например, здесь

**Comment by kaero** [comment]
> я как раз думал, что мы будем, так сказать, в live режиме отображать происходящее. Условная гуглотаблица (так сделано, кажется, в новосибирском хс)

Как только у нас будет юрлицо, расчетный счет и бухгалтерия у-- источником правды должна стать бухгалтерия. Можно все наавтоматизировать на ней (по крайней мере несколько сервисов, что я знаю имеют довольно сносные API). 

До этого можно:
1. Потерпеть
2. Руками переносить из закрытой таблички в открытую
3. Написать скрипт для п.2

**Comment by glitchcore** [comment]
> 2\. Руками переносить из закрытой таблички в открытую

можно так

**Comment by z4fd** [comment]
Может тогда вообще имеет смысл все и юридический оформить как НКО ? У меня у самого нет точной позиции по этому предложению, насколько оно вообще имеет место быть в таком контексте. Нырну в консультант плюс, может что-то интересное откопаю

**Comment by glitchcore** [comment]
> Может тогда вообще имеет смысл все и юридический оформить как НКО?

а потом нас вые^W будут пристально инспектировать. В общем, нагрузка на отчетность возрастает неимоверно

**Comment by kaero** [comment]
> Может тогда вообще имеет смысл все и юридический оформить как НКО ?

У меня есть позиция. Нет смысла. Плюсов нам никаких, отчетности и внимания со стороны госструктур больше. Придется все время доказывать, что мы не получаем выгоду, обосновывать траты, и не фактически, а так, чтобы удовлетворить 1000 и 1 дурацкий закон и инспектора.

**Comment by glitchcore** [comment]
Обновил описание
/a

**Comment by kaero** [comment]
> Предлагаю:
> 1. Т.к. у нас нет расчетного счета и все деньги лежат буквально у нас на руках, вести закрытую таблицу с именами о том, кто сколько взял-положил
> 2. Расчеты вида «в хакспейс пришло, хакспейс потратил» вести отдельной публичной гуглотаблицей
> 3. Интеграцию делать руками, мб из закрытой таблицы сослаться на публичную (вроде так 
можно?) и навернуть формул, которые будут проверять, что баланс/история транзакций сходится между таблицами

Поддерживаю.

Также предложить заинтересованного человека в ведения и автоматизации бухгалтерии, как этой недобухгалтерии, так и в будущем "настоящей".

>  Обсуждаем, ... и кто может распоряжаться финансами.

На вторую часть вопроса ответа и обсуждения нет. Либо вынести в отдельную issue, либо таки решить тут.

Моя позиция такова: решения касательно необязательных трат (список таких зафиксировать явно, сейчас это: аренда помещения, коммунальные услуги, электричество, интернет в спейсе) стоит принимать в дискуссионом порядке в issues, как и другие.

Пока отклоняю из-за отсутствия в описании предложения по второй части вопроса. 
/d

**Comment by glitchcore** [comment]
Добавил кусок про «кто может распоряжаться»
/a

**Comment by glitchcore** [comment]
Создал PR #37
