### ISSUE TITLE
Сделать анонс СКУД hackathon`а

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#70]
Т.к. на выходные (9.11-10.11) запланировали хакатон, надо на основе описания из #52 сделать анонс. Дедлайн вечер 07.11

Скопировал описание в док и сделал заготовку https://docs.google.com/document/d/1EkvfQNdc1b6L9XtrMBv4MtiBuvutymy-f12ae-3WQ4Q/edit

/deadline 2019-11-07 23:00

**Comment by z4fd** [comment]
@aanper уже запили пулл  #69

**Comment by glitchcore** [comment]
Предлагаю закрыть как дублирующееся

**Comment by z4fd** [comment]
Закрыто как дубликат #69
