### ISSUE TITLE
Приобрести электромагнитные замки

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#72]
Для завтрашнего хакатона (#52) нужны замки: 2 шт, типа [таких](https://alpatech.ru/elektromagnitnye/st-el050s-zamok-elektromagnitnyy-smartec/)

**Comment by lomalkin** [comment]
Есть катушка без ответной части. Могу подогнать.
![IMG_20191108_171123](https://user-images.githubusercontent.com/1192479/68482556-e588ba80-024a-11ea-8d26-073d5c9a65bb.jpg)
![IMG_20191108_171134](https://user-images.githubusercontent.com/1192479/68482557-e588ba80-024a-11ea-9054-76a6aa62a541.jpg)

**Comment by NetBUG** [comment]
Есть катушка типа AccordTec на 180 с уголком крепления, на входную пойдёт.
Могу подогнать в районе 18 числа, или организовать квест «забери из моего питерского дома».
Также есть полный комплект Визитовского домофона (панель, БП, матричный блок) на 100 квартир.

**Comment by kaero** [comment]
Не актуально
