### ISSUE TITLE
Пожарная безопасность

### ISSUE THREAD

**Issue by komplivit** [b4ck5p4c3/0x08.in#74]
Выглядит необходимым закупить пару огнетушителей с подставками или креплениями на стену. план-схема эвакуации и номера различных экстренных служб, судя по всему и датчики тоже стоит проверить.

**Comment by z4fd** [comment]
Один огнетушитель с креплением сегодня принесли, надо подумать куда его повесить

**Comment by van2048** [comment]
Еще бы добавил что по скольку стоимость средней железки превышает стоимость огнетушителя имеет смысл покупать углекислотные огнетушители а не порошковые. После использования порошкового, устройства в радиусе пары метров скорее всего не удастся привести в юзабельное состояние

**Comment by glitchcore** [comment]
Закупили углекислотный с подвесом
