### ISSUE TITLE
Киносеанс: "Все создания, добро пожаловать! / All Creatures Welcome" RUS SUB (22.11)

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#75]
> Документальный фильм о хакерском движении и крупнейшей в европе хакерской ассоциации Chaos Computer Club

Добыли фильм с русскими субтитрами, предлагаю сделать киносеанс на следующей неделе вечером, например 22 числа 

/a

**Comment by glitchcore** [comment]
Сделай PR в страницу с событиями, ну
