### ISSUE TITLE
Размещение переговорки в холле

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#77]
Есть предложение, кардинально отличающееся от прежнего плана:
а что если отгородить часть холла, где сейчас стоит вешалка? Там довольно удаленное в плане шума место, перегородку проще сделать, доступ есть для всех.

**Comment by kaero** [comment]
Мы там панировали хранение проектов и "кухню". 

Стеллаж с проектами в общем зале разместим?

От кухни отказываемся?

**Comment by glitchcore** [comment]
![photo_2019-11-27_01-03-20](https://user-images.githubusercontent.com/12886640/69676440-cd6dc380-10b1-11ea-9052-3b43f4b11c30.jpg)

**Comment by kaero** [comment]
Очно обсудили, что переговорка в "прихожей" всем норм и будем делать там. 

/a

**Comment by lomalkin** [comment]
/a

Issue можно закрывать?

**Comment by glitchcore** [comment]
Я, честно говоря, хз чо с этим делать, надо где-то зафиксировать решение

**Comment by kaero** [comment]
Думаю, что ближайшее время с переговоркой будем делать примерно ничего, потому предлагаю закрыть ишью без решения.

**Comment by glitchcore** [comment]
Я сначала думал, что пусть она висит напоминанием, но наверное и правда можно закрыть.
/d
