### ISSUE TITLE
Вернуть Домофон

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#79]
Прикрутить кнопку с камерой
Прикрутить iButton
Прикрутить магнит
? Более длинный установочный болт
? Шайба/пластина

**Comment by kitnerboy** [comment]
Нужно ещё толстое сверло, чтобы было куда вставить более длинный болт.
Думаю, сверло надо по размеру гайки (ну или как это можно назвать).

**Comment by kitnerboy** [comment]
Текущее состояние:
Повесили камеру и считыватель iButton. Расположили над дверью, чтобы была максимальная защита от падающей с неба воды.
Установили на двери пластину от магнитного замка.
Есть сложность с тем, что сам магнитный замок в косяке двери (ну или как это можно назвать) можно закрепить только в тонкой пластине. Пример такой ненадёжной фиксации можно увидеть там же на доводчике: верхняя пара саморезов входит в профиль внутри рамы дверного косяка, а нижняя пара держится только за одну пластнку, а в целом саморез висит в воздухе. Замок конструктивно можно повесить только на уровне нижних саморезов доводчика. Ну либо поднять немного замок, так что он будет соприкасаться только с частью ответной пластины. Максимальная нагрузка снизится, но хотя бы будет ниже шанс вырывания замка.

Осталось:
Перенести кнопку открытия. Это просто вопрос времени, особых сложностей **пока** не наблюдается.
Провести питание к замку. @aanper в чате что-то считал по сечению провода, были предположения по повышению напряжения питания замка. Я не заметил выводов. Можно провести питание по сигнальной шине, взяв две пары проводников для увеличения тока.
Дождаться монтажа NFC считывателя и зашить обратно крышу аквариума.

**Comment by glitchcore** [comment]
Вроде все сделали. Надо магнит поставить по-человечески, но можно позже
