### ISSUE TITLE
Проблема(?) неконсистентности адресов спейса

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#8]
Т.к. само название и основной вариант B4CKSP4CE постоянно заняты, нам приходиться каждый раз изгаляться по разному. Предлагаю выбрать и делать какой-то суффикс и использовать его везде, где получиться поменять. Что я конкретно имею ввиду:
- b4cksp4ce_hackspace
- ....

Че думаете ? Было бы здорово, сразу еще вариантов придумать если понравилась идея, но не суффикс

Это все  за исключение адреса сайта, он прекрасен

**Comment by glitchcore** [comment]
Мне кажется, что это не проблема, можно изгаляться как угодно, народ во всякие странные места попадает обычно по ссылкам.
Алсо b4ck5p4ce почти всегда свободен. Ну или b4ck5p4c3 уж на крайний случай

**Comment by kaero** [comment]
Мне тоже не нравится разножопица, но я не вижу уже безболезненного способа нормализации имени везде. И это скорее вкусовщина, нежели какая-то реальная проблема. В плане ссылок я солидарен с @aanper

**Comment by glitchcore** [comment]
Предлагаю закрывать

**Comment by kaero** [comment]
> Предлагаю закрывать

Но правила закрытия должны быть определены https://github.com/b4ck5p4c3/wiki/issues/2 !

**Comment by glitchcore** [comment]
> Но правила закрытия должны быть определены #2 !

да, меня тоже радует)
предлагаю в этом случае автору обсуждения принять решение о закрытии.
