### ISSUE TITLE
Верстак

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#82]
Закончить с чертежами

**Comment by NetBUG** [comment]
Можно провести второй сейшн, можно в менее лекционном формате.

**Comment by glitchcore** [comment]
С появлением токарника вопрос верстка становится весьма актуален

**Comment by sntxerror** [comment]
актуальности прибавляет в том числе и появление принтера

**Comment by p-hash** [comment]
Этот issue жив? В каком оно статусе?

**Comment by glitchcore** [comment]
Думаю, что как минимум нужно будет концепцию пересматривать, потому что верстак нужен в хардварь и, видимо, какой-то другой.

/d

**Comment by heeeyflo** [comment]
Закрыто, в связи с необходимостью обсуждения и реализации полностью новой концепции верстака.
