### ISSUE TITLE
Дежурство, расписание и вообще

### ISSUE THREAD

**Issue by glitchcore** [b4ck5p4c3/0x08.in#87]
Для новых участников неочевидно, что хакспейс работает, в какое время и вообще, можно ли к нам приходить.
Помимо информации «открыто ли сейчас», которую может предоставлять СКУД, необходим какой-то механизм, с помощью которого можно будет узнать, можно ли придти, в какое время, или договориться с кем-то из потенциальных дежурных о том, чтобы придти

**Comment by kaero** [comment]
Предлагаю Google-календарь, который, к тому же, у нас уже есть :)

https://calendar.google.com/calendar/embed?src=n0oev7vtqntpok3phdbb48cvu0%40group.calendar.google.com&ctz=Europe%2FMoscow

Я завел событие "Открыто" например на 27 число, когда я с 13 до 20 буду в спейсе.

@aanper @kaero @z4fd @sntxerror и Димон имеют права на редактирование

**Comment by kaero** [comment]
Можем размечать время, когда открыто для участников, открыто для гостей, мероприятия

**Comment by glitchcore** [comment]
Предлагаю на еженедельных встречах раскидывать хотя бы вечернее и выходное дежурство, в рабочее время будних дней добавлять on demand

**Comment by glitchcore** [comment]
Во, еще стоит создать таки бота, через которого можно будет делать запросы в ключе «а будет ли открыто в желаемое время». То же самое можно делать через почту, например

**Comment by glitchcore** [comment]
В PR #90 я добавил ссылку на календарь, на чат и сделал гуглоформу обратной связи, на нее можно подписаться

**Comment by lomalkin** [comment]
> Во, еще стоит создать таки бота, через которого можно будет делать запросы в ключе «а будет ли открыто в желаемое время». То же самое можно делать через почту, например

Предлагаю вместо бота вывесить таки плашку на сайт в качестве основного механизма. 

Альтернативный вариант (если хочется быть поближе к Телеге): паблик с автопостингом, в который постится, что кто-то пришел (первый) или кто-то ушел (последний). Информацию в этом случае надо будет брать из СКУДа.
P.S. Это позволяет как минимум гибко управлять уведомлениями, чтобы включив их можно было по дороге понять, что приходить уже поздно. Или наоборот, включить и ждать, когда кто-то первый придет.

**Comment by glitchcore** [comment]
> Предлагаю вместо бота вывесить таки плашку на сайт

Кажется, одно другому не мешает, будем постепенно наворачивать интеграций

**Comment by lomalkin** [comment]
> Кажется, одно другому не мешает, будем постепенно наворачивать интеграций

Энивей, я считаю, что наворачивать бота на плашку на сайте проще и правильнее, чем плашку на бота.

**Comment by kaero** [comment]
> наворачивать бота на плашку на сайте проще и правильнее, чем плашку на бота.

Кажется, что никто не собирается "наворачивать плашку на бота". И для того и для другого источник -- это какой-то программный интерфейс торчащий с малины за кэширующим слоем на сервере, а дальше хоть боты, хоть http-обработчики, хоть черти волосатые.

**Comment by kaero** [comment]
Кажется, что issue должен был закрыт с #90 но не случилось
