### ISSUE TITLE
Расширение Community Standards

### ISSUE THREAD

**Issue by heeeyflo** [b4ck5p4c3/0x08.in#92]
В текущем виде, наши правила сообщества очень поверхностно декларируют людские взаимодействия. Понятие "be excellent to each other" совсем не строгое, следовательно не способно достаточно конкретно и чётко сформулировать представление о добре и зле в отношении других участников.

Я почекал подобные штуки у других хакспейсов, и у Noisebridge эта политика очень полно сформулирована сформулирована в двух документах: [Community Standards](https://www.noisebridge.net/wiki/Community_Standards) и [Anti-Harrasment Policy](https://www.noisebridge.net/wiki/Anti-Harassment_Policy).

Я предлагаю полностью перенять второй документ, и обсудить что можно перенести из гайдлайнов Noisebridge в наши принципы сообщества.

Я готов заняться переводом и адаптацией если все согласны, иначе, предлагаю перенести обсуждение на следующую встречу во вторник.

_**P.S.:** кажется, я уже поднимал эту тему на собрании от 11/26/2019, но мы её так нигде и не зафиксировали._

**Comment by kaero** [comment]
Я прочитал документы Noisebridge (как и других спейсов, которые мы рассматривали ранее, например, i3). Если внимательно к ним присмотреться можно увидеть, что пункты являются результатом решения каких-то конкретных проблем на основании реальных прецедентов.

Не считаю, что стоит копировать любой из документов беспрецедентно.

Если ты, как и любой другой участник, видишь сейчас конкретные проблемы, требующие решения введением более конкретных правил, то, на мой взгляд, стоит предложить именно их.

**Comment by glitchcore** [comment]
Мне тоже не нравится, что принцип be excellent является довольно неявным.
Основная идея всей этой движухи, на мой взгляд, вот в чем:
отсутствие прецедентов и является прецедентом — есть люди, которым некомфортно, но они не могут сказать об этом, потому что они уже внутри ситуации. И поэтому об этом нужно говорить.

Например, один человек громко матерится или шутит про мамку, а для второго это неприемлемо, но второй по разным причинам не может озвучить свою претензию.

Это сложный вопрос, но кажется, здесь нет универсальных решений, все, что мы можем попытаться сделать — сформировать культуру уважения участников к границам других.

**Comment by heeeyflo** [comment]
> Если внимательно к ним присмотреться можно увидеть, что пункты являются результатом решения каких-то конкретных проблем на основании реальных прецедентов.

@kaero Фил, я не нашёл никакого упоминания о конкретных инцидентах, мне наоборот кажется что в Noisebridge эти политики были внедрены превентивно, чтобы таких инцидентов вообще не возникало. Уточни, пожалуйста, как ты к этому пришёл?

Я согласен с Андреем @aanper в том, что существует много возможных причин, по которым человек не скажет открыто о том, что ему некомфортно. И этими документами я хочу постараться предотвратить серьёзные нарушения личных границ участников, чётко установив личные границы согласно тому, что есть в anti-harassment policy.

Не хочу говорить что мой опыт единственно верный, но я проводил какое-то количество мероприятий, и на них нередко нам (организаторам) приходилось за руку одёргивать людей, нарушающих личные границы стеснительных участников теми взаимодействиями, которые запрещает эта политика. Ежу понятно, что это поможет отнюдь не от всего и что рецепт не универсальный, но хоть что-то.

Ещё Андрей писал про "сформировать культуру уважения участников к границам других". К сожалению, культурный бэкграунд у всех разный, и для некоторых людей штуки вроде кэт-коллинга, нежелательных объятий или обхвата за талию не воспринимаются как нарушения границ.

**Comment by kaero** [comment]
> @kaero Фил, я не нашёл никакого упоминания о конкретных инцидентах, мне наоборот кажется что в Noisebridge эти политики были внедрены превентивно, чтобы таких инцидентов вообще не возникало. Уточни, пожалуйста, как ты к этому пришёл?

Там нет упоминаний прецедентов, кроме одного: в запрете на пользование торрентами. Я читаю их из факта наличия самих правил, так как иначе я не могу объяснить наличие там пункта про животных (который вообще в результате никак не помогает определить excellent ли приводить животных, и видится мне вопросом, который кто-то поднял, но к ответу на который не пришли), но отсутствие пункта... ну, скажем, запрещающего приносить радиоактивные вещества вне изолирующих контейнеров. Просто один прецедент был, и ретроспективно был признан существенным, что привело к запрету, другой был признан несущественным, а третьего еще не случалось. На мой взгляд, нельзя взять чужой опыт прецентов и слепо применить его к себе, например, у нас я бы запретил приводить животных, так как я знаю как минимум двух участников с аллергией, но не собираюсь делать этого до первого прецедента, так как считаю вероятность этого небольшой, да и думаю решить один или два таких случая будет достаточно индивидуальной просьбой с объяснением причины. 

Я лично против жестких правил поведения, так как их очень легко эксплуатировать против сообщества, как буквально (я первый прийду и попрошу всех покинуть спейс, если мы примем правило аналогичное существующему в Noisebridge), так и косвенно, например, разделяя сообщество самими их обсуждениями.

Мы уже ранее обсуждали, и в рамках данного тикета я за то, чтобы дать инструмент сообщить организаторам (опционально анонимно) о нарушающем принципы или правила поведении участника, и рассматривать каждый случай индивидуально, закрыто или открыто на усмотрение организаторов.

**Comment by heeeyflo** [comment]
Давайте тогда:
 — возьмём от нойзбриджа их anti-harassment policy (к ней, вроде бы, нет такие вопросов как к их гайдлайнам), переведём и добавим ссылку на эту страницу в правилах. 
 — дадим инструмент сообщение об поведении, нарушающем правила, пускай это будет та же самая почта.

@kaero этот вариант подходит на первых порах?

**Comment by glitchcore** [comment]
Создавай PR, это будет продуктивнее.

**Comment by glitchcore** [comment]
@imcatwhocode Напоминаю про PR, если ты готов им заняться

**Comment by heeeyflo** [comment]
@aanper да, постараюсь сформировать PR в ближайшие две недели.

**Comment by sntxerror** [comment]
@imcatwhocode когад получится сделать?

**Comment by heeeyflo** [comment]
@sntxerror ~проставил дедлайн.~ тут нет дедлайнов, в общем до 3/01.
/deadline 2020-03-01T06:00:00Z

**Comment by glitchcore** [comment]
Мне тут подкинули еще http://citizencodeofconduct.org/
