### ISSUE TITLE
Уборка помещения

### ISSUE THREAD

**Issue by dm-shi** [b4ck5p4c3/0x08.in#93]
Предлагаю нанять уборщицу. Раз в неделю/две. Я считаю что мы можем заниматься более интеллектуальной деятельностью чем уборка, например модбас запускать. Женщина, которая сдавала помещение, сказала что можно найти уборщицу поспрашивав в других офисах.

**Comment by glitchcore** [comment]
Обсуждали этот вопрос на встрече, я предложил такой вариант: пока нас это не забодает, не думать, пока вроде все с энтузиазмом готовы проводить раз в неделю субботник, лично мне норм отвлечься на часик-другой от модбаса и подмести пол с шутками-прибаутками.
Ну и уборка дело добровольное, если кто-то не хочет мыть толчок, вроде пока есть кому его мыть.

/d
