### ISSUE TITLE
Аккумулятор для СКУДа

### ISSUE THREAD

**Issue by kaero** [b4ck5p4c3/0x08.in#94]
Чтобы СКУД работал при перебоях с элетропитанием предлагается забэкапить питание малины, контроллера, электропривода замка и электромагнита (под вопросом).

**Comment by glitchcore** [comment]
Нужен зарядник + сам аккумулятор (я предлагаю взять автомобильный)

**Comment by NetBUG** [comment]
Удваиваю про автомобильный.
Могу отдать ББП2.1, представляющее собой ЗУ для буферного аккумулятора и БП на 12.8 или около того вольт.
Штатно оно работало с банкой 12V7A*h, но банка померла, кажется.

Дверной замок резервировать надо.
Особенно если есть возможность получать интернет при отсутствии электропитания, например, также запитать ЭВМ с функциями роутера от ББП.

**Comment by glitchcore** [comment]
> Могу отдать ББП2.1

Тащи

**Comment by kaero** [comment]
@komplivit Ты как-то говорил, что можешь добыть нам свинцовых аккумуляторов. Предложение актуально еше? :3

**Comment by kaero** [comment]
Несколько раз обсудили, вроде бы, что кажется, что на самом деле в резервировании питания для СКУДа нет большого смысла: для выхода есть механический фолбэк у всех, для входа есть механический фолбэк у некоторых участников, но в целом при отсутствии электричеств в спейсе делать нечего.

Можно придумать ряд сценариев, когда кто-то из участников без механических ключей принес  что-то тяжелое в спейс, и тут выключили электричество -- это может быть досадно. Стоит ли такой случай введения и обслуживания бэкапа, мне не очевидно.

**Comment by sntxerror** [comment]
Резервирование однозначно стоит добавить. Доступ в спэйс должен быть для всех участников, у кого нет механических ключей, даже когда электричесвто оффнулось.

Сценариев где это пригодится можно придумать множество, все мы просто не зафиксируем. Почему бы не сделать лучше, если это не сложно.

**Comment by glitchcore** [comment]
За полгода не было ни одного прецедента, когда перебои с питанием привели бы к проблемам с доступом (не считая случая, когда мы наговнокодили и двери открылись), я предлагаю закрыть вопрос — мне кажется, проблема действительно столь маловероятна, что в случае ее возникновения можно и с ключом подскочить.

/d
