### ISSUE TITLE
Планирование LAN Party

### ISSUE THREAD

**Issue by z4fd** [b4ck5p4c3/0x08.in#99]
Давно уже говорили, что хотим зимой сделать :) Поэтому поводу у меня есть пара вопросов:
- Когда, есть у кого-то предложения ? 
- И во что будем резаться ? (Героев не предлагать, это может растянуться на более чем сутки :D )

**Comment by kitnerboy** [comment]
LAN пати мо моему мнению будет значительно отличаться от обычных мероприятий по воздухопотреблению. Сейчас часовой доклад со спокойно сидящими дышащими людьми в конце вызывает дискомфорт.
В запале борьбы может случить так называемая "мокрая катка", когда температура и влажность значительно возрастут, после чего будет опасно просто открыть окна - пачка людей тут же застудится и заболеет.
В каком с остоянии сейчас осознание проекта вентиляции?

**Comment by glitchcore** [comment]
Quake 3 arena
HL
Warcraft 3

**Comment by z4fd** [comment]
Нашел докер контейнеры серверов, на неделе припрусь обкатывать все это дело :)

p.s. q3 точно получится кросплотформенной, даже для господ с макбуками. Остальное надо тестить с вином

**Comment by vazhnov** [comment]
OpenArena
Xonotic
Hedgewars
Cube 2: Sauerbraten, map Face-capture, it is similar to CTF-Face (Facing Worlds) from Unreal Tournament 2003

**Comment by kitnerboy** [comment]
Хочу устроить ретро угол с эмуляторами или реальными консолями (если найдутся желающие предоставить). Нужен телек (он вроде как есть, но хз, может будет использован для ранков или трансляции spectator), либо проектор (но тут скорее место не получится организовать).
Я не знаю, каков будет масштаб пати, поэтому хочу узнать, хватит на это ресурсов и места.

**Comment by glitchcore** [comment]
Обсудили ланпати в #147, @z4fd предлагаю сделать PR с описанием события.

**Comment by sntxerror** [comment]
@z4fd как процесс? можно чем то помочь?

**Comment by sntxerror** [comment]
FYI, млжно будет заюзать мой системник с виндой под сервер на винде.

**Comment by z4fd** [comment]
@sntxerror На стадии решения сетевых проблем с сервером :)

з.ы. у нас там сервер стоит, не думаю что системник с виндой понадобиться

**Comment by sntxerror** [comment]
@z4fd может стоит все же в рамках этой таски заняться обсуждением ивента с RTS? Либо расскажи из чего состоит подготовка отдельного ивента и чем можно помочь?

**Comment by glitchcore** [comment]
Раз уж такая ситуация, может провести LAN party в онлайне?)

**Comment by kitnerboy** [comment]
Можно хотя бы отрепетировать всю движуху по серверам и софту, чтобы на мероприятии уже были отработаны основные косяки.

**Comment by glitchcore** [comment]
Предлагаю закрыть в связи с особыми режимами содержания
/d
